#pragma once
#include "game/globals/global_types.h"

extern char g_szUiCloseParen[];

extern "C" {
extern char g_szUiPlaceholderStaticText[];
extern char g_szUiPlaceholderTreasury[];
extern char g_szUiPlaceholderSeason[];
extern char g_szUiPlaceholderSampleText[];

extern char g_szNewGameAllAutoGPs[];
extern char g_szNewGameNamesRandom[];
extern char g_szNewGameNamesHistorical[];
extern char g_szNewGameNamesLabel[];
extern char g_szNewGameDifficultySetting[];
extern char g_szNewGameDifficultyNighOnImpossible[];
extern char g_szNewGameDifficultyHard[];
extern char g_szNewGameDifficultyNormal[];
extern char g_szNewGameDifficultyEasy[];
extern char g_szNewGameDifficultyIntroductory[];
extern char g_szNewGameScenarioPlaceholderTitle[];
extern char g_szNewGameGameNameLabel[];

// Turn-event, navy, army, and trade report text.
extern char g_szUiPlaceholderZero[];
extern char g_szUiOrdersLabel[];
extern char g_szUiDefaultPlanetName[];
extern char g_szUiPickAPlanet[];
extern char g_szUiAsEstimatedBy[];
extern char g_szUiForeignShippingObserved[];
extern char g_szUiHalfDozenShips[];
extern char g_szUiNavalForcesReportOf[];
extern char g_szUiPlaceholderPont[];
extern char g_szUiForeignFleetReport[];
extern char g_szUiTraderIndiamen[];
extern char g_szUiStoppedFromTrade[];
extern char g_szUiPlaceholderPokei[];
extern char g_szUiToLabel[];
extern char g_szUiItemLabel[];
extern char g_szUiCarryingCargoOf[];
extern char g_szUiOwnrTag[];
extern char g_szUiMerchantsBelongingTo[];
extern char g_szUiAndConsistingOf[];
extern char g_szUiByTaskForceCommandedBy[];
extern char g_szUiAdmiralKirk[];
extern char g_szUiInThe[];
extern char g_szUiSeaOfOblongata[];
extern char g_szUiThreeVessels[];
extern char g_szUiResultOfSuccessful[];
extern char g_szUiBlockadeLabel[];
extern char g_szUiEnemyTradeInterrupted[];
extern char g_szUiSeaOfSalamanders[];
extern char g_szUiEngageAllFloating[];
extern char g_szUiForceCurrentlyLocated[];
extern char g_szUiTaskForceReport[];
extern char g_szUiRegularsLabel[];
extern char g_szUiSkirmishersLabel[];
extern char g_szUiMinutemanLabel[];
extern char g_szUiConstructionOptions[];
extern char g_szUiEditTextLabel[];
extern char g_szUiAdmiralBobMinnow[];
extern char g_szUiCompositionLabel[];
extern char g_szUiPatrolTheWaters[];
extern char g_szUiOneHenTwoDucks[];
extern char g_szUiArmyReportTitle[];
extern char g_szUiCivilianReportTitle[];
extern char g_szUiLossesHaxaco[];
extern char g_szUiOrderOfBattle[];
extern char g_szUiHaxacoLegions[];
extern char g_szUiSkirmishReportTitle[];
extern char g_szUiPage14of14[];
extern char g_szUiPlaceholderOne[];
extern char g_szUiAvailableColon[];
extern char g_szUiCostColon[];
extern char g_szUiUniversityTitle[];
extern char g_szUiThousandDollars[];
extern char g_szUiLevel1[];
extern char g_szUiPlaceholder185[];
extern char g_szUiQuantityToOfferLabel[];
extern char g_szUiAvailableLabel[];
extern char g_szUiPriceLabel[];
extern char g_szUiCommodityLabel[];
extern char g_szUiBoardOfTradeLabel[];
extern char g_szUiNilPointerMessage[];
extern char g_szDecimalFormat[];
extern char g_szClientSavePrefix[];
extern char g_szUiFailureMessage[];
} // extern "C"
