// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Category: /imperialism/runtime

#pragma once

typedef unsigned char   undefined;

typedef unsigned char    bool;
typedef unsigned char    byte;
typedef unsigned int    dword;
typedef pointer32 ImageBaseOffset32;

typedef int    sdword;
typedef unsigned char    uchar;
typedef unsigned int    uint;
typedef unsigned long    ulong;
typedef unsigned char    undefined1;
typedef unsigned short    undefined2;
typedef unsigned int    undefined3;
typedef unsigned int    undefined4;
typedef unsigned long long    undefined5;
typedef unsigned long long    undefined6;
typedef unsigned long long    undefined8;
typedef unsigned short    ushort;
typedef short    wchar_t;
typedef unsigned short    word;
typedef struct RuntimeClassState_0063E898 RuntimeClassState_0063E898, *PRuntimeClassState_0063E898;

struct RuntimeClassState_0063E898 {
    void *pRuntimeClassPtr; // manual
    void *pChainHead; // manual
    uint state08; // manual
    uint state0C; // manual
    uint state10; // manual
    uint state14; // manual
    uint seedOrCapacity; // manual
};

typedef struct RuntimeClassState_00646FB0 RuntimeClassState_00646FB0, *PRuntimeClassState_00646FB0;

struct RuntimeClassState_00646FB0 {
    void *pRuntimeClassPtr; // manual
    void *pOwnedBuffer; // manual
    uint state08; // manual
    uint state0C; // manual
    uint state10; // manual
};

typedef struct RuntimeClassState_0064B580 RuntimeClassState_0064B580, *PRuntimeClassState_0064B580;

struct RuntimeClassState_0064B580 {
    void *pRuntimeClassPtr; // manual
    void *pChainHead; // manual
    uint state08; // manual
    uint state0C; // manual
    uint state10; // manual
    uint state14; // manual
    uint seedOrCapacity; // manual
};

typedef struct TUiResourcePoolState TUiResourcePoolState, *PTUiResourcePoolState;

struct TUiResourcePoolState {
    void *pReservedOrOwner; // unknown/reserved slot
    void *pChainHead; // oldest node in active chain
    void *pChainTop; // newest/current node in active chain
    int nDepth; // active pool depth
    void *pFreeListHead; // head of reusable node free-list
    void *pBlockChainHead; // linked allocation block chain
    int nNodesPerBlock; // node count allocated per block
};

