#!/usr/bin/env python3
"""Generate typed vtable call facades from config/vtable_slots.csv."""

from __future__ import annotations

import argparse
from pathlib import Path

from tools.common.pipe_csv import read_pipe_rows
from tools.common.repo import repo_root_from_file, resolve_repo_path


def parse_args() -> argparse.Namespace:
    repo_root = repo_root_from_file(__file__)
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--slots-csv",
        default=str(repo_root / "config" / "vtable_slots.csv"),
        help="Pipe-delimited slot registry path.",
    )
    parser.add_argument(
        "--output",
        default=str(repo_root / "include" / "game" / "generated" / "vcall_facades.h"),
        help="Generated facade header output path.",
    )
    parser.add_argument(
        "--owner-file",
        action="append",
        default=[],
        help="Optional owner_file filter. May be passed multiple times.",
    )
    return parser.parse_args()


def parse_arg_types(value: str) -> list[str]:
    raw = value.strip()
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


def render_wrapper(
    wrapper_name: str,
    return_type: str,
    slot_expr: str,
    arg_types: list[str],
    note: str,
) -> list[str]:
    arity = len(arg_types)
    if arity > 4:
        raise ValueError(f"{wrapper_name}: unsupported arity {arity}, max is 4")

    params = ["void* object"]
    args = []
    for idx, arg_type in enumerate(arg_types):
        arg_name = f"arg{idx}"
        params.append(f"{arg_type} {arg_name}")
        args.append(arg_name)

    lines: list[str] = []
    lines.append(f"// {note}".rstrip())
    signature = f"static __inline {return_type} {wrapper_name}({', '.join(params)}) {{"
    lines.append(signature)
    slot_value = f"static_cast<unsigned int>({slot_expr})"

    if return_type == "void":
        call = f"vcall_runtime::fastcall{arity}v(object, {slot_value}"
        if args:
            call += ", " + ", ".join(args)
        call += ");"
        lines.append(f"  {call}")
        lines.append("}")
        return lines

    call = f"vcall_runtime::fastcall{arity}<{return_type}>(object, {slot_value}"
    if args:
        call += ", " + ", ".join(args)
    call += ");"
    lines.append(f"  return {call}")
    lines.append("}")
    return lines


def build_header(rows: list[dict[str, str]]) -> str:
    out: list[str] = []
    out.append("// AUTOGENERATED FILE. DO NOT EDIT.")
    out.append("// Generated by tools/workflow/generate_vcall_facades.py")
    out.append("#pragma once")
    out.append("")
    out.append('#include "game/vcall_runtime.h"')
    out.append("")

    for row in rows:
        wrapper_name = (row.get("wrapper_name") or "").strip()
        return_type = (row.get("return_type") or "").strip()
        slot_expr = (row.get("slot_expr") or "").strip()
        notes = (row.get("notes") or "").strip()
        arg_types = parse_arg_types(row.get("arg_types") or "")

        if not wrapper_name:
            raise ValueError("Row missing wrapper_name")
        if not return_type:
            raise ValueError(f"{wrapper_name}: missing return_type")
        if not slot_expr:
            raise ValueError(f"{wrapper_name}: missing slot_expr")

        out.extend(
            render_wrapper(
                wrapper_name=wrapper_name,
                return_type=return_type,
                slot_expr=slot_expr,
                arg_types=arg_types,
                note=notes,
            )
        )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    repo_root = repo_root_from_file(__file__)
    slots_csv = resolve_repo_path(repo_root, args.slots_csv)
    output = resolve_repo_path(repo_root, args.output)

    rows = read_pipe_rows(slots_csv)
    if args.owner_file:
        owner_set = set(args.owner_file)
        rows = [row for row in rows if (row.get("owner_file") or "").strip() in owner_set]

    rows.sort(
        key=lambda row: (
            (row.get("owner_file") or "").strip(),
            (row.get("wrapper_name") or "").strip(),
        )
    )

    rendered = build_header(rows)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output} ({len(rows)} wrappers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
