#!/usr/bin/env python3
"""In-repo class-discovery evidence CLI (formerly the external ``impk`` shim).

This restores the subset of ``impk`` commands consumed by
``tools.workflow.class_discovery`` using this repo's checked-in export CSVs and
autogenerated sources as evidence. It has no dependency on the Ghidra project DB
or on the external ``imperialism_knowledge`` checkout — it reads only
``config/symbols.csv`` and ``src/ghidra_autogen/index.csv``.

Invoke as ``python -m tools.workflow.impk_compat <command> ...``.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def repo_root_from_project(project_root: str | None) -> Path:
    if project_root:
        root = Path(project_root).expanduser().resolve()
    else:
        root = Path.cwd().resolve()
    if (root / "config" / "symbols.csv").exists():
        return root
    sibling = root.parent / "imperialism-decomp"
    if (sibling / "config" / "symbols.csv").exists():
        return sibling.resolve()
    raise SystemExit(f"Could not locate imperialism-decomp from project root: {root}")


def normalize_hex(value: str) -> str:
    raw = (value or "").strip().lower()
    if raw.startswith("0x"):
        raw = raw[2:]
    try:
        return f"0x{int(raw, 16):08x}"
    except ValueError:
        return ""


def read_pipe_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as fd:
        return list(csv.DictReader(fd, delimiter="|"))


def write_rows(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fd:
        writer = csv.DictWriter(fd, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def function_rows(decomp_root: Path) -> list[dict[str, str]]:
    index = decomp_root / "src" / "ghidra_autogen" / "index.csv"
    rows = []
    for row in read_pipe_rows(index):
        name = (row.get("name") or "").strip()
        if "::" not in name:
            continue
        class_name = name.split("::", 1)[0].strip()
        address = normalize_hex(row.get("address") or "")
        if not address:
            continue
        rows.append(
            {
                "address": address,
                "class_name": class_name,
                "name": name,
                "confidence": "medium",
                "evidence": f"autogen_index:{row.get('file','')}",
            }
        )
    return rows


def cmd_infer_class(args: argparse.Namespace, lane: str) -> int:
    decomp_root = repo_root_from_project(args.project_root)
    rows = function_rows(decomp_root)
    for row in rows:
        row["evidence"] = f"{lane}:{row['evidence']}"
        if lane in {"decomp", "this_passing"}:
            row["confidence"] = "high"
    write_rows(Path(args.out_csv), ["address", "class_name", "name", "confidence", "evidence"], rows)
    return 0


def cmd_scan_windows_static_vtables(args: argparse.Namespace) -> int:
    decomp_root = repo_root_from_project(args.project_root)
    rows = []
    for row in read_pipe_rows(decomp_root / "config" / "symbols.csv"):
        name = (row.get("name") or "").strip()
        if not name.startswith("g_vtbl"):
            continue
        addr = normalize_hex(row.get("address") or "")
        if not addr:
            continue
        rows.append(
            {
                "vtable_addr": addr,
                "existing_class_name": name.removeprefix("g_vtbl"),
                "symbol_name": name,
                "evidence": "symbols.csv:g_vtbl",
            }
        )
    rows.sort(key=lambda r: r["vtable_addr"])
    write_rows(
        Path(args.out_csv),
        ["vtable_addr", "existing_class_name", "symbol_name", "evidence"],
        rows,
    )
    return 0


def cmd_attribute_vtables(args: argparse.Namespace) -> int:
    in_rows = []
    in_path = Path(args.windows_static_vtables_csv)
    if in_path.exists():
        with in_path.open("r", encoding="utf-8", newline="") as fd:
            in_rows = list(csv.DictReader(fd))
    out_rows = [
        {
            "vtable_addr": row.get("vtable_addr", ""),
            "class_name": row.get("existing_class_name", ""),
            "confidence": "medium",
            "evidence": "static_vtable_symbol_name",
        }
        for row in in_rows
    ]
    write_rows(Path(args.out_csv), ["vtable_addr", "class_name", "confidence", "evidence"], out_rows)
    return 0


def cmd_run_wave(args: argparse.Namespace) -> int:
    static_rows = []
    static_path = Path(args.windows_static_vtables_csv)
    if static_path.exists():
        with static_path.open("r", encoding="utf-8", newline="") as fd:
            static_rows = list(csv.DictReader(fd))
    winner_rows = []
    for row in static_rows:
        class_name = row.get("existing_class_name", "")
        winner_rows.append(
            {
                "vtable_addr": row.get("vtable_addr", ""),
                "existing_class_name": class_name,
                "winner_class": class_name,
                "winner_score": "1",
                "reason": "compat_static_symbol",
                "anchor_sources": "symbols.csv",
                "strong_anchor_sources": "",
                "high_conf_sources": "static_vtable_symbol_name",
                "accepted": "yes",
            }
        )
    write_rows(
        Path(args.winners_csv),
        [
            "vtable_addr",
            "existing_class_name",
            "winner_class",
            "winner_score",
            "reason",
            "anchor_sources",
            "strong_anchor_sources",
            "high_conf_sources",
            "accepted",
        ],
        winner_rows,
    )
    for maybe in [
        args.conflicts_csv,
        args.relabel_csv,
        args.base_labels_apply_csv,
        args.attach_apply_csv,
        args.rename_only_apply_csv,
        args.move_global_apply_csv,
        args.report_csv,
        args.constructor_xrefs_csv,
        args.slot_ownership_csv,
        args.ctor_stores_csv,
        args.ctor_name_csv,
        args.slot_overlap_csv,
        args.macos_slot_count_csv,
        args.matrix_csv,
    ]:
        write_rows(Path(maybe), ["status"], [])
    return 0


def symbol_lookup(decomp_root: Path) -> dict[int, str]:
    out: dict[int, str] = {}
    for row in read_pipe_rows(decomp_root / "config" / "symbols.csv"):
        addr = normalize_hex(row.get("address") or "")
        if addr:
            out[int(addr, 16)] = (row.get("name") or "").strip()
    return out


def find_constructor_xrefs(decomp_root: Path, target_addrs: list[str]) -> list[dict[str, str]]:
    symbols = symbol_lookup(decomp_root)
    wanted = {int(addr, 16): addr for addr in target_addrs if normalize_hex(addr)}
    rows: list[dict[str, str]] = []
    hex_suffixes = {addr: f"{addr_int:06x}" for addr_int, addr in wanted.items()}
    for sym_addr, name in symbols.items():
        lower = name.lower()
        for target_norm in wanted.values():
            suffix = hex_suffixes[target_norm]
            if suffix in lower and ("vtbl" in lower or "vtable" in lower):
                rows.append(
                    {
                        "target_addr": target_norm,
                        "function_addr": f"0x{sym_addr:08x}",
                        "function_name": name,
                        "instruction": f"name_mentions_{suffix}",
                    }
                )
    dedup = {(r["target_addr"], r["function_addr"], r["function_name"]): r for r in rows}
    return sorted(dedup.values(), key=lambda r: (r["target_addr"], r["function_addr"]))


def cmd_list_xrefs(args: argparse.Namespace) -> int:
    decomp_root = repo_root_from_project(None)
    target_addrs = [normalize_hex(raw) for raw in args.addresses]
    rows = find_constructor_xrefs(decomp_root, target_addrs)
    import sys

    writer = csv.DictWriter(
        sys.stdout,
        fieldnames=["target_addr", "function_addr", "function_name", "instruction"],
    )
    writer.writeheader()
    writer.writerows(rows)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="impk_compat")
    sub = parser.add_subparsers(dest="command", required=True)

    for name in [
        "infer_class_from_callers",
        "infer_class_from_decomp",
        "infer_class_from_this_passing",
        "infer_class_from_indirect_refs",
    ]:
        p = sub.add_parser(name)
        p.add_argument("--out-csv", required=True)
        p.add_argument("--project-root", default="")
        p.add_argument("--min-callers")
        p.add_argument("--min-ratio")
        p.add_argument("--caller-depth")
        p.add_argument("--min-votes")

    p = sub.add_parser("scan_windows_static_vtables")
    p.add_argument("--out-csv", required=True)
    p.add_argument("--project-root", default="")

    for name in ["attribute_vtables_from_slot_func_names", "attribute_vtables_from_slot_ownership"]:
        p = sub.add_parser(name)
        p.add_argument("--windows-static-vtables-csv", required=True)
        p.add_argument("--out-csv", required=True)
        p.add_argument("--project-root", default="")
        p.add_argument("--macos-csv")
        p.add_argument("--confidence-filter")

    p = sub.add_parser("run_windows_class_recovery_wave")
    for arg in [
        "windows-static-vtables-csv",
        "windows-runtime-slot-writes-csv",
        "windows-runtime-slot-map-csv",
        "matrix-csv",
        "winners-csv",
        "conflicts-csv",
        "relabel-csv",
        "base-labels-apply-csv",
        "attach-apply-csv",
        "rename-only-apply-csv",
        "move-global-apply-csv",
        "report-csv",
        "constructor-xrefs-csv",
        "slot-ownership-csv",
        "ctor-stores-csv",
        "ctor-name-csv",
        "slot-overlap-csv",
        "macos-slot-count-csv",
    ]:
        p.add_argument(f"--{arg}", required=True)
    p.add_argument("--skip-scan", action="store_true")
    p.add_argument("--skip-bsim", action="store_true")
    p.add_argument("--confidence-filter")
    p.add_argument("--project-root", default="")

    p = sub.add_parser("list_xrefs_to_address")
    p.add_argument("addresses", nargs="+")

    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.command == "infer_class_from_callers":
        return cmd_infer_class(args, "callers")
    if args.command == "infer_class_from_decomp":
        return cmd_infer_class(args, "decomp")
    if args.command == "infer_class_from_this_passing":
        return cmd_infer_class(args, "this_passing")
    if args.command == "infer_class_from_indirect_refs":
        return cmd_infer_class(args, "indirect_refs")
    if args.command == "scan_windows_static_vtables":
        return cmd_scan_windows_static_vtables(args)
    if args.command in {"attribute_vtables_from_slot_func_names", "attribute_vtables_from_slot_ownership"}:
        return cmd_attribute_vtables(args)
    if args.command == "run_windows_class_recovery_wave":
        return cmd_run_wave(args)
    if args.command == "list_xrefs_to_address":
        return cmd_list_xrefs(args)
    raise SystemExit(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
