#include "game/ui_core/CMcEditWindow.h"

#include "game/ui_core/CIncludeView.h"
#include "game/ImperialismApp.h"

// SYNTHETIC: IMPERIALISM 0x00490a00
// CMcEditWindow::`scalar deleting destructor'

// Original AFX_MSGMAP_ENTRY order (0x00649540): ON_WM_CHAR only.
// See CMcWindow.cpp for why the macros are skipped in the compile-only lint build.
#ifndef IMPERIALISM_LINT
BEGIN_MESSAGE_MAP(CMcEditWindow, CEdit)
ON_WM_CHAR()
END_MESSAGE_MAP()
#endif

// GetMessageMap (vtable slot 12) is compiler-generated by the message-map macros above.
// SYNTHETIC: IMPERIALISM 0x00489ee0
// CMcEditWindow::GetMessageMap

// Forward the edit-completion keys (Linefeed/Return/Escape) to the main view
// host as WM_KEYDOWN so the game-side key dispatch sees them, then run the
// default edit-control character processing.
// FUNCTION: IMPERIALISM 0x00489e70
void CMcEditWindow::OnChar(UINT nChar, UINT nRepCnt, UINT nFlags) {
  if (nChar == 0x0a || nChar == 0x0d || nChar == 0x1b) {
    if (GetMainViewHostFromActiveThread() != 0) {
      HWND hostWindow = GetMainViewHostFromActiveThread()->m_hWnd;
      ::SendMessageA(hostWindow, WM_KEYDOWN, nChar, 0);
    }
  }
  CWnd::OnChar(nChar, nRepCnt, nFlags);
}
