#include "game/ui_core/TCommand.h"
#include "game/ui_core/TApplication.h"
#include "game/globals/prelude.h"
#include "game/globals/shared_globals.h"

// SYNTHETIC: IMPERIALISM 0x004877c0
// TCommand::CreateObject

// SYNTHETIC: IMPERIALISM 0x00487800
// TCommand::GetRuntimeClass

IMPLEMENT_DYNCREATE(TCommand, TEvent)

// The compiler emits the 0x648e28 vtable write from the // VTABLE: annotation.

// GetRuntimeClass() at 0x487800 generated by IMPLEMENT_DYNCREATE

// FUNCTION: IMPERIALISM 0x00487820
TCommand::TCommand() : targetContext(0) {}

// Vtable-shape placeholder bodies (the real slot implementations live elsewhere;
// these exist so the class emits its native vtable and derived classes can
// override individual slots through real C++ inheritance).

// SYNTHETIC: IMPERIALISM 0x00487850
// TCommand::`scalar deleting destructor'

// FUNCTION: IMPERIALISM 0x004878a0
void TCommand::ICommand(long itsCommandNumber, TCommandHandler* itsContext, unsigned char canUndo,
                        unsigned char causesChange, TObject* itsChangedObject) {
  (void)canUndo;
  (void)causesChange;
  (void)itsChangedObject;
  TCommandHandler* resolvedContext = itsContext;
  if (resolvedContext == 0) {
    resolvedContext = g_pApplicationUiRootController;
  }
  sourceHandler = 0;
  dispatchMessage = itsCommandNumber;
  targetHandler = resolvedContext;
  commandNumber = itsCommandNumber;
  targetContext = resolvedContext;
}

// FUNCTION: IMPERIALISM 0x004878e0
void TCommand::Free() {
  delete this;
}

// FUNCTION: IMPERIALISM 0x00487900
void TCommand::Process() {
  if (targetContext != 0) {
    targetContext->PerformCommand(this);
  }
}

// FUNCTION: IMPERIALISM 0x00487a00
void TCommand::DoIt() {}
