// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: AFX_THREAD_STATE.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00623477
// GHIDRA_NAME _AFX_THREAD_STATE::_AFX_THREAD_STATE
// GHIDRA_PROTO undefined _AFX_THREAD_STATE()

void __fastcall _AFX_THREAD_STATE::_AFX_THREAD_STATE(undefined4 *param_1)

{
  param_1[0x35] = 0xffffffff;
  param_1[0x41] = 0xffffffff;
  *param_1 = &PTR__scalar_deleting_destructor__00670c4c;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0062348E
// GHIDRA_NAME _AFX_THREAD_STATE::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined 'scalar_deleting_destructor'()

undefined4 __thiscall
_AFX_THREAD_STATE::_scalar_deleting_destructor_(undefined4 param_1,byte param_2)

{
  ~_AFX_THREAD_STATE();
  if ((param_2 & 1) != 0) {
    CNoTrackObject::delete(param_1);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006234A9
// GHIDRA_NAME _AFX_THREAD_STATE::~_AFX_THREAD_STATE
// GHIDRA_PROTO undefined ~_AFX_THREAD_STATE()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: virtual __thiscall _AFX_THREAD_STATE::~_AFX_THREAD_STATE(void)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: virtual __thiscall _AFX_THREAD_STATE::~_AFX_THREAD_STATE(void)
   
   Library: nafxcw retail msvc500:static */

void _AFX_THREAD_STATE::~_AFX_THREAD_STATE(void)

{
  int *piVar1;
  undefined4 uVar2;
  undefined4 *extraout_ECX;
  int unaff_EBP;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  *(undefined4 **)(unaff_EBP + -0x10) = extraout_ECX;
  *extraout_ECX = &PTR__scalar_deleting_destructor__00670c4c;
  piVar1 = (int *)extraout_ECX[0x33];
  *(undefined4 *)(unaff_EBP + -4) = 0;
  if (piVar1 != (int *)0x0) {
    (**(code **)(*piVar1 + 0x60))();
    if ((int *)extraout_ECX[0x33] != (int *)0x0) {
      (**(code **)(*(int *)extraout_ECX[0x33] + 4))(1);
    }
  }
  if ((HHOOK)extraout_ECX[0xc] != (HHOOK)0x0) {
    UnhookWindowsHookEx((HHOOK)extraout_ECX[0xc]);
  }
  if ((HHOOK)extraout_ECX[0xb] != (HHOOK)0x0) {
    UnhookWindowsHookEx((HHOOK)extraout_ECX[0xb]);
  }
  if (extraout_ECX[3] != 0) {
    FreeHeapBlockWithAllocatorTracking(extraout_ECX[3]);
  }
  uVar2 = *(undefined4 *)(unaff_EBP + -0xc);
  *extraout_ECX = &PTR____GCNoTrackObject__UAEPAXI_Z_0066fdf4;
  *unaff_FS_OFFSET = uVar2;
  return;
}

