// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: AFX_CTL3D_STATE.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005E5440
// GHIDRA_NAME _AFX_CTL3D_STATE>::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * _AFX_CTL3D_STATE>::CreateObject(void)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)new(0x30);
  if (puVar1 != (undefined4 *)0x0) {
    *puVar1 = &PTR__scalar_deleting_destructor__00670554;
    return puVar1;
  }
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E5455
// GHIDRA_NAME _AFX_CTL3D_STATE::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined 'scalar_deleting_destructor'()

undefined4 __thiscall
_AFX_CTL3D_STATE::_scalar_deleting_destructor_(undefined4 param_1,byte param_2)

{
  ~_AFX_CTL3D_STATE();
  if ((param_2 & 1) != 0) {
    delete(param_1);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006242DE
// GHIDRA_NAME _AFX_CTL3D_STATE::~_AFX_CTL3D_STATE
// GHIDRA_PROTO undefined ~_AFX_CTL3D_STATE()

void _AFX_CTL3D_STATE::~_AFX_CTL3D_STATE(void)

{
  code *pcVar1;
  undefined4 uVar2;
  undefined4 *extraout_ECX;
  int unaff_EBP;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  *(undefined4 **)(unaff_EBP + -0x10) = extraout_ECX;
  *extraout_ECX = &PTR__scalar_deleting_destructor__00670554;
  pcVar1 = (code *)extraout_ECX[4];
  *(undefined4 *)(unaff_EBP + -4) = 0;
  if (pcVar1 != (code *)0x0) {
    (*pcVar1)(0);
  }
  if ((HMODULE)extraout_ECX[2] != (HMODULE)0x0) {
    FreeLibrary((HMODULE)extraout_ECX[2]);
  }
  uVar2 = *(undefined4 *)(unaff_EBP + -0xc);
  *extraout_ECX = &PTR____GCNoTrackObject__UAEPAXI_Z_0066fdf4;
  *unaff_FS_OFFSET = uVar2;
  return;
}

