// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: CImageList.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005E69E7
// GHIDRA_NAME CImageList::Create
// GHIDRA_PROTO int __thiscall Create(int param_1, int param_2, uint param_3, int param_4, int param_5)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: int __thiscall CImageList::Create(int,int,unsigned int,int,int)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: int __thiscall CImageList::Create(int,int,unsigned int,int,int)
   
   Library: nafxcw retail msvc500:static */

int __thiscall
CImageList::Create(CImageList *this,int param_1,int param_2,uint param_3,int param_4,int param_5)

{
  HIMAGELIST p_Var1;
  int iVar2;
  
  p_Var1 = ImageList_Create(param_1,param_2,param_3,param_4,param_5);
  iVar2 = Attach(this,(int)p_Var1);
  return iVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6A0F
// GHIDRA_NAME CImageList::Create
// GHIDRA_PROTO undefined Create()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Multiple Matches With Same Base Name
// GHIDRA_COMMENT  public: int __thiscall CImageList::Create(unsigned int,int,int,unsigned long)
// GHIDRA_COMMENT  public: int __thiscall CImageList::Create(char const *,int,int,unsigned long)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Multiple Matches With Same Base Name
    public: int __thiscall CImageList::Create(unsigned int,int,int,unsigned long)
    public: int __thiscall CImageList::Create(char const *,int,int,unsigned long)
   
   Library: nafxcw retail msvc500:static */

void __thiscall
CImageList::Create(CImageList *param_1,LPCSTR param_2,int param_3,int param_4,COLORREF param_5)

{
  int iVar1;
  HIMAGELIST p_Var2;
  
  iVar1 = AfxGetModuleState();
  p_Var2 = ImageList_LoadImageA(*(HINSTANCE *)(iVar1 + 0xc),param_2,param_3,param_4,param_5,0,0);
  Attach(param_1,(int)p_Var2);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6A41
// GHIDRA_NAME CImageList::Create
// GHIDRA_PROTO undefined Create()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Multiple Matches With Same Base Name
// GHIDRA_COMMENT  public: int __thiscall CImageList::Create(unsigned int,int,int,unsigned long)
// GHIDRA_COMMENT  public: int __thiscall CImageList::Create(char const *,int,int,unsigned long)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Multiple Matches With Same Base Name
    public: int __thiscall CImageList::Create(unsigned int,int,int,unsigned long)
    public: int __thiscall CImageList::Create(char const *,int,int,unsigned long)
   
   Library: nafxcw retail msvc500:static */

void __thiscall
CImageList::Create(CImageList *param_1,LPCSTR param_2,int param_3,int param_4,COLORREF param_5)

{
  int iVar1;
  HIMAGELIST p_Var2;
  
  iVar1 = AfxGetModuleState();
  p_Var2 = ImageList_LoadImageA(*(HINSTANCE *)(iVar1 + 0xc),param_2,param_3,param_4,param_5,0,0);
  Attach(param_1,(int)p_Var2);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6A73
// GHIDRA_NAME CImageList::Create
// GHIDRA_PROTO undefined Create()

void __thiscall
CImageList::Create(CImageList *param_1,int param_2,int param_3,int param_4,int param_5,int param_6,
                  int param_7)

{
  HIMAGELIST p_Var1;
  
  p_Var1 = ImageList_Merge(*(HIMAGELIST *)(param_2 + 4),param_3,*(HIMAGELIST *)(param_4 + 4),param_5
                           ,param_6,param_7);
  Attach(param_1,(int)p_Var1);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6AA4
// GHIDRA_NAME CImageList::Attach
// GHIDRA_PROTO undefined __thiscall Attach(int param_1)

bool __thiscall CImageList::Attach(CImageList *this,int param_1)

{
  CMapPtrToPtr *this_00;
  undefined4 *puVar1;
  
  if (param_1 != 0) {
    this_00 = (CMapPtrToPtr *)afxMapHMENU(1);
    *(int *)(this + 4) = param_1;
    puVar1 = (undefined4 *)CMapPtrToPtr::operator[](this_00,param_1);
    *puVar1 = this;
  }
  return param_1 != 0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6AD1
// GHIDRA_NAME CImageList::Read
// GHIDRA_PROTO undefined Read()

bool __thiscall CImageList::Read(IStreamVtbl *param_1,undefined4 param_2)

{
  HIMAGELIST p_Var1;
  IStream local_c;
  IStreamVtbl *pIStack_8;
  
  local_c.lpVtbl = param_1;
  pIStack_8 = param_1;
  CArchiveStream::CArchiveStream(param_2);
  p_Var1 = ImageList_Read(&local_c);
  param_1->AddRef = (_func_5233 *)p_Var1;
  return p_Var1 != (HIMAGELIST)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6AFE
// GHIDRA_NAME CImageList::Write
// GHIDRA_PROTO undefined Write()

void __thiscall CImageList::Write(IStreamVtbl *param_1,undefined4 param_2)

{
  IStream local_c;
  IStreamVtbl *pIStack_8;
  
  local_c.lpVtbl = param_1;
  pIStack_8 = param_1;
  CArchiveStream::CArchiveStream(param_2);
  ImageList_Write((HIMAGELIST)param_1->AddRef,&local_c);
  return;
}

