// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: CString.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004B0970
// GHIDRA_NAME CString::CString(void)
// GHIDRA_PROTO undefined CString(void)()

CString * __fastcall CString::CString_void_(CString *param_1)

{
  CString(param_1);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004D6B70
// GHIDRA_NAME CString::operator=
// GHIDRA_PROTO undefined operator=()

CString * __thiscall CString::operator=(CString *param_1,CString *param_2)

{
  operator=(param_1,param_2);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005DB2F0
// GHIDRA_NAME CString::GetLength
// GHIDRA_PROTO undefined GetLength()

undefined4 __fastcall CString::GetLength(int *param_1)

{
  return *(undefined4 *)(*param_1 + -8);
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEB3B
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO undefined CString()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: __thiscall CString::CString(char,int)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: __thiscall CString::CString(char,int)
   
   Library: nafxcw retail msvc500:static */

CString * __thiscall CString::CString(CString *param_1,char param_2,size_t param_3)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)GetSharedEmptyStringRef();
  param_1->m_pchData = (char *)*puVar1;
  if (0 < (int)param_3) {
    AllocBuffer(param_1,param_3);
    memset(param_1->m_pchData,(int)param_2,param_3);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEB73
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO undefined CString()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: __thiscall CString::CString(char const *,int)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: __thiscall CString::CString(char const *,int)
   
   Library: nafxcw retail msvc500:static */

CString * __thiscall CString::CString(CString *param_1,undefined4 param_2,int param_3)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)GetSharedEmptyStringRef();
  param_1->m_pchData = (char *)*puVar1;
  if (param_3 != 0) {
    AllocBuffer(param_1,param_3);
    _memcpy(param_1->m_pchData,param_2,param_3);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEBA9
// GHIDRA_NAME CString::operator=
// GHIDRA_PROTO undefined operator=()

CString * __fastcall CString::operator=(CString *param_1)

{
  AssignCopy(param_1,1,&stack0x00000004);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEC82
// GHIDRA_NAME CString::Mid
// GHIDRA_PROTO undefined Mid()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: class CString __thiscall CString::Mid(int)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: class CString __thiscall CString::Mid(int)const 
   
   Library: nafxcw retail msvc500:static */

undefined4 __thiscall CString::Mid(int *param_1,undefined4 param_2,int param_3)

{
  Mid(param_2,param_3,*(int *)(*param_1 + -8) - param_3);
  return param_2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FECA5
// GHIDRA_NAME CString::Mid
// GHIDRA_PROTO undefined Mid()

undefined4 CString::Mid(void)

{
  int iVar1;
  undefined4 uVar2;
  int *extraout_ECX;
  int iVar3;
  int unaff_EBP;
  int iVar4;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  *(undefined4 *)(unaff_EBP + -0x14) = 0;
  iVar3 = *(int *)(unaff_EBP + 0xc);
  *(int **)(unaff_EBP + -0x10) = extraout_ECX;
  if (iVar3 < 0) {
    iVar3 = 0;
  }
  iVar4 = *(int *)(unaff_EBP + 0x10);
  if (iVar4 < 0) {
    iVar4 = 0;
  }
  iVar1 = *(int *)(*extraout_ECX + -8);
  if (iVar1 < iVar4 + iVar3) {
    iVar4 = iVar1 - iVar3;
  }
  if (iVar1 < iVar3) {
    iVar4 = 0;
  }
  CString((CString *)(unaff_EBP + 0xc));
  *(undefined4 *)(unaff_EBP + -4) = 1;
  AllocCopy(unaff_EBP + 0xc,iVar4,iVar3,0);
  CString(*(CString **)(unaff_EBP + 8),(CString *)(unaff_EBP + 0xc));
  *(undefined4 *)(unaff_EBP + -0x14) = 1;
  *(undefined1 *)(unaff_EBP + -4) = 0;
  ~CString((CString *)(unaff_EBP + 0xc));
  uVar2 = *(undefined4 *)(unaff_EBP + 8);
  *unaff_FS_OFFSET = *(undefined4 *)(unaff_EBP + -0xc);
  return uVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FED30
// GHIDRA_NAME CString::Right
// GHIDRA_PROTO undefined Right()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: class CString __thiscall CString::Right(int)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: class CString __thiscall CString::Right(int)const 
   
   Library: nafxcw retail msvc500:static */

undefined4 CString::Right(void)

{
  int iVar1;
  undefined4 uVar2;
  int *extraout_ECX;
  int iVar3;
  int unaff_EBP;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  *(undefined4 *)(unaff_EBP + -0x10) = 0;
  iVar3 = *(int *)(unaff_EBP + 0xc);
  if (iVar3 < 0) {
    iVar3 = 0;
  }
  else if (*(int *)(*extraout_ECX + -8) < iVar3) {
    iVar3 = *(int *)(*extraout_ECX + -8);
  }
  CString((CString *)(unaff_EBP + 0xc));
  iVar1 = *(int *)(*extraout_ECX + -8);
  *(undefined4 *)(unaff_EBP + -4) = 1;
  AllocCopy(unaff_EBP + 0xc,iVar3,iVar1 - iVar3,0);
  CString(*(CString **)(unaff_EBP + 8),(CString *)(unaff_EBP + 0xc));
  *(undefined4 *)(unaff_EBP + -0x10) = 1;
  *(undefined1 *)(unaff_EBP + -4) = 0;
  ~CString((CString *)(unaff_EBP + 0xc));
  uVar2 = *(undefined4 *)(unaff_EBP + 8);
  *unaff_FS_OFFSET = *(undefined4 *)(unaff_EBP + -0xc);
  return uVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEDAD
// GHIDRA_NAME CString::Left
// GHIDRA_PROTO undefined Left()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: class CString __thiscall CString::Left(int)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: class CString __thiscall CString::Left(int)const 
   
   Library: nafxcw retail msvc500:static */

undefined4 CString::Left(void)

{
  undefined4 uVar1;
  int *extraout_ECX;
  int unaff_EBP;
  int iVar2;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  *(undefined4 *)(unaff_EBP + -0x10) = 0;
  iVar2 = *(int *)(unaff_EBP + 0xc);
  if (iVar2 < 0) {
    iVar2 = 0;
  }
  else if (*(int *)(*extraout_ECX + -8) < iVar2) {
    iVar2 = *(int *)(*extraout_ECX + -8);
  }
  CString((CString *)(unaff_EBP + 0xc));
  *(undefined4 *)(unaff_EBP + -4) = 1;
  AllocCopy(unaff_EBP + 0xc,iVar2,0,0);
  CString(*(CString **)(unaff_EBP + 8),(CString *)(unaff_EBP + 0xc));
  *(undefined4 *)(unaff_EBP + -0x10) = 1;
  *(undefined1 *)(unaff_EBP + -4) = 0;
  ~CString((CString *)(unaff_EBP + 0xc));
  uVar1 = *(undefined4 *)(unaff_EBP + 8);
  *unaff_FS_OFFSET = *(undefined4 *)(unaff_EBP + -0xc);
  return uVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEE24
// GHIDRA_NAME CString::SpanExcluding
// GHIDRA_PROTO undefined SpanExcluding()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Multiple Matches With Different Base Names
// GHIDRA_COMMENT  public: class CString __thiscall CString::SpanExcluding(char const *)const
// GHIDRA_COMMENT  public: class CString __thiscall CString::SpanIncluding(char const *)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Multiple Matches With Different Base Names
    public: class CString __thiscall CString::SpanExcluding(char const *)const 
    public: class CString __thiscall CString::SpanIncluding(char const *)const 
   
   Library: nafxcw retail msvc500:static */

undefined4 __thiscall
CString::SpanExcluding(undefined4 *param_1,undefined4 param_2,undefined4 param_3)

{
  undefined4 uVar1;
  
  uVar1 = __mbsspn(*param_1,param_3);
  Left(param_2,uVar1);
  return param_2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEE78
// GHIDRA_NAME CString::ReverseFind
// GHIDRA_PROTO undefined ReverseFind()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: int __thiscall CString::ReverseFind(char)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: int __thiscall CString::ReverseFind(char)const 
   
   Library: nafxcw retail msvc500:static */

int __thiscall CString::ReverseFind(int *param_1,undefined1 param_2)

{
  int iVar1;
  
  iVar1 = __mbsrchr(*param_1,param_2);
  if (iVar1 == 0) {
    iVar1 = -1;
  }
  else {
    iVar1 = iVar1 - *param_1;
  }
  return iVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEE99
// GHIDRA_NAME CString::FindOneOf
// GHIDRA_PROTO undefined FindOneOf()

int __thiscall CString::FindOneOf(int *param_1,undefined4 param_2)

{
  int iVar1;
  
  iVar1 = __mbsstr(*param_1,param_2);
  if (iVar1 == 0) {
    iVar1 = -1;
  }
  else {
    iVar1 = iVar1 - *param_1;
  }
  return iVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FEEB8
// GHIDRA_NAME CString::FormatV
// GHIDRA_PROTO undefined FormatV()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  protected: void __thiscall CString::FormatV(char const *,char *)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    protected: void __thiscall CString::FormatV(char const *,char *)
   
   Library: nafxcw retail msvc500:static */

void __thiscall CString::FormatV(CString *param_1,char *param_2,int *param_3)

{
  int *piVar1;
  char cVar2;
  char *pcVar3;
  int iVar4;
  uint uVar5;
  int *piVar6;
  int *piVar7;
  int iVar8;
  bool bVar9;
  int local_10;
  int local_c;
  
  piVar1 = param_3;
  local_10 = 0;
  cVar2 = *param_2;
  piVar7 = param_3;
  pcVar3 = param_2;
  do {
    if (cVar2 == '\0') {
      GetBuffer(param_1,local_10);
      _vsprintf(param_1->m_pchData,param_2,piVar1);
      ReleaseBuffer(param_1,-1);
      return;
    }
    if (*pcVar3 == '%') {
      pcVar3 = (char *)__mbsinc(pcVar3);
      cVar2 = *pcVar3;
      if (cVar2 == '%') goto LAB_005ff0df;
      iVar8 = 0;
      param_3 = (int *)0x0;
      piVar6 = piVar7;
      while (cVar2 != '\0') {
        if (cVar2 == '#') {
          local_10 = local_10 + 2;
        }
        else if (cVar2 == '*') {
          param_3 = (int *)*piVar6;
          piVar6 = piVar6 + 1;
        }
        else if ((((cVar2 != '-') && (cVar2 != '+')) && (cVar2 != '0')) && (cVar2 != ' ')) break;
        pcVar3 = (char *)__mbsinc(pcVar3);
        cVar2 = *pcVar3;
      }
      if (param_3 == (int *)0x0) {
        param_3 = (int *)_atoi(pcVar3);
        while ((*pcVar3 != '\0' && (iVar4 = __ismbcdigit((int)*pcVar3), iVar4 != 0))) {
          pcVar3 = (char *)__mbsinc(pcVar3);
        }
      }
      local_c = 0;
      if (*pcVar3 == '.') {
        pcVar3 = (char *)__mbsinc(pcVar3);
        if (*pcVar3 == '*') {
          local_c = *piVar6;
          piVar6 = piVar6 + 1;
          pcVar3 = (char *)__mbsinc(pcVar3);
        }
        else {
          local_c = _atoi(pcVar3);
          while ((*pcVar3 != '\0' && (iVar4 = __ismbcdigit((int)*pcVar3), iVar4 != 0))) {
            pcVar3 = (char *)__mbsinc(pcVar3);
          }
        }
      }
      cVar2 = *pcVar3;
      uVar5 = 0;
      if (((cVar2 == 'F') || (cVar2 == 'L')) || (cVar2 == 'N')) {
LAB_005fefc4:
        pcVar3 = (char *)__mbsinc(pcVar3);
      }
      else {
        if (cVar2 == 'h') {
          uVar5 = 0x10000;
          goto LAB_005fefc4;
        }
        if (cVar2 == 'l') {
          uVar5 = 0x20000;
          goto LAB_005fefc4;
        }
      }
      uVar5 = uVar5 | (int)*pcVar3;
      piVar7 = piVar6;
      if ((int)uVar5 < 0x54) {
        if (uVar5 == 0x53) goto LAB_005ff023;
        bVar9 = uVar5 == 0x43;
LAB_005feffe:
        if (bVar9) {
LAB_005ff057:
          iVar8 = 2;
          piVar7 = piVar6 + 1;
        }
      }
      else {
        if (0x73 < (int)uVar5) {
          if ((int)uVar5 < 0x10054) {
            if (uVar5 == 0x10053) goto LAB_005ff036;
            bVar9 = uVar5 == 0x10043;
            goto LAB_005feffe;
          }
          if (uVar5 != 0x10063) {
            if (uVar5 == 0x10073) goto LAB_005ff036;
            if (uVar5 != 0x20043) {
              if (uVar5 != 0x20053) {
                if (uVar5 == 0x20063) goto LAB_005ff057;
                if (uVar5 != 0x20073) goto LAB_005ff05d;
              }
LAB_005ff023:
              if (*piVar6 == 0) goto LAB_005ff040;
              iVar8 = _wcslen(*piVar6);
              goto LAB_005ff04b;
            }
          }
          goto LAB_005ff057;
        }
        if (uVar5 == 0x73) {
LAB_005ff036:
          if ((LPCSTR)*piVar6 == (LPCSTR)0x0) {
LAB_005ff040:
            iVar8 = 6;
          }
          else {
            iVar8 = lstrlenA((LPCSTR)*piVar6);
LAB_005ff04b:
            piVar7 = piVar6 + 1;
            if (0 < iVar8) goto LAB_005ff05d;
            iVar8 = 1;
          }
          piVar7 = piVar6 + 1;
        }
        else if (uVar5 == 99) goto LAB_005ff057;
      }
LAB_005ff05d:
      if (iVar8 == 0) {
        cVar2 = *pcVar3;
        if (cVar2 < 'Y') {
          if (cVar2 == 'X') {
LAB_005ff0ba:
            piVar7 = piVar7 + 1;
            iVar8 = 0x20;
          }
          else {
            if (cVar2 != 'G') goto LAB_005ff0d5;
LAB_005ff09b:
            piVar7 = piVar7 + 2;
            iVar8 = 0x80;
          }
          local_c = local_c + (int)param_3;
          bVar9 = SBORROW4(local_c,iVar8);
          iVar4 = local_c - iVar8;
          goto LAB_005ff0cc;
        }
        if (cVar2 < 'j') {
          if ((cVar2 == 'i') || (cVar2 == 'd')) goto LAB_005ff0ba;
          if (('d' < cVar2) && (cVar2 < 'h')) goto LAB_005ff09b;
        }
        else if (cVar2 == 'n') {
          piVar7 = piVar7 + 1;
        }
        else if (((cVar2 == 'o') || (cVar2 == 'p')) || ((cVar2 == 'u' || (cVar2 == 'x'))))
        goto LAB_005ff0ba;
      }
      else {
        if (iVar8 <= (int)param_3) {
          iVar8 = (int)param_3;
        }
        if (local_c == 0) goto LAB_005ff0d5;
        bVar9 = SBORROW4(iVar8,local_c);
        iVar4 = iVar8 - local_c;
LAB_005ff0cc:
        if (bVar9 == iVar4 < 0) {
          iVar8 = local_c;
        }
      }
LAB_005ff0d5:
      local_10 = local_10 + iVar8;
    }
    else {
LAB_005ff0df:
      iVar8 = _mbclen(pcVar3);
      local_10 = local_10 + iVar8;
    }
    pcVar3 = (char *)__mbsinc(pcVar3);
    cVar2 = *pcVar3;
  } while( true );
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FF15E
// GHIDRA_NAME CString::Format
// GHIDRA_PROTO undefined Format()

void CString::Format(undefined4 param_1,undefined4 param_2)

{
  FormatV(param_2,&stack0x0000000c);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FF1BA
// GHIDRA_NAME CString::FormatMessageA
// GHIDRA_PROTO undefined FormatMessageA()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: void __cdecl CString::FormatMessageA(char const *,...)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: void __cdecl CString::FormatMessageA(char const *,...)
   
   Library: nafxcw retail msvc500:static */

void CString::FormatMessageA(CString *param_1,LPCVOID param_2)

{
  DWORD DVar1;
  va_list local_c;
  char *local_8;
  
  local_c = &stack0x0000000c;
  DVar1 = ::FormatMessageA(0x500,param_2,0,0,(LPSTR)&local_8,0,&local_c);
  if ((DVar1 == 0) || (local_8 == (char *)0x0)) {
    AfxThrowMemoryException();
  }
  operator=(param_1,local_8);
  LocalFree(local_8);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FF206
// GHIDRA_NAME CString::FormatMessageA
// GHIDRA_PROTO undefined FormatMessageA()

void CString::FormatMessageA(void)

{
  DWORD DVar1;
  int unaff_EBP;
  undefined4 *unaff_FS_OFFSET;
  
  _EH_prolog();
  CString((CString *)(unaff_EBP + -0x14));
  *(undefined4 *)(unaff_EBP + -4) = 0;
  LoadStringA(*(undefined4 *)(unaff_EBP + 0xc));
  *(int *)(unaff_EBP + -0x18) = unaff_EBP + 0x10;
  DVar1 = ::FormatMessageA(0x500,*(LPCVOID *)(unaff_EBP + -0x14),0,0,(LPSTR)(unaff_EBP + -0x10),0,
                           (va_list *)(unaff_EBP + -0x18));
  if ((DVar1 == 0) || (*(int *)(unaff_EBP + -0x10) == 0)) {
    AfxThrowMemoryException();
  }
  operator=(*(CString **)(unaff_EBP + 8),*(char **)(unaff_EBP + -0x10));
  LocalFree(*(HLOCAL *)(unaff_EBP + -0x10));
  *(undefined4 *)(unaff_EBP + -4) = 0xffffffff;
  *(undefined4 *)(unaff_EBP + -0x18) = 0;
  ~CString((CString *)(unaff_EBP + -0x14));
  *unaff_FS_OFFSET = *(undefined4 *)(unaff_EBP + -0xc);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FF289
// GHIDRA_NAME CString::TrimRight
// GHIDRA_PROTO undefined TrimRight()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: void __thiscall CString::TrimRight(void)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: void __thiscall CString::TrimRight(void)
   
   Library: nafxcw retail msvc500:static */

void __fastcall CString::TrimRight(CString *param_1)

{
  int iVar1;
  char *pcVar2;
  char *pcVar3;
  
  CopyBeforeWrite(param_1);
  pcVar3 = (char *)0x0;
  for (pcVar2 = param_1->m_pchData; *pcVar2 != '\0'; pcVar2 = (char *)__mbsinc(pcVar2)) {
    iVar1 = __ismbcspace((int)*pcVar2);
    if (iVar1 == 0) {
      pcVar3 = (char *)0x0;
    }
    else if (pcVar3 == (char *)0x0) {
      pcVar3 = pcVar2;
    }
  }
  if (pcVar3 != (char *)0x0) {
    *pcVar3 = '\0';
    *(int *)(param_1->m_pchData + -8) = (int)pcVar3 - (int)param_1->m_pchData;
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FF2D2
// GHIDRA_NAME CString::TrimLeft
// GHIDRA_PROTO undefined TrimLeft()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: void __thiscall CString::TrimLeft(void)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: void __thiscall CString::TrimLeft(void)
   
   Library: nafxcw retail msvc500:static */

void __fastcall CString::TrimLeft(CString *param_1)

{
  char *pcVar1;
  int iVar2;
  char *pcVar3;
  
  CopyBeforeWrite(param_1);
  pcVar3 = param_1->m_pchData;
  while( true ) {
    iVar2 = __ismbcspace((int)*pcVar3);
    if (iVar2 == 0) break;
    pcVar3 = (char *)__mbsinc(pcVar3);
  }
  pcVar1 = param_1->m_pchData;
  iVar2 = *(int *)(pcVar1 + -8);
  memmove(pcVar1,pcVar3,pcVar1 + (iVar2 - (int)pcVar3) + 1);
  *(char **)(param_1->m_pchData + -8) = pcVar1 + (iVar2 - (int)pcVar3);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605797
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO void __thiscall CString(void)

void __thiscall CString::CString(CString *this)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)GetSharedEmptyStringRef();
  this->m_pchData = (char *)*puVar1;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006057A7
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO CString * __thiscall CString(CString * src_ref)

CString * __thiscall CString::CString(CString *this,CString *src_ref)

{
  char *pcVar1;
  undefined4 *puVar2;
  
  pcVar1 = src_ref->m_pchData;
  if (*(int *)(pcVar1 + -0xc) < 0) {
    puVar2 = (undefined4 *)GetSharedEmptyStringRef();
    this->m_pchData = (char *)*puVar2;
    operator=(this,src_ref->m_pchData);
  }
  else {
    this->m_pchData = pcVar1;
    InterlockedIncrement((LONG *)(pcVar1 + -0xc));
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006057DE
// GHIDRA_NAME CString::AllocBuffer
// GHIDRA_PROTO void __thiscall AllocBuffer(int text_length)

void __thiscall CString::AllocBuffer(CString *this,int text_length)

{
  undefined4 *puVar1;
  char *pcVar2;
  
  if (text_length == 0) {
    puVar1 = (undefined4 *)GetSharedEmptyStringRef();
    pcVar2 = (char *)*puVar1;
  }
  else {
    puVar1 = (undefined4 *)operator_new(text_length + 0xd);
    *puVar1 = 1;
    *(undefined1 *)((int)puVar1 + text_length + 0xc) = 0;
    puVar1[1] = text_length;
    puVar1[2] = text_length;
    pcVar2 = (char *)(puVar1 + 3);
  }
  this->m_pchData = pcVar2;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605818
// GHIDRA_NAME CString::Release
// GHIDRA_PROTO undefined Release()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  protected: void __thiscall CString::Release(void)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    protected: void __thiscall CString::Release(void)
   
   Library: nafxcw retail msvc500:static */

void __fastcall CString::Release(int *param_1)

{
  LONG LVar1;
  int *piVar2;
  
  if ((LONG *)(*param_1 + -0xc) != (LONG *)afxDataNil) {
    LVar1 = InterlockedDecrement((LONG *)(*param_1 + -0xc));
    if (LVar1 < 1) {
      operator_delete(*param_1 + -0xc);
    }
    piVar2 = (int *)GetSharedEmptyStringRef();
    *param_1 = *piVar2;
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0060586D
// GHIDRA_NAME CString::Empty
// GHIDRA_PROTO undefined Empty()

void __fastcall CString::Empty(CString *param_1)

{
  if (*(int *)(param_1->m_pchData + -8) != 0) {
    if (-1 < *(int *)(param_1->m_pchData + -0xc)) {
      Release();
      return;
    }
    operator=(param_1,&afxChNil);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0060588B
// GHIDRA_NAME CString::CopyBeforeWrite
// GHIDRA_PROTO void __thiscall CopyBeforeWrite(void)

void __thiscall CString::CopyBeforeWrite(CString *this)

{
  char *pcVar1;
  
  pcVar1 = this->m_pchData;
  if (1 < *(int *)(pcVar1 + -0xc)) {
    Release();
    AllocBuffer(this,*(int *)(pcVar1 + -8));
    _memcpy(this->m_pchData,pcVar1,*(int *)(pcVar1 + -8) + 1);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006058B9
// GHIDRA_NAME CString::AllocBeforeWrite
// GHIDRA_PROTO void __thiscall AllocBeforeWrite(int required_capacity)

void __thiscall CString::AllocBeforeWrite(CString *this,int required_capacity)

{
  if ((1 < *(int *)(this->m_pchData + -0xc)) || (*(int *)(this->m_pchData + -4) < required_capacity)
     ) {
    Release();
    AllocBuffer(this,required_capacity);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006058E2
// GHIDRA_NAME CString::~CString
// GHIDRA_PROTO void __thiscall ~CString(void)

void __thiscall CString::~CString(CString *this)

{
  LONG LVar1;
  
  if (this->m_pchData + -0xc != afxDataNil) {
    LVar1 = InterlockedDecrement((LONG *)(this->m_pchData + -0xc));
    if (LVar1 < 1) {
      operator_delete(this->m_pchData + -0xc);
    }
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0060590B
// GHIDRA_NAME CString::AllocCopy
// GHIDRA_PROTO undefined AllocCopy()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  protected: void __thiscall CString::AllocCopy(class CString &,int,int,int)const
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    protected: void __thiscall CString::AllocCopy(class CString &,int,int,int)const 
   
   Library: nafxcw retail msvc500:static */

void __thiscall
CString::AllocCopy(int *param_1,CString *param_2,int param_3,int param_4,int param_5)

{
  undefined4 *puVar1;
  
  if (param_5 + param_3 == 0) {
    puVar1 = (undefined4 *)GetSharedEmptyStringRef();
    param_2->m_pchData = (char *)*puVar1;
  }
  else {
    AllocBuffer(param_2,param_5 + param_3);
    _memcpy(param_2->m_pchData,*param_1 + param_4,param_3);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605950
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO void __thiscall CString(char * text_or_resource_id)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Initializes a shared-string ref from either an ANSI C-string pointer or (when high word is zero) a resource/string-table id in the low word.
// GHIDRA_COMMENT_END

/* Initializes a shared-string ref from either an ANSI C-string pointer or (when high word is zero)
   a resource/string-table id in the low word. */

void __thiscall CString::CString(CString *this,char *text_or_resource_id)

{
  undefined4 *puVar1;
  int text_length;
  
  puVar1 = (undefined4 *)GetSharedEmptyStringRef();
  this->m_pchData = (char *)*puVar1;
  if (text_or_resource_id != (char *)0x0) {
    if ((short)((uint)text_or_resource_id >> 0x10) == 0) {
      LoadStringA((uint)text_or_resource_id & 0xffff);
      return;
    }
    if (text_or_resource_id != (char *)0x0) {
      text_length = lstrlenA(text_or_resource_id);
      goto LAB_0060598e;
    }
  }
  text_length = 0;
LAB_0060598e:
  if (text_length != 0) {
    AllocBuffer(this,text_length);
    _memcpy(this->m_pchData,text_or_resource_id,text_length);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006059AE
// GHIDRA_NAME CString::CString
// GHIDRA_PROTO undefined CString()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: __thiscall CString::CString(unsigned short const *)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: __thiscall CString::CString(unsigned short const *)
   
   Library: nafxcw retail msvc500:static */

CString * __thiscall CString::CString(CString *param_1,int param_2)

{
  undefined4 *puVar1;
  int iVar2;
  
  puVar1 = (undefined4 *)GetSharedEmptyStringRef();
  param_1->m_pchData = (char *)*puVar1;
  if (param_2 == 0) {
    iVar2 = 0;
  }
  else {
    iVar2 = _wcslen(param_2);
  }
  if (iVar2 != 0) {
    AllocBuffer(param_1,iVar2 * 2);
    _wcstombsz(param_1->m_pchData,param_2,iVar2 * 2 + 1);
    ReleaseBuffer(param_1,-1);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x006059FC
// GHIDRA_NAME CString::AssignCopy
// GHIDRA_PROTO void __thiscall AssignCopy(int new_length, char * src_text)

void __thiscall CString::AssignCopy(CString *this,int new_length,char *src_text)

{
  AllocBeforeWrite(this,new_length);
  _memcpy(this->m_pchData,src_text,new_length);
  *(int *)(this->m_pchData + -8) = new_length;
  this->m_pchData[new_length] = '\0';
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605A29
// GHIDRA_NAME CString::operator=
// GHIDRA_PROTO CString * __thiscall operator=(CString * src_ref)

CString * __thiscall CString::operator=(CString *this,CString *src_ref)

{
  char *pcVar1;
  astruct_29 *piVar2;
  
  pcVar1 = src_ref->m_pchData;
  if (this->m_pchData != pcVar1) {
    piVar2 = (astruct_29 *)(this->m_pchData + -0xc);
    if (((piVar2->field0_0x0 < 0) && (piVar2 != (astruct_29 *)afxDataNil)) ||
       (*(int *)(pcVar1 + -0xc) < 0)) {
      AssignCopy(this,*(int *)(pcVar1 + -8),pcVar1);
    }
    else {
      Release();
      pcVar1 = src_ref->m_pchData;
      this->m_pchData = pcVar1;
      InterlockedIncrement((LONG *)(pcVar1 + -0xc));
    }
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605A78
// GHIDRA_NAME CString::operator=
// GHIDRA_PROTO CString * __thiscall operator=(char * src_text)

CString * __thiscall CString::operator=(CString *this,char *src_text)

{
  int new_length;
  
  if (src_text == (char *)0x0) {
    new_length = 0;
  }
  else {
    new_length = lstrlenA(src_text);
  }
  AssignCopy(this,new_length,src_text);
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605A9F
// GHIDRA_NAME CString::operator=
// GHIDRA_PROTO undefined operator=()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: class CString const & __thiscall CString::operator=(unsigned short const *)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: class CString const & __thiscall CString::operator=(unsigned short const *)
   
   Library: nafxcw retail msvc500:static */

CString * __thiscall CString::operator=(CString *param_1,int param_2)

{
  int iVar1;
  
  if (param_2 == 0) {
    iVar1 = 0;
  }
  else {
    iVar1 = _wcslen(param_2);
  }
  AllocBeforeWrite(param_1,iVar1 * 2);
  _wcstombsz(param_1->m_pchData,param_2,iVar1 * 2 + 1);
  ReleaseBuffer(param_1,-1);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605AE0
// GHIDRA_NAME CString::ConcatCopy
// GHIDRA_PROTO void __thiscall ConcatCopy(int lhs_len, char * lhs_text, int rhs_len, char * rhs_text)

void __thiscall
CString::ConcatCopy(CString *this,int lhs_len,char *lhs_text,int rhs_len,char *rhs_text)

{
  if (rhs_len + lhs_len != 0) {
    AllocBuffer(this,rhs_len + lhs_len);
    _memcpy(this->m_pchData,lhs_text,lhs_len);
    _memcpy(this->m_pchData + lhs_len,rhs_text,rhs_len);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605C6F
// GHIDRA_NAME CString::ConcatInPlace
// GHIDRA_PROTO void __thiscall ConcatInPlace(int append_len, char * append_text)

void __thiscall CString::ConcatInPlace(CString *this,int append_len,char *append_text)

{
  char *lhs_text;
  
  if (append_len != 0) {
    lhs_text = this->m_pchData;
    if ((*(int *)(lhs_text + -0xc) < 2) &&
       (append_len + *(int *)(lhs_text + -8) <= *(int *)(lhs_text + -4))) {
      _memcpy(lhs_text + *(int *)(lhs_text + -8),append_text,append_len);
      *(int *)(this->m_pchData + -8) = *(int *)(this->m_pchData + -8) + append_len;
      this->m_pchData[*(int *)(this->m_pchData + -8)] = '\0';
    }
    else {
      ConcatCopy(this,*(int *)(lhs_text + -8),lhs_text,append_len,append_text);
      DecrementSharedStringRefCountAndFree(lhs_text + -0xc);
    }
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605CCE
// GHIDRA_NAME CString::operator+=
// GHIDRA_PROTO undefined4 __thiscall operator+=(char * text)

CString * __thiscall CString::operator+=(CString *this,char *text)

{
  int append_len;
  
  if (text == (char *)0x0) {
    append_len = 0;
  }
  else {
    append_len = lstrlenA(text);
  }
  ConcatInPlace(this,append_len,text);
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605CF5
// GHIDRA_NAME CString::operator+=
// GHIDRA_PROTO undefined operator+=()

CString * __fastcall CString::operator+=(CString *param_1)

{
  ConcatInPlace(param_1,1,&stack0x00000004);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605D0A
// GHIDRA_NAME CString::operator+=
// GHIDRA_PROTO undefined operator+=()

CString * __thiscall CString::operator+=(CString *param_1,undefined4 *param_2)

{
  ConcatInPlace(param_1,*(int *)((char *)*param_2 + -8),(char *)*param_2);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605D22
// GHIDRA_NAME CString::GetBuffer
// GHIDRA_PROTO int __thiscall GetBuffer(int min_capacity)

int __thiscall CString::GetBuffer(CString *this,int min_capacity)

{
  char *pcVar1;
  int iVar2;
  
  pcVar1 = this->m_pchData;
  if ((1 < *(int *)(pcVar1 + -0xc)) || (*(int *)(pcVar1 + -4) < min_capacity)) {
    iVar2 = *(int *)(pcVar1 + -8);
    if (min_capacity < iVar2) {
      min_capacity = iVar2;
    }
    AllocBuffer(this,min_capacity);
    _memcpy(this->m_pchData,pcVar1,iVar2 + 1);
    *(int *)(this->m_pchData + -8) = iVar2;
    DecrementSharedStringRefCountAndFree(pcVar1 + -0xc);
  }
  return (int)this->m_pchData;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605D71
// GHIDRA_NAME CString::ReleaseBuffer
// GHIDRA_PROTO void __thiscall ReleaseBuffer(int new_length)

void __thiscall CString::ReleaseBuffer(CString *this,int new_length)

{
  CopyBeforeWrite(this);
  if (new_length == -1) {
    new_length = lstrlenA(this->m_pchData);
  }
  *(int *)(this->m_pchData + -8) = new_length;
  this->m_pchData[new_length] = '\0';
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605D99
// GHIDRA_NAME CString::GetBufferSetLength
// GHIDRA_PROTO int __thiscall GetBufferSetLength(int new_length)

int __thiscall CString::GetBufferSetLength(CString *this,int new_length)

{
  GetBuffer(this,new_length);
  *(int *)(this->m_pchData + -8) = new_length;
  this->m_pchData[new_length] = '\0';
  return (int)this->m_pchData;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605DEC
// GHIDRA_NAME CString::LockBuffer
// GHIDRA_PROTO undefined LockBuffer()

void __fastcall CString::LockBuffer(CString *param_1)

{
  char *pcVar1;
  
  GetBuffer(param_1,0);
  pcVar1 = param_1->m_pchData;
  pcVar1[-0xffffffff0000000c] = -1;
  pcVar1[-0xffffffff0000000b] = -1;
  pcVar1[-0xffffffff0000000a] = -1;
  pcVar1[-0xffffffff00000009] = -1;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605E12
// GHIDRA_NAME CString::Find
// GHIDRA_PROTO undefined __thiscall Find(undefined1 param_1)

int __thiscall CString::Find(CString *this,undefined1 param_1)

{
  int iVar1;
  
  iVar1 = __mbschr(this->m_pchData,param_1);
  if (iVar1 == 0) {
    iVar1 = -1;
  }
  else {
    iVar1 = iVar1 - (int)this->m_pchData;
  }
  return iVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605E52
// GHIDRA_NAME CString::MakeUpper
// GHIDRA_PROTO undefined MakeUpper()

void __fastcall CString::MakeUpper(CString *param_1)

{
  CopyBeforeWrite(param_1);
  __mbsupr(param_1->m_pchData);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605E88
// GHIDRA_NAME CString::SetAt
// GHIDRA_PROTO undefined SetAt()

void __thiscall CString::SetAt(CString *param_1,int param_2,char param_3)

{
  CopyBeforeWrite(param_1);
  param_1->m_pchData[param_2] = param_3;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00605EA1
// GHIDRA_NAME CString::OemToCharA
// GHIDRA_PROTO undefined OemToCharA()

void __fastcall CString::OemToCharA(CString *param_1)

{
  CopyBeforeWrite(param_1);
  CharToOemA(param_1->m_pchData,param_1->m_pchData);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0060C7FB
// GHIDRA_NAME CString::'vector_deleting_destructor'
// GHIDRA_PROTO undefined 'vector_deleting_destructor'()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Library Function - Single Match
// GHIDRA_COMMENT  public: void * __thiscall CString::`vector deleting destructor'(unsigned int)
// GHIDRA_COMMENT
// GHIDRA_COMMENT Library: nafxcw retail msvc500:static
// GHIDRA_COMMENT_END

/* Library Function - Single Match
    public: void * __thiscall CString::`vector deleting destructor'(unsigned int)
   
   Library: nafxcw retail msvc500:static */

CString * __thiscall CString::_vector_deleting_destructor_(CString *param_1,byte param_2)

{
  CString *pCVar1;
  
  if ((param_2 & 2) == 0) {
    ~CString(param_1);
    pCVar1 = param_1;
    if ((param_2 & 1) == 0) {
      return param_1;
    }
  }
  else {
    ___M_YGXPAXIHP6EX0_Z_Z(param_1,4,param_1[-1].m_pchData,~CString);
    pCVar1 = param_1 + -1;
  }
  operator_delete(pCVar1);
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0060CE85
// GHIDRA_NAME CString::LoadStringA
// GHIDRA_PROTO undefined LoadStringA()

bool CString::LoadStringA(undefined4 param_1)

{
  int iVar1;
  int iVar2;
  int iVar3;
  char local_108 [256];
  CString *local_8;
  
  iVar1 = AfxLoadString(param_1,local_108,0x100);
  if (0x100U - iVar1 < 3) {
    iVar2 = 0x100;
    do {
      iVar3 = iVar2 + 0x100;
      iVar1 = iVar3;
      iVar2 = GetBuffer(local_8,iVar2 + 0xff);
      iVar1 = AfxLoadString(param_1,iVar2,iVar1);
      iVar2 = iVar3;
    } while (iVar3 - iVar1 < 3);
    ReleaseBuffer(local_8,-1);
  }
  else {
    operator=(local_8,local_108);
  }
  return 0 < iVar1;
}

