// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: CToolBarCtrl.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005E5950
// GHIDRA_NAME CToolBarCtrl::AddBitmap
// GHIDRA_PROTO undefined AddBitmap()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Builds module/context pair and sends control message 0x413 to this->HWND.
// GHIDRA_COMMENT_END

/* Builds module/context pair and sends control message 0x413 to this->HWND. */

void __thiscall CToolBarCtrl::AddBitmap(int param_1,WPARAM param_2,undefined4 param_3)

{
  int iVar1;
  int local_c;
  int local_8;
  
  local_c = param_1;
  local_8 = param_1;
  iVar1 = AfxGetModuleState();
  local_c = *(int *)(iVar1 + 0xc);
  if (local_c != 0) {
    local_8 = param_3;
    SendMessageA(*(HWND *)(param_1 + 0x1c),0x413,param_2,(LPARAM)&local_c);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E59E7
// GHIDRA_NAME CToolBarCtrl::AddString
// GHIDRA_PROTO undefined AddString()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Sends control message 0x41C using module-thread HINSTANCE as wParam when available.
// GHIDRA_COMMENT_END

/* Sends control message 0x41C using module-thread HINSTANCE as wParam when available. */

void __thiscall CToolBarCtrl::AddString(int param_1,LPARAM param_2)

{
  int iVar1;
  
  iVar1 = AfxGetModuleState();
  if (*(WPARAM *)(iVar1 + 0xc) != 0) {
    SendMessageA(*(HWND *)(param_1 + 0x1c),0x41c,*(WPARAM *)(iVar1 + 0xc),param_2);
  }
  return;
}

