// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: T2PictToggleButton.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0040358F
// GHIDRA_NAME T2PictToggleButton::thunk_GetT2PictToggleButtonClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetT2PictToggleButtonClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetT2PictToggleButtonClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetT2PictToggleButtonClassNamePointer */

void * __cdecl T2PictToggleButton::thunk_GetT2PictToggleButtonClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetT2PictToggleButtonClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00403C7E
// GHIDRA_NAME T2PictToggleButton::thunk_DestructT2PictToggleButtonAndMaybeFree
// GHIDRA_PROTO void * __thiscall thunk_DestructT2PictToggleButtonAndMaybeFree(byte freeSelfFlag)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to DestructT2PictToggleButtonAndMaybeFree
// GHIDRA_COMMENT_END

/* Single-JMP thunk to DestructT2PictToggleButtonAndMaybeFree */

void * __thiscall
T2PictToggleButton::thunk_DestructT2PictToggleButtonAndMaybeFree
          (T2PictToggleButton *this,byte freeSelfFlag)

{
  void *pvVar1;
  
  pvVar1 = DestructT2PictToggleButtonAndMaybeFree(this,freeSelfFlag);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004060FA
// GHIDRA_NAME T2PictToggleButton::thunk_IsField3cWithinShortLimit84
// GHIDRA_PROTO void __cdecl thunk_IsField3cWithinShortLimit84(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to IsField3cWithinShortLimit84
// GHIDRA_COMMENT_END

/* Single-JMP thunk to IsField3cWithinShortLimit84 */

void __cdecl T2PictToggleButton::thunk_IsField3cWithinShortLimit84(void)

{
  IsField3cWithinShortLimit84();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00408E59
// GHIDRA_NAME T2PictToggleButton::thunk_SyncField0fTowardsField21ByDirectionAndRefresh
// GHIDRA_PROTO void __thiscall thunk_SyncField0fTowardsField21ByDirectionAndRefresh(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to SyncField0fTowardsField21ByDirectionAndRefresh
// GHIDRA_COMMENT_END

/* Single-JMP thunk to SyncField0fTowardsField21ByDirectionAndRefresh */

void __thiscall
T2PictToggleButton::thunk_SyncField0fTowardsField21ByDirectionAndRefresh(T2PictToggleButton *this)

{
  SyncField0fTowardsField21ByDirectionAndRefresh(this);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00584890
// GHIDRA_NAME T2PictToggleButton::CreateT2PictToggleButtonInstance
// GHIDRA_PROTO void * __cdecl CreateT2PictToggleButtonInstance(void)

void * __cdecl T2PictToggleButton::CreateT2PictToggleButtonInstance(void)

{
  TToggleButton *this;
  TToggleButton *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063762a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (TToggleButton *)AllocateWithFallbackHandler(0x90);
  local_4 = 0;
  pTVar1 = (TToggleButton *)0x0;
  if (this != (TToggleButton *)0x0) {
    TToggleButton::ConstructTToggleButtonBaseState(this);
    *(undefined ***)this = &g_vtblT2PictToggleButton;
    pTVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00584910
// GHIDRA_NAME T2PictToggleButton::GetT2PictToggleButtonClassNamePointer
// GHIDRA_PROTO void * __cdecl GetT2PictToggleButtonClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for T2PictToggleButton.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for T2PictToggleButton. */

void * __cdecl T2PictToggleButton::GetT2PictToggleButtonClassNamePointer(void)

{
  return &g_pClassDescT2PictToggleButton;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00584930
// GHIDRA_NAME T2PictToggleButton::ConstructT2PictToggleButtonBaseState
// GHIDRA_PROTO void * __thiscall ConstructT2PictToggleButtonBaseState(void)

void * __thiscall T2PictToggleButton::ConstructT2PictToggleButtonBaseState(T2PictToggleButton *this)

{
  TToggleButton::ConstructTToggleButtonBaseState((TToggleButton *)this);
  *(undefined ***)this = &g_vtblT2PictToggleButton;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00584960
// GHIDRA_NAME T2PictToggleButton::DestructT2PictToggleButtonAndMaybeFree
// GHIDRA_PROTO void * __thiscall DestructT2PictToggleButtonAndMaybeFree(byte freeSelfFlag)

void * __thiscall
T2PictToggleButton::DestructT2PictToggleButtonAndMaybeFree
          (T2PictToggleButton *this,byte freeSelfFlag)

{
  thunk_DestructCityDialogSharedBaseState();
  if ((freeSelfFlag & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005849B0
// GHIDRA_NAME T2PictToggleButton::IsField3cWithinShortLimit84
// GHIDRA_PROTO void __cdecl IsField3cWithinShortLimit84(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns whether field at +0x3C is within short limit at +0x84.
// GHIDRA_COMMENT_END

/* Returns whether field at +0x3C is within short limit at +0x84. */

void __cdecl T2PictToggleButton::IsField3cWithinShortLimit84(void)

{
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005849D0
// GHIDRA_NAME T2PictToggleButton::SyncField0fTowardsField21ByDirectionAndRefresh
// GHIDRA_PROTO void __thiscall SyncField0fTowardsField21ByDirectionAndRefresh(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Adjusts field +0x0F toward short at +0x21 depending on direction flag and refreshes dependent view state.
// GHIDRA_COMMENT_END

/* Adjusts field +0x0F toward short at +0x21 depending on direction flag and refreshes dependent
   view state. */

void __thiscall
T2PictToggleButton::SyncField0fTowardsField21ByDirectionAndRefresh(T2PictToggleButton *this)

{
  short sVar1;
  int iVar2;
  char in_stack_00000004;
  
  sVar1 = *(short *)(this + 0x84);
  if (((in_stack_00000004 == '\0') && (*(int *)(this + 0x3c) < (int)sVar1)) ||
     ((in_stack_00000004 == '\x01' && ((int)sVar1 < *(int *)(this + 0x3c))))) {
    (**(code **)(*(int *)this + 0x1c8))(*(undefined2 *)(this + 0x3c),0);
    *(int *)(this + 0x3c) = (int)sVar1;
  }
  iVar2 = *(int *)this;
  (**(code **)(iVar2 + 0xf8))();
  (**(code **)(iVar2 + 0x114))(0);
  return;
}

