// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TArmsForeignMinister.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00533FF0
// GHIDRA_NAME TArmsForeignMinister::GetTArmsForeignMinisterClassNamePointer
// GHIDRA_PROTO undefined GetTArmsForeignMinisterClassNamePointer()

undefined ** TArmsForeignMinister::GetTArmsForeignMinisterClassNamePointer(void)

{
  return &PTR_s_TArmsForeignMinister_00659b28;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00534010
// GHIDRA_NAME TArmsForeignMinister::ConstructTArmsForeignMinister
// GHIDRA_PROTO undefined ConstructTArmsForeignMinister()

undefined4 * __fastcall TArmsForeignMinister::ConstructTArmsForeignMinister(undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  *(undefined4 *)((int)param_1 + 0x49) = 0x1010101;
  *(undefined2 *)((int)param_1 + 0x4d) = 0x101;
  *(undefined1 *)((int)param_1 + 0x4f) = 1;
  puVar2 = param_1 + 0x14;
  for (iVar1 = 0xb; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = 0;
    puVar2 = puVar2 + 1;
  }
  *(undefined2 *)puVar2 = 0;
  *(undefined1 *)(param_1 + 0x12) = 1;
  *(undefined2 *)(param_1 + 7) = 1;
  *(undefined2 *)((int)param_1 + 0x16) = 0;
  *param_1 = &PTR_LAB_0065a188;
  *(undefined2 *)((int)param_1 + 0x1a) = 4;
  *(undefined2 *)(param_1 + 3) = 0;
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00534080
// GHIDRA_NAME TArmsForeignMinister::DeletingDestructTArmsForeignMinister
// GHIDRA_PROTO undefined DeletingDestructTArmsForeignMinister()

undefined4 __thiscall
TArmsForeignMinister::DeletingDestructTArmsForeignMinister(undefined4 param_1,byte param_2)

{
  DestructTArmsForeignMinister();
  if ((param_2 & 1) != 0) {
    FreeHeapBufferIfNotNull(param_1);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005340B0
// GHIDRA_NAME TArmsForeignMinister::DestructTArmsForeignMinister
// GHIDRA_PROTO undefined DestructTArmsForeignMinister()

void __fastcall TArmsForeignMinister::DestructTArmsForeignMinister(undefined4 *param_1)

{
  *param_1 = &PTR_GetCObjectRuntimeClass_RuntimeObjectBaseState_0066FEC4;
  return;
}

