// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TArrowsControl.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005838B0
// GHIDRA_NAME TArrowsControl::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TArrowsControl::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063752a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x94);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    func_0x00401122();
    *puVar1 = &_vftable_;
    puVar1[0x24] = 0;
    *unaff_FS_OFFSET = local_c;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00583950
// GHIDRA_NAME TArrowsControl::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TArrowsControl::GetRuntimeClass()

{
  return &classTArrowsControl;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00583970
// GHIDRA_NAME TArrowsControl::ConstructTArrowsControlBaseState
// GHIDRA_PROTO undefined __thiscall ConstructTArrowsControlBaseState(void)

TArrowsControl * TArrowsControl::ConstructTArrowsControlBaseState()

{
  func_0x00401122();
  this->vftable = &_vftable_;
  *(undefined4 *)&this->field_0x90 = 0;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005839A0
// GHIDRA_NAME TArrowsControl::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TArrowsControl * TArrowsControl::_scalar_deleting_destructor_(byte param_1)

{
  func_0x0040159b();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005839F0
// GHIDRA_NAME TArrowsControl::DispatchPictureResourceCommand
// GHIDRA_PROTO undefined __thiscall DispatchPictureResourceCommand(int param_1, int param_2)

void TArrowsControl::DispatchPictureResourceCommand(int param_1, int param_2)

{
  TArrowsControlVtbl *pTVar1;
  char cVar2;
  uint uVar3;
  int iVar4;
  int in_stack_00000010;
  
  if (param_1 != 2) {
    uVar3 = func_0x004092d7();
    if (*(int *)&this->field_0x90 + 5U <= uVar3) {
      iVar4 = func_0x004092d7();
      *(int *)&this->field_0x90 = iVar4;
      if (param_1 == 0) {
        *(int *)&this->field_0x90 = iVar4 + 10;
      }
      pTVar1 = this->vftable;
      cVar2 = (*pTVar1->VTableSlot5B)(in_stack_00000010);
      if (cVar2 != '\0') {
        if (*(int *)(in_stack_00000010 + 4) <= this->field38 / 2) {
          (*pTVar1->OrphanTiny_ReturnZero_0048a730)(100);
          return;
        }
        (*pTVar1->OrphanTiny_ReturnZero_0048a730)(0x65,this,0);
      }
    }
  }
  return;
}

