// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TBehavior.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00486F90
// GHIDRA_NAME TBehavior::CreateTBehaviorInstance
// GHIDRA_PROTO undefined __thiscall CreateTBehaviorInstance(void)

void __thiscall TBehavior::CreateTBehaviorInstance(TBehavior *this)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  puStack_8 = &LAB_0062ead8;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this->vftable = (TBehaviorVtbl *)&ApplicationUiRootEmbeddedList::_vftable_;
  puVar1 = *(undefined4 **)&this->field_0x4;
  local_4 = 0;
  for (; puVar1 != (undefined4 *)0x0; puVar1 = (undefined4 *)*puVar1) {
  }
  *(undefined4 *)&this->field_0xc = 0;
  this[1].vftable = (TBehaviorVtbl *)0x0;
  *(undefined4 *)&this->field_0x8 = 0;
  *(undefined4 *)&this->field_0x4 = 0;
  CPlex::FreeDataChain();
  *(undefined4 *)&this[1].field_0x4 = 0;
  this->vftable = (TBehaviorVtbl *)&PTR_GetCObjectRuntimeClass_RuntimeObjectBaseState_0066FEC4;
  *unaff_FS_OFFSET = local_c;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00487180
// GHIDRA_NAME TBehavior::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TBehavior::CreateObject(void)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)operator_new(0x10);
  if (puVar1 != (undefined4 *)0x0) {
    *puVar1 = &_vftable_;
    puVar1[1] = 0x20202020;
    puVar1[2] = 0;
    *(undefined1 *)(puVar1 + 3) = 1;
    return puVar1;
  }
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004871C0
// GHIDRA_NAME TBehavior::GetRuntimeClass
// GHIDRA_PROTO CRuntimeClass * __thiscall GetRuntimeClass(void)

CRuntimeClass * __thiscall TBehavior::GetRuntimeClass(TBehavior *this)

{
  return &classTBehavior;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004871E0
// GHIDRA_NAME TBehavior::ConstructTBehaviorBaseState
// GHIDRA_PROTO undefined __thiscall ConstructTBehaviorBaseState(void)

void __thiscall TBehavior::ConstructTBehaviorBaseState(TBehavior *this)

{
  this->vftable = &_vftable_;
  *(undefined4 *)&this->field_0x4 = 0x20202020;
  *(undefined4 *)&this->field_0x8 = 0;
  this->field_0xc = 1;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00487210
// GHIDRA_NAME TBehavior::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TBehavior * __thiscall TBehavior::_scalar_deleting_destructor_(TBehavior *this,byte param_1)

{
  func_0x00403f94();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00487280
// GHIDRA_NAME TBehavior::OrphanTiny_SetDwordEcxOffset_8_00487280
// GHIDRA_PROTO undefined __thiscall OrphanTiny_SetDwordEcxOffset_8_00487280(undefined4 param_1)

void __thiscall
TBehavior::OrphanTiny_SetDwordEcxOffset_8_00487280(TBehavior *this,undefined4 param_1)

{
  *(undefined4 *)&this->field_0x8 = param_1;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004872A0
// GHIDRA_NAME TBehavior::OrphanLeaf_NoCall_Ins02_004872a0
// GHIDRA_PROTO undefined __thiscall OrphanLeaf_NoCall_Ins02_004872a0(void)

undefined1 __thiscall TBehavior::OrphanLeaf_NoCall_Ins02_004872a0(TBehavior *this)

{
  return this->field_0xc;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004872C0
// GHIDRA_NAME TBehavior::CreateTDialogBehaviorInstance
// GHIDRA_PROTO undefined __thiscall CreateTDialogBehaviorInstance(undefined1 param_1)

void __thiscall TBehavior::CreateTDialogBehaviorInstance(TBehavior *this,undefined1 param_1)

{
  this->field_0xc = param_1;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004872E0
// GHIDRA_NAME TBehavior::OrphanRetStub_004872e0
// GHIDRA_PROTO undefined __thiscall OrphanRetStub_004872e0(void)

void __thiscall TBehavior::OrphanRetStub_004872e0(TBehavior *this)

{
  return;
}

