// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TButton.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0048EB10
// GHIDRA_NAME TButton::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TButton::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0062eec2;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x84);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    func_0x004064e2();
    *(undefined1 *)(puVar1 + 0x19) = 0;
    puVar1[0x18] = 1;
    puVar1[0x1a] = 0;
    puVar1[0x1b] = 0;
    puVar1[0x1c] = 0;
    puVar1[0x1d] = 0;
    puVar1[0x1e] = g_nUiResourceEntryDefaultParam0;
    puVar1[0x1f] = g_nUiResourceEntryDefaultParam1;
    *(ushort *)(puVar1 + 0x20) = g_wUiResourceEntryDefaultParam2;
    local_4 = CONCAT31(local_4._1_3_,1);
    *puVar1 = &_vftable_;
    func_0x004057a4(g_szMcAppUiHeaderPath_006943CC,0x5a6);
    *puVar1 = &_vftable_;
    *unaff_FS_OFFSET = local_c;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0048EC00
// GHIDRA_NAME TButton::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TButton * TButton::_scalar_deleting_destructor_(byte param_1)

{
  func_0x00404066();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0048ECC0
// GHIDRA_NAME TButton::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TButton::GetRuntimeClass()

{
  return &classTButton;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0048EDD0
// GHIDRA_NAME TButton::DestructTButtonAndMaybeFree
// GHIDRA_PROTO undefined __thiscall DestructTButtonAndMaybeFree(byte param_1)

TButton * TButton::DestructTButtonAndMaybeFree(byte param_1)

{
  func_0x00401b36();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00492DE0
// GHIDRA_NAME TButton::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TButton * TButton::_scalar_deleting_destructor_(byte param_1)

{
  func_0x00409467();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

