// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TCheater.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004023BA
// GHIDRA_NAME TCheater::thunk_GetTCheaterClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetTCheaterClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTCheaterClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTCheaterClassNamePointer */

void * __cdecl TCheater::thunk_GetTCheaterClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetTCheaterClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00404985
// GHIDRA_NAME TCheater::thunk_InitializeCheaterDialogControlsAndBindings
// GHIDRA_PROTO void * __thiscall thunk_InitializeCheaterDialogControlsAndBindings(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Thunk forwarding to InitializeCheaterDialogControlsAndBindings.
// GHIDRA_COMMENT_END

/* Thunk forwarding to InitializeCheaterDialogControlsAndBindings. */

void * __thiscall TCheater::thunk_InitializeCheaterDialogControlsAndBindings(TCheater *this)

{
  TControl *pTVar1;
  void *extraout_EAX;
  undefined4 *unaff_FS_OFFSET;
  TControl *pTStack00000004;
  undefined2 in_stack_00000008;
  undefined4 uStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  uStack_4 = 0xffffffff;
  puStack_8 = &LAB_00630d54;
  uStack_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &uStack_c;
  thunk_InitializeUiResourceEntryFrameAndParent();
  pTStack00000004 = (TControl *)AllocateWithFallbackHandler(0x94);
  uStack_4 = 0;
  if (pTStack00000004 != (TControl *)0x0) {
    TStaticText::thunk_ConstructUiTextResourceEntryBase((TStaticText *)pTStack00000004);
  }
  uStack_4 = 0xffffffff;
  thunk_InitializeTextEntryBaseAndOptionalStringResource();
  pTVar1 = (TControl *)AllocateWithFallbackHandler(0x84);
  uStack_4 = 1;
  pTStack00000004 = pTVar1;
  if (pTVar1 == (TControl *)0x0) {
    pTVar1 = (TControl *)0x0;
  }
  else {
    TControl::thunk_ConstructUiCommandTagResourceEntryBase(pTVar1);
    uStack_4 = CONCAT31(uStack_4._1_3_,2);
    *(undefined ***)pTVar1 = &g_vtblTButton;
    thunk_TemporarilyClearAndRestoreUiInvalidationFlag();
    *(undefined ***)pTVar1 = &g_vtblTCtlMgr;
  }
  uStack_4 = 0xffffffff;
  ConstructSharedStringFromCStrOrResourceId(&g_TCheater_Base_Value_00695A18);
  uStack_4 = 3;
  if (g_TCheater_Base_Value_006A2480 == 0) {
    thunk_TemporarilyClearAndRestoreUiInvalidationFlag();
  }
  uStack_4 = 0xffffffff;
  ReleaseSharedStringRefIfNotEmpty();
  *(undefined4 *)(pTVar1 + 0x60) = 0x22;
  *(undefined2 *)&this->dwField_60 = in_stack_00000008;
  *unaff_FS_OFFSET = uStack_c;
  return extraout_EAX;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B1480
// GHIDRA_NAME TCheater::GetTCheaterClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTCheaterClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for TCheater.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for TCheater. */

void * __cdecl TCheater::GetTCheaterClassNamePointer(void)

{
  return &g_pClassDescTCheater;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B14A0
// GHIDRA_NAME TCheater::ConstructTCheaterBaseState
// GHIDRA_PROTO void * __thiscall ConstructTCheaterBaseState(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Builds cheater dialog UI controls/text resources and binds them into the dialog frame.
// GHIDRA_COMMENT_END

/* Builds cheater dialog UI controls/text resources and binds them into the dialog frame. */

void * __thiscall TCheater::ConstructTCheaterBaseState(TCheater *this)

{
  TControl *pTVar1;
  void *extraout_EAX;
  undefined4 *unaff_FS_OFFSET;
  TControl *pTStack00000004;
  undefined2 in_stack_00000008;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00630d54;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  thunk_InitializeUiResourceEntryFrameAndParent();
  pTStack00000004 = (TControl *)AllocateWithFallbackHandler(0x94);
  local_4 = 0;
  if (pTStack00000004 != (TControl *)0x0) {
    TStaticText::thunk_ConstructUiTextResourceEntryBase((TStaticText *)pTStack00000004);
  }
  local_4 = 0xffffffff;
  thunk_InitializeTextEntryBaseAndOptionalStringResource();
  pTVar1 = (TControl *)AllocateWithFallbackHandler(0x84);
  local_4 = 1;
  pTStack00000004 = pTVar1;
  if (pTVar1 == (TControl *)0x0) {
    pTVar1 = (TControl *)0x0;
  }
  else {
    TControl::thunk_ConstructUiCommandTagResourceEntryBase(pTVar1);
    local_4 = CONCAT31(local_4._1_3_,2);
    *(undefined ***)pTVar1 = &g_vtblTButton;
    thunk_TemporarilyClearAndRestoreUiInvalidationFlag();
    *(undefined ***)pTVar1 = &g_vtblTCtlMgr;
  }
  local_4 = 0xffffffff;
  ConstructSharedStringFromCStrOrResourceId(&g_TCheater_Base_Value_00695A18);
  local_4 = 3;
  if (g_TCheater_Base_Value_006A2480 == 0) {
    thunk_TemporarilyClearAndRestoreUiInvalidationFlag();
  }
  local_4 = 0xffffffff;
  ReleaseSharedStringRefIfNotEmpty();
  *(undefined4 *)(pTVar1 + 0x60) = 0x22;
  *(undefined2 *)&this->dwField_60 = in_stack_00000008;
  *unaff_FS_OFFSET = local_c;
  return extraout_EAX;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B1670
// GHIDRA_NAME TCheater::DestructTCheaterAndMaybeFree
// GHIDRA_PROTO void __thiscall DestructTCheaterAndMaybeFree(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Computes centered dialog bounds from content dimensions and applies modal positioning.
// GHIDRA_COMMENT_END

/* Computes centered dialog bounds from content dimensions and applies modal positioning. */

void __thiscall TCheater::DestructTCheaterAndMaybeFree(TCheater *this)

{
  int iVar1;
  int *piVar2;
  int *unaff_retaddr;
  int iStack_10;
  int iStack_c;
  int iStack_8;
  
  piVar2 = (int *)(**(code **)((int)this->pVtable + 0x58))();
  iVar1 = *piVar2;
  (**(code **)(iVar1 + 300))(&iStack_10);
  iStack_10 = 0xf0 - unaff_retaddr[1] / 2;
  iStack_8 = iStack_10 + unaff_retaddr[1];
  iStack_c = (0x140 - *unaff_retaddr / 2) + *unaff_retaddr;
  (**(code **)(iVar1 + 0x168))(&stack0xffffffec,1);
  return;
}

