// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TClickZone.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00401762
// GHIDRA_NAME TClickZone::thunk_GetTClickZoneClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetTClickZoneClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTClickZoneClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTClickZoneClassNamePointer */

void * __cdecl TClickZone::thunk_GetTClickZoneClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetTClickZoneClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004038FF
// GHIDRA_NAME TClickZone::thunk_ConstructUiCommandTagResourceEntry
// GHIDRA_PROTO void __thiscall thunk_ConstructUiCommandTagResourceEntry(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to ConstructUiCommandTagResourceEntry
// GHIDRA_COMMENT_END

/* Single-JMP thunk to ConstructUiCommandTagResourceEntry */

void __thiscall TClickZone::thunk_ConstructUiCommandTagResourceEntry(TClickZone *this)

{
  TControl::thunk_ConstructUiCommandTagResourceEntryBase((TControl *)this);
  *(undefined ***)this = &g_vtblTClickZone;
  *(undefined2 *)(this + 0x84) = 7000;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00408198
// GHIDRA_NAME TClickZone::thunk_DestructTClickZoneAndMaybeFree
// GHIDRA_PROTO void * __thiscall thunk_DestructTClickZoneAndMaybeFree(byte freeSelfFlag)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to DestructTClickZoneAndMaybeFree
// GHIDRA_COMMENT_END

/* Single-JMP thunk to DestructTClickZoneAndMaybeFree */

void * __thiscall
TClickZone::thunk_DestructTClickZoneAndMaybeFree(TClickZone *this,byte freeSelfFlag)

{
  void *pvVar1;
  
  pvVar1 = DestructTClickZoneAndMaybeFree(this,freeSelfFlag);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00572350
// GHIDRA_NAME TClickZone::CreateTClickZoneInstance
// GHIDRA_PROTO void * __cdecl CreateTClickZoneInstance(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [ClassQuad] create inferred for TClickZone; alloc factory pattern.
// GHIDRA_COMMENT_END

/* [ClassQuad] create inferred for TClickZone; alloc factory pattern. */

void * __cdecl TClickZone::CreateTClickZoneInstance(void)

{
  TControl *this;
  TControl *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_006364ca;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (TControl *)AllocateWithFallbackHandler(0x88);
  local_4 = 0;
  pTVar1 = (TControl *)0x0;
  if (this != (TControl *)0x0) {
    TControl::thunk_ConstructUiCommandTagResourceEntryBase(this);
    *(undefined ***)this = &g_vtblTClickZone;
    *(undefined2 *)(this + 0x84) = 7000;
    pTVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005723F0
// GHIDRA_NAME TClickZone::GetTClickZoneClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTClickZoneClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for TClickZone.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for TClickZone. */

void * __cdecl TClickZone::GetTClickZoneClassNamePointer(void)

{
  return &g_pClassDescTClickZone;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00572410
// GHIDRA_NAME TClickZone::ConstructUiCommandTagResourceEntry
// GHIDRA_PROTO void __thiscall ConstructUiCommandTagResourceEntry(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Derived command-tag UI entry over ConstructUiCommandTagResourceEntryBase; used by list/info/view/count style command-tag paths and sets +0x84 word to 7000.
// GHIDRA_COMMENT_END

/* Derived command-tag UI entry over ConstructUiCommandTagResourceEntryBase; used by
   list/info/view/count style command-tag paths and sets +0x84 word to 7000. */

void __thiscall TClickZone::ConstructUiCommandTagResourceEntry(TClickZone *this)

{
  TControl::thunk_ConstructUiCommandTagResourceEntryBase((TControl *)this);
  *(undefined ***)this = &g_vtblTClickZone;
  *(undefined2 *)(this + 0x84) = 7000;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00572440
// GHIDRA_NAME TClickZone::DestructTClickZoneAndMaybeFree
// GHIDRA_PROTO void * __thiscall DestructTClickZoneAndMaybeFree(byte freeSelfFlag)

void * __thiscall TClickZone::DestructTClickZoneAndMaybeFree(TClickZone *this,byte freeSelfFlag)

{
  thunk_DestructEngineerDialogBaseState();
  if ((freeSelfFlag & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

