// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TCzechBox.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0043D6F0
// GHIDRA_NAME TCzechBox::WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0
// GHIDRA_PROTO undefined WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0()

undefined4 * __fastcall
TCzechBox::WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0(undefined4 *param_1)

{
  ConstructTCzechBoxBaseState();
  param_1[0x26] = 0;
  *param_1 = &PTR_LAB_00641df0;
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00571B60
// GHIDRA_NAME TCzechBox::CreateTCzechBoxInstance
// GHIDRA_PROTO undefined CreateTCzechBoxInstance()

undefined4 * TCzechBox::CreateTCzechBoxInstance(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063646a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)AllocateWithFallbackHandler(0x98);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    thunk_TPictureButton::TPictureButton();
    *(undefined2 *)((int)puVar1 + 0x92) = 7000;
    *(undefined1 *)(puVar1 + 0x25) = 0;
    *puVar1 = &PTR_LAB_0065fae0;
    *unaff_FS_OFFSET = local_c;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00571C00
// GHIDRA_NAME TCzechBox::GetTCzechBoxClassNamePointer
// GHIDRA_PROTO undefined GetTCzechBoxClassNamePointer()

undefined ** TCzechBox::GetTCzechBoxClassNamePointer(void)

{
  return &PTR_s_TCzechBox_0065e610;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00571C20
// GHIDRA_NAME TCzechBox::ConstructTCzechBoxBaseState
// GHIDRA_PROTO undefined ConstructTCzechBoxBaseState()

undefined4 * __fastcall TCzechBox::ConstructTCzechBoxBaseState(undefined4 *param_1)

{
  thunk_TPictureButton::TPictureButton();
  *(undefined2 *)((int)param_1 + 0x92) = 7000;
  *(undefined1 *)(param_1 + 0x25) = 0;
  *param_1 = &PTR_LAB_0065fae0;
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00571C60
// GHIDRA_NAME TCzechBox::DestructTCzechBoxAndMaybeFree
// GHIDRA_PROTO undefined DestructTCzechBoxAndMaybeFree()

undefined4 __thiscall TCzechBox::DestructTCzechBoxAndMaybeFree(undefined4 param_1,byte param_2)

{
  thunk_DestructCityDialogSharedBaseState();
  if ((param_2 & 1) != 0) {
    FreeHeapBufferIfNotNull(param_1);
  }
  return param_1;
}

