// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TDiplomatForeignMinister.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005326E0
// GHIDRA_NAME TDiplomatForeignMinister::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TDiplomatForeignMinister::CreateObject(void)

{
  undefined4 *puVar1;
  int iVar2;
  undefined4 *puVar3;
  
  puVar1 = (undefined4 *)operator_new(0x80);
  if (puVar1 != (undefined4 *)0x0) {
    *(undefined4 *)((int)puVar1 + 0x49) = 0x1010101;
    *(undefined2 *)((int)puVar1 + 0x4d) = 0x101;
    *(undefined1 *)((int)puVar1 + 0x4f) = 1;
    puVar3 = puVar1 + 0x14;
    for (iVar2 = 0xb; iVar2 != 0; iVar2 = iVar2 + -1) {
      *puVar3 = 0;
      puVar3 = puVar3 + 1;
    }
    *(undefined2 *)puVar3 = 0;
    *(undefined2 *)((int)puVar1 + 0x16) = 0;
    *(undefined1 *)(puVar1 + 0x12) = 0;
    *(undefined2 *)((int)puVar1 + 0x1a) = 5;
    *(undefined2 *)(puVar1 + 7) = 2;
    *puVar1 = &_vftable_;
    *(undefined2 *)(puVar1 + 3) = 3;
    return puVar1;
  }
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00532760
// GHIDRA_NAME TDiplomatForeignMinister::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TDiplomatForeignMinister::GetRuntimeClass()

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00532780
// GHIDRA_NAME TDiplomatForeignMinister::ConstructTDiplomatForeignMinister
// GHIDRA_PROTO undefined __thiscall ConstructTDiplomatForeignMinister(void)

TDiplomatForeignMinister * TDiplomatForeignMinister::ConstructTDiplomatForeignMinister()

{
  int iVar1;
  undefined4 *puVar2;
  
  *(undefined4 *)&this->field_0x49 = 0x1010101;
  *(undefined2 *)&this->field_0x4d = 0x101;
  this->field_0x4f = 1;
  puVar2 = (undefined4 *)&this->field_0x50;
  for (iVar1 = 0xb; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = 0;
    puVar2 = puVar2 + 1;
  }
  *(undefined2 *)puVar2 = 0;
  *(undefined2 *)&this->field_0x1a = 5;
  *(undefined2 *)&this->field_0x16 = 0;
  this->field_0x48 = 0;
  *(undefined2 *)&this->field_0x1c = 2;
  this->vftable = &_vftable_;
  *(undefined2 *)&this->field_0xc = 3;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005327F0
// GHIDRA_NAME TDiplomatForeignMinister::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TDiplomatForeignMinister * TDiplomatForeignMinister::_scalar_deleting_destructor_(byte param_1)

{
  func_0x00401f37();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00532820
// GHIDRA_NAME TDiplomatForeignMinister::DestructTDiplomatForeignMinister
// GHIDRA_PROTO undefined __thiscall DestructTDiplomatForeignMinister(void)

void TDiplomatForeignMinister::DestructTDiplomatForeignMinister()

{
  this->vftable =
       (TDiplomatForeignMinisterVtbl *)&PTR_GetCObjectRuntimeClass_RuntimeObjectBaseState_0066FEC4;
  return;
}

