// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TGameScorePicture.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0045AFB0
// GHIDRA_NAME TGameScorePicture::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TGameScorePicture * TGameScorePicture::_scalar_deleting_destructor_(byte param_1)

{
  func_0x0040416f();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0057B000
// GHIDRA_NAME TGameScorePicture::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TGameScorePicture::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00636c1a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x94);
  local_4 = 0;
  puVar2 = (undefined4 *)0x0;
  if (puVar1 != (undefined4 *)0x0) {
    func_0x00403328();
    *puVar1 = &_vftable_;
    puVar2 = puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return puVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0057B080
// GHIDRA_NAME TGameScorePicture::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TGameScorePicture::GetRuntimeClass()

{
  return &classTGameScorePicture;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0057B0A0
// GHIDRA_NAME TGameScorePicture::NoOpUiLifecycleHook
// GHIDRA_PROTO undefined __thiscall NoOpUiLifecycleHook(void)

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void TGameScorePicture::NoOpUiLifecycleHook()

{
  CString CVar1;
  short sVar2;
  int *piVar3;
  CString *src_ref;
  int iVar4;
  int *unaff_FS_OFFSET;
  int in_stack_00000004;
  int iVar5;
  CString CStack_7c;
  undefined1 *puStack_78;
  TSimMgr *pTStack_74;
  CString *pCStack_70;
  int iVar6;
  CString CStack_5c;
  undefined1 *puStack_58;
  CString CStack_54;
  CString CStack_50;
  int iStack_4c;
  CString local_38;
  CString local_34;
  CString local_30;
  char local_2c [8];
  char acStack_24 [8];
  CString local_1c;
  undefined1 local_18 [2];
  undefined1 uStack_16;
  undefined1 uStack_15;
  undefined1 uStack_14;
  undefined1 uStack_13;
  undefined1 local_10 [4];
  int iStack_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00636c58;
  iStack_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = (int)&iStack_c;
  iStack_4c = in_stack_00000004;
  CStack_50.m_pchData = (char *)0x57b0cc;
  local_1c.m_pchData = (char *)this;
  func_0x00406ba9();
  CStack_50.m_pchData = (char *)0x57b0d5;
  CString::CString(&local_34);
  iVar4 = 0;
  puStack_8 = (undefined1 *)0x0;
  CStack_50.m_pchData = (char *)0x57b0e4;
  CString::CString(&local_38);
  puStack_8._0_1_ = 1;
  CStack_50.m_pchData = (char *)0x57b0f2;
  CString::CString((CString *)&stack0x00000000);
  puStack_8 = (undefined1 *)CONCAT31(puStack_8._1_3_,2);
  uStack_16 = 0;
  uStack_15 = 0;
  uStack_14 = 0;
  uStack_13 = 0;
  CStack_50.m_pchData = (char *)0x57b12a;
  func_0x004092af();
  CStack_50.m_pchData = (char *)0xb;
  CStack_54.m_pchData = (char *)0x57b137;
  func_0x00401483();
  CStack_54.m_pchData = "hh+";
  func_0x00409138();
  CStack_54.m_pchData = (char *)0x2b68;
  puStack_58 = (undefined1 *)0xe;
  CStack_5c.m_pchData = (char *)0x0;
  func_0x00406afa();
  CStack_54.m_pchData = &stack0xffffffc0;
  puStack_58 = (undefined1 *)0x2b6a;
  CStack_5c.m_pchData = (char *)0x57b166;
  func_0x004093cc();
  CStack_54.m_pchData = (char *)0x57b174;
  func_0x00403b16();
  CStack_54.m_pchData = (char *)0x57b183;
  func_0x00404502();
  local_34.m_pchData = (char *)this->vftable->OrphanLeaf_NoCall_Ins07_004d8920_25;
  do {
    CStack_54.m_pchData = (char *)(iVar4 + 0x73637261);
    puStack_58 = (undefined1 *)0x57b19c;
    piVar3 = (int *)(*(code *)local_34.m_pchData)();
    iVar5 = *piVar3;
    puStack_58 = (undefined1 *)0x57b1a5;
    (**(code **)(iVar5 + 0xc))();
    if (iVar4 == 0xb) {
      puStack_58 = (undefined1 *)0x2b68;
      CStack_5c.m_pchData = (char *)0x12;
      func_0x00406afa();
    }
    CStack_5c.m_pchData = acStack_24;
    puStack_58 = (undefined1 *)0x1;
    (**(code **)(iVar5 + 0x1b4))();
    piVar3[0x25] = iStack_4c;
    (*g_pSimMgr->vftable[0x10].slot_0x04)();
    if (iVar4 == 10) {
      pCStack_70 = (CString *)0x57b208;
      CString::operator=(&CStack_50,&local_1c);
      pCStack_70 = (CString *)(*(int *)&g_pSimMgr->field_0x40 + 0xd);
      pTStack_74 = (TSimMgr *)0x2737;
      puStack_78 = (undefined1 *)0x57b227;
      (*g_pSimMgr->vftable[0x10].slot_0x04)();
      CStack_7c.m_pchData = CStack_5c.m_pchData;
      puStack_78 = local_10;
      func_0x0040988b(g_pSimMgr);
    }
    pCStack_70 = &local_1c;
    iVar6 = 1;
    pTStack_74 = (TSimMgr *)0x57b254;
    (**(code **)(iVar5 + 0x1c8))();
    pTStack_74 = (TSimMgr *)(iVar4 + 0x6e756d61);
    puStack_78 = (undefined1 *)0x57b261;
    piVar3 = (int *)(*(code *)CStack_54.m_pchData)();
    iVar5 = *piVar3;
    puStack_78 = (undefined1 *)0x57b26a;
    (**(code **)(iVar5 + 0xc))();
    CStack_7c.m_pchData = &stack0xffffffbc;
    puStack_78 = (undefined1 *)0x1;
    (**(code **)(iVar5 + 0x1b4))();
    piVar3[0x25] = iVar6;
    if (iVar4 == 10) {
      sVar2 = func_0x00403b16();
      puStack_58 = *(undefined1 **)&g_apNationStates[sVar2]->field_0x958;
      if ((int)puStack_58 % 10 < 1) {
        CString__Format(&local_30,&g_szDecimalFormat);
      }
      else {
        puStack_58 = (undefined1 *)((float)(int)puStack_58 * _DAT_00661ab8);
        func_0x004011a4(puStack_58);
      }
      src_ref = (CString *)AssignSharedStringConcatCStrAndRef(&CStack_54,&DAT_00698b0c);
      local_38.m_pchData._0_1_ = 3;
      CString::CString(&CStack_5c,src_ref);
      local_38.m_pchData._0_1_ = 4;
      CString::operator=(&local_30,&CStack_5c);
      local_38.m_pchData._0_1_ = 3;
      CString::~CString(&CStack_5c);
      local_38.m_pchData._0_1_ = 2;
      CString::~CString(&CStack_54);
    }
    else {
      func_0x00403b16();
      CString__Format(&local_30,&g_szDecimalFormat);
    }
    (**(code **)(iVar5 + 0x1c8))(&local_30);
    CVar1.m_pchData = local_34.m_pchData;
    iVar4 = iVar4 + 1;
  } while (iVar4 < 0xc);
  CStack_54.m_pchData = (char *)0x76696374;
  puStack_58 = (undefined1 *)0x57b3a9;
  piVar3 = (int *)(*(code *)local_34.m_pchData)();
  iVar4 = *piVar3;
  puStack_58 = (undefined1 *)0x57b3b2;
  (**(code **)(iVar4 + 0xc))();
  puStack_58 = &stack0xffffffc4;
  CStack_5c.m_pchData = (char *)0x0;
  (*g_pSimMgr->vftable[0x10].slot_0x04)();
  func_0x00403b16();
  func_0x00405245();
  pCStack_70 = (CString *)local_18;
  pTStack_74 = g_pSimMgr;
  puStack_78 = (undefined1 *)0x57b405;
  func_0x0040988b();
  pCStack_70 = (CString *)0x57b417;
  (**(code **)(iVar4 + 0x1c8))();
  pCStack_70 = (CString *)0x1;
  pTStack_74 = (TSimMgr *)0x2b68;
  puStack_78 = (undefined1 *)0x18;
  CStack_7c.m_pchData = (char *)0x0;
  InitializeUiTextStyleDescriptor();
  pTStack_74 = (TSimMgr *)&stack0xffffffc4;
  pCStack_70 = (CString *)0x1;
  puStack_78 = (undefined1 *)0x57b43e;
  (**(code **)(iVar4 + 0x1b4))();
  puStack_78 = (undefined1 *)0x70746672;
  piVar3[0x25] = (int)&iStack_4c;
  CStack_7c.m_pchData = (char *)0x57b451;
  piVar3 = (int *)(*(code *)CVar1.m_pchData)();
  iVar4 = *piVar3;
  CStack_7c.m_pchData = (char *)0x57b45a;
  (**(code **)(iVar4 + 0xc))();
  CStack_7c.m_pchData = local_2c;
  iVar5 = 0x2761;
  (*g_pSimMgr->vftable[0x10].slot_0x04)();
  (**(code **)(iVar4 + 0x1c8))(&local_38,1);
  func_0x00406afa(&CStack_5c,0,0xe,0x2b68);
  (**(code **)(iVar4 + 0x1b4))(&CStack_5c,1);
  CStack_50.m_pchData._0_1_ = 1;
  piVar3[0x25] = iVar5;
  CString::~CString((CString *)&stack0xffffffb8);
  CStack_50.m_pchData = (char *)((uint)CStack_50.m_pchData._1_3_ << 8);
  CString::~CString((CString *)&stack0xffffff80);
  CStack_50.m_pchData = (char *)0xffffffff;
  CString::~CString(&CStack_7c);
  *unaff_FS_OFFSET = (int)puStack_58;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0057B620
// GHIDRA_NAME TGameScorePicture::HandleEvent
// GHIDRA_PROTO undefined __thiscall HandleEvent(int param_1, int param_2)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Command callback helper: runs completion handler and, for command-id 10 with tag 'done', reinitializes game flow and posts turn-event code 0x5E0.
// GHIDRA_COMMENT_END

/* Command callback helper: runs completion handler and, for command-id 10 with tag 'done',
   reinitializes game flow and posts turn-event code 0x5E0. */

void TGameScorePicture::HandleEvent(int param_1, int param_2)

{
  func_0x00404566(param_1,param_2);
  if ((param_1 == 10) && (*(int *)(param_2 + 0x1c) == 0x646f6e65)) {
    func_0x00403553(0x5e0);
  }
  return;
}

