// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TGameWindow.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004FFB30
// GHIDRA_NAME TGameWindow::CreateTGameWindowInstance
// GHIDRA_PROTO undefined CreateTGameWindowInstance()

TControl * TGameWindow::CreateTGameWindowInstance(void)

{
  TControl *this;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;

  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063331a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (TControl *)__2_YAPAXI_Z(0xb0);
  local_4 = 0;
  if (this != (TControl *)0x0) {
    TControl::ConstructUiWindowResourceEntryBase(this);
    this->vftable = (TControlVtbl *)&TGameWindowVtbl_00656a98;
    this[1].field_0x1c = 0;
    *(undefined2 *)&this[1].field_0x1e = 0x14;
    *(undefined4 *)&this[1].field_0x20 = 0;
    *(undefined4 *)&this[1].field_0x24 = 0;
    *(undefined4 *)&this[1].field_0x28 = 0;
    *unaff_FS_OFFSET = local_c;
    return this;
  }
  *unaff_FS_OFFSET = local_c;
  return (TControl *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFBF0
// GHIDRA_NAME TGameWindow::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall TSoundPlayer::GetTEventHandlerClassNamePointer(void)

CRuntimeClass * TGameWindow::GetTEventHandlerClassNamePointer()

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFC60
// GHIDRA_NAME TGameWindow::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Destructor wrapper for viewport-adaptive turn-event window entry.
// GHIDRA_COMMENT_END

/* Destructor wrapper for viewport-adaptive turn-event window entry. */

TGameWindow * TGameWindow::_scalar_deleting_destructor_(byte param_1)

{
  TView::DestructTWindowViewAndUnlinkGlobalLists((TView *)this);
  if ((param_1 & 1) != 0) {
    __3_YAXPAX_Z(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFCB0
// GHIDRA_NAME TGameWindow::OrphanCallChain_C11_I88_004874b0
// GHIDRA_PROTO undefined __thiscall TEditText::OrphanCallChain_C11_I88_004874b0(void)

void TGameWindow::OrphanCallChain_C11_I88_004874b0()

{
  TGameWindowVtbl *pTVar1;
  char cVar2;

  pTVar1 = this->vftable;
  cVar2 = (*pTVar1->ReleaseRuntimeSelectionOwnerAndDestroyObject_3b)();
  if (cVar2 == '\0') {
    (*pTVar1->UpdateTurnOrderNavigationWindowLayout)();
  }
  TWindow::OrphanCallChain_C11_I88_004874b0((TWindow *)this);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFD10
// GHIDRA_NAME TGameWindow::SetForeignMinisterReadyFlag14
// GHIDRA_PROTO undefined __thiscall TCommand::SetForeignMinisterReadyFlag14(undefined4 * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4)

void __thiscall
TGameWindow::SetForeignMinisterReadyFlag14
          (TGameWindow *this,undefined4 *param_1,undefined4 param_2,undefined4 param_3,
          undefined4 param_4)

{
  TView::SetForeignMinisterReadyFlag14((TView *)this,param_1,param_2,param_3,param_4);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFD40
// GHIDRA_NAME TGameWindow::InvalidateWindowRectFromHandleField1C
// GHIDRA_PROTO undefined __thiscall InvalidateWindowRectFromHandleField1C(undefined4 * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4)

void __thiscall
TGameWindow::InvalidateWindowRectFromHandleField1C
          (TGameWindow *this,undefined4 *param_1,undefined4 param_2,undefined4 param_3,
          undefined4 param_4)

{
  TControl::DispatchUiMouseEventToChildrenOrSelf((TControl *)this,param_1,param_2,param_3,param_4);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004FFD70
// GHIDRA_NAME TGameWindow::OrphanTiny_ReturnZero_0048a730
// GHIDRA_PROTO undefined __thiscall TDropShadowText::OrphanTiny_ReturnZero_0048a730(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Handles commands for the viewport-adaptive turn-order navigation window. Maps command codes 0x31..0x35 to turn-state requests (0x69,0x6A,0x67,0x68,0x6D) while guarding against already-active target event states (0x7DE,0x7DB,0x7D9/0x7DA,0x7D8,0x8FC).
// GHIDRA_COMMENT_END

/* Handles commands for the viewport-adaptive turn-order navigation window. Maps command codes
   0x31..0x35 to turn-state requests (0x69,0x6A,0x67,0x68,0x6D) while guarding against
   already-active target event states (0x7DE,0x7DB,0x7D9/0x7DA,0x7D8,0x8FC). */

void TGameWindow::OrphanTiny_ReturnZero_0048a730()

{
  short sVar1;
  undefined uVar2;
  undefined3 extraout_var;
  int iVar4;
  undefined4 uVar5;
  int unaff_retaddr;
  int *piVar3;

  uVar2 = (*this->vftable->OrphanLeaf_NoCall_Ins07_004d8920)(0x6d61696e);
  piVar3 = (int *)CONCAT31(extraout_var,uVar2);
  if (piVar3 == (int *)0x0) {
    return;
  }
  if (*(short *)(unaff_retaddr + 0x20) == 0x29a) {
    return;
  }
  iVar4 = InvokeAfxThreadAndCallSecondaryRefresh();
  if (iVar4 != 0) {
    return;
  }
  *(undefined2 *)(unaff_retaddr + 0x20) = 0x29a;
  if ((((*(short *)(unaff_retaddr + 0x1c) == 0x68) || (*(short *)(unaff_retaddr + 0x1c) == 0x48)) &&
      (iVar4 = (**(code **)(*piVar3 + 0x94))(0x71756572), iVar4 != 0)) && (DAT_006a21b8 != 0)) {
    (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
    if (*(short *)&g_pUiRuntimeContext->field_0x4 == 0x7dd) {
      DispatchUiRuntimeMessage101AAndRefreshActiveView();
      return;
    }
    SelectAndActivatePendingEventForCurrentView();
    return;
  }
  sVar1 = *(short *)(unaff_retaddr + 0x1c);
  if (((sVar1 == 3) || (sVar1 == 0xd)) || ((sVar1 == 0x1b || (sVar1 == 0x20)))) {
    if ((*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7dd) &&
       (iVar4 = (**(code **)(*piVar3 + 0x94))(0x656e6420), iVar4 != 0)) {
      (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
      if (*(int *)&g_pLocalizationTable->field_0x8 != 0x11) {
        (*g_pLocalizationTable->vftable[8].slot_0x04)();
        return;
      }
      uVar5 = UiRuntimeContext::GetActiveNationId();
      uVar5 = ConsumeFirstPendingAbilityUnlock(uVar5);
      if ((short)uVar5 != -1) {
        (**(code **)(g_pUiRuntimeContext->vftable + 0x88))(uVar5);
        return;
      }
      (*g_pLocalizationTable->vftable[8].slot_0x04)();
      return;
    }
    if (*(short *)&g_pUiRuntimeContext->field_0xf8 != 0) {
      if (*(int *)&g_pUiRuntimeContext->field_0xf4 == 0) {
        return;
      }
      SendMessage808IfSelectionStateActive();
      return;
    }
switchD_004ffe93_default:
    (**(code **)(*piVar3 + 0x48))(unaff_retaddr);
  }
  else {
    if ((g_pLocalizationTable == (TSimMgr *)0x0) ||
       ((((iVar4 = *(int *)&g_pLocalizationTable->field_0x8, iVar4 != 0x69 && (iVar4 != 0x68)) &&
         (iVar4 != 0x67)) &&
        (((iVar4 != 0x6a && (iVar4 != 0x6d)) && (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7dd)
         ))))) {
      (**(code **)(*piVar3 + 0x48))(unaff_retaddr);
      return;
    }
    switch(sVar1) {
    case 0x31:
      if (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7de) {
        (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
        (*g_pLocalizationTable->vftable[9].GetTSimMgrClassNamePointer)(0x69);
        return;
      }
      break;
    case 0x32:
      if (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7db) {
        (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
        (*g_pLocalizationTable->vftable[9].GetTSimMgrClassNamePointer)(0x6a);
        return;
      }
      break;
    case 0x33:
      if ((*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7d9) &&
         (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7da)) {
        (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
        (*g_pLocalizationTable->vftable[9].GetTSimMgrClassNamePointer)(0x67);
        return;
      }
      break;
    case 0x34:
      if (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x7d8) {
        (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
        (*g_pLocalizationTable->vftable[9].GetTSimMgrClassNamePointer)(0x68);
        return;
      }
      break;
    case 0x35:
      if (*(short *)&g_pUiRuntimeContext->field_0x4 != 0x8fc) {
        (**(code **)&g_pSfxPlaybackSystem->vftable[1].field_0x10)(7000,0,1);
        (*g_pLocalizationTable->vftable[9].GetTSimMgrClassNamePointer)(0x6d);
        return;
      }
      break;
    default:
      goto switchD_004ffe93_default;
    }
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00500160
// GHIDRA_NAME TGameWindow::UpdateTurnOrderNavigationWindowLayout
// GHIDRA_PROTO undefined __thiscall UpdateTurnOrderNavigationWindowLayout(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Layout/update hook for turn-order navigation window. Applies viewport-rect-driven layout update when active event code is 0x7D1, then chains the class update callback.
// GHIDRA_COMMENT_END

/* Layout/update hook for turn-order navigation window. Applies viewport-rect-driven layout update
   when active event code is 0x7D1, then chains the class update callback. */

void TGameWindow::UpdateTurnOrderNavigationWindowLayout()

{
  TGameWindowVtbl *pTVar1;
  int *piVar2;
  LONG local_20;
  LONG LStack_1c;
  LONG LStack_18;
  tagRECT tStack_14;

  if (*(short *)(DAT_006a2158 + 0xe) == 0x7d1) {
    pTVar1 = this->vftable;
    (*pTVar1->OrphanRetStub_0059add0_4b)(&local_20);
    piVar2 = (int *)InitializeGlobalRectDefaultsIfUninitialized();
    CopyRect(&tStack_14,(RECT *)(*piVar2 + 4));
    local_20 = tStack_14.top;
    LStack_18 = tStack_14.bottom;
    LStack_1c = tStack_14.right;
    (*pTVar1->GetTEventHandlerClassNamePointer_5a)(&stack0xffffffdc,1);
  }
  (*this->vftable->NoOpTurnOrderNavigationVtableSlotA)();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00500200
// GHIDRA_NAME TGameWindow::NoOpTurnOrderNavigationVtableSlotA
// GHIDRA_PROTO undefined __thiscall NoOpTurnOrderNavigationVtableSlotA(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT No-op return stub (RET). Reached through a thunk-table entry used by turn-order-navigation vtable wiring.
// GHIDRA_COMMENT_END

/* No-op return stub (RET). Reached through a thunk-table entry used by turn-order-navigation vtable
   wiring. */

void TGameWindow::NoOpTurnOrderNavigationVtableSlotA()

{
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00500220
// GHIDRA_NAME TGameWindow::NoOpTurnOrderNavigationVtableSlotB
// GHIDRA_PROTO undefined __thiscall NoOpTurnOrderNavigationVtableSlotB(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT No-op return stub (RET). Secondary turn-order-navigation vtable slot mapped through thunk-table entry.
// GHIDRA_COMMENT_END

/* No-op return stub (RET). Secondary turn-order-navigation vtable slot mapped through thunk-table
   entry. */

void TGameWindow::NoOpTurnOrderNavigationVtableSlotB()

{
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00500240
// GHIDRA_NAME TGameWindow::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Turn-order navigation window cleanup override: executes class-specific teardown path and clears the display-manager active dialog slot (DAT_006a2158 + 0x4).
// GHIDRA_COMMENT_END

/* Turn-order navigation window cleanup override: executes class-specific teardown path and clears
   the display-manager active dialog slot (DAT_006a2158 + 0x4). */

void TGameWindow::_scalar_deleting_destructor_()

{
  (*this->vftable->NoOpTurnOrderNavigationVtableSlotB)();
  TWindow::_scalar_deleting_destructor_((TWindow *)this);
  *(undefined4 *)(DAT_006a2158 + 4) = 0;
  return;
}

