// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: THotspotBehavior.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0040133E
// GHIDRA_NAME THotspotBehavior::thunk_DestructTHotspotBehaviorAndMaybeFree
// GHIDRA_PROTO void * __thiscall thunk_DestructTHotspotBehaviorAndMaybeFree(byte freeSelfFlag)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to DestructTHotspotBehaviorAndMaybeFree
// GHIDRA_COMMENT_END

/* Single-JMP thunk to DestructTHotspotBehaviorAndMaybeFree */

void * __thiscall
THotspotBehavior::thunk_DestructTHotspotBehaviorAndMaybeFree
          (THotspotBehavior *this,byte freeSelfFlag)

{
  void *pvVar1;
  
  pvVar1 = DestructTHotspotBehaviorAndMaybeFree(this,freeSelfFlag);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00402856
// GHIDRA_NAME THotspotBehavior::thunk_GetTHotspotBehaviorClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetTHotspotBehaviorClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTHotspotBehaviorClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTHotspotBehaviorClassNamePointer */

void * __cdecl THotspotBehavior::thunk_GetTHotspotBehaviorClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetTHotspotBehaviorClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00407234
// GHIDRA_NAME THotspotBehavior::thunk_WrapperFor_AllocateWithFallbackHandler_At004b0c00
// GHIDRA_PROTO void __thiscall thunk_WrapperFor_AllocateWithFallbackHandler_At004b0c00(int arg1, int arg2)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to WrapperFor_AllocateWithFallbackHandler_At004b0c00
// GHIDRA_COMMENT_END

/* Single-JMP thunk to WrapperFor_AllocateWithFallbackHandler_At004b0c00 */

void __thiscall
THotspotBehavior::thunk_WrapperFor_AllocateWithFallbackHandler_At004b0c00
          (THotspotBehavior *this,int arg1,int arg2)

{
  WrapperFor_AllocateWithFallbackHandler_At004b0c00(this,arg1,arg2);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B0AF0
// GHIDRA_NAME THotspotBehavior::CreateTHotspotBehaviorInstance
// GHIDRA_PROTO void * __cdecl CreateTHotspotBehaviorInstance(void)

void * __cdecl THotspotBehavior::CreateTHotspotBehaviorInstance(void)

{
  TBehavior *pThis;
  TBehavior *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00630c1a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  pThis = (TBehavior *)AllocateWithFallbackHandler(0x10);
  local_4 = 0;
  pTVar1 = (TBehavior *)0x0;
  if (pThis != (TBehavior *)0x0) {
    TBehavior::ConstructTBehaviorBaseState(pThis);
    *(undefined ***)pThis = &g_vtblTHotspotBehavior;
    pTVar1 = pThis;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B0B60
// GHIDRA_NAME THotspotBehavior::GetTHotspotBehaviorClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTHotspotBehaviorClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for THotspotBehavior.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for THotspotBehavior. */

void * __cdecl THotspotBehavior::GetTHotspotBehaviorClassNamePointer(void)

{
  return &g_pClassDescTHotspotBehavior;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B0B80
// GHIDRA_NAME THotspotBehavior::ConstructTHotspotBehaviorBaseState
// GHIDRA_PROTO void * __thiscall ConstructTHotspotBehaviorBaseState(void)

void * __thiscall THotspotBehavior::ConstructTHotspotBehaviorBaseState(THotspotBehavior *this)

{
  TBehavior::ConstructTBehaviorBaseState((TBehavior *)this);
  *(undefined ***)this = &g_vtblTHotspotBehavior;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B0BB0
// GHIDRA_NAME THotspotBehavior::DestructTHotspotBehaviorAndMaybeFree
// GHIDRA_PROTO void * __thiscall DestructTHotspotBehaviorAndMaybeFree(byte freeSelfFlag)

void * __thiscall
THotspotBehavior::DestructTHotspotBehaviorAndMaybeFree(THotspotBehavior *this,byte freeSelfFlag)

{
  DestructTHotspotBehaviorAndMaybeFree_Impl();
  if ((freeSelfFlag & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004B0C00
// GHIDRA_NAME THotspotBehavior::WrapperFor_AllocateWithFallbackHandler_At004b0c00
// GHIDRA_PROTO void __thiscall WrapperFor_AllocateWithFallbackHandler_At004b0c00(int arg1, int arg2)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [WrapperShape] small wrapper around AllocateWithFallbackHandler; instructions=37, call_insns=2, internal_calls=1, unique_internal=1
// GHIDRA_COMMENT_END

/* [WrapperShape] small wrapper around AllocateWithFallbackHandler; instructions=37, call_insns=2,
   internal_calls=1, unique_internal=1 */

void __thiscall
THotspotBehavior::WrapperFor_AllocateWithFallbackHandler_At004b0c00
          (THotspotBehavior *this,int arg1,int arg2)

{
  undefined4 uVar1;
  int iVar2;
  undefined4 *puVar3;
  int *piVar4;
  
  piVar4 = *(int **)(this + 8);
  if ((piVar4[7] != 0x444c4f47) && (piVar4[7] != 0x6d61696e)) {
    piVar4 = (int *)piVar4[8];
  }
  puVar3 = (undefined4 *)AllocateWithFallbackHandler(0x14);
  if (puVar3 == (undefined4 *)0x0) {
    puVar3 = (undefined4 *)0x0;
  }
  else {
    puVar3[1] = 0;
    puVar3[2] = 0;
    puVar3[3] = 0;
    puVar3[4] = 0;
    *puVar3 = &PTR_thunk_GetTEventClassNamePointer_00649770;
  }
  uVar1 = *(undefined4 *)(this + 8);
  puVar3[2] = 0x6b;
  puVar3[1] = 0x6b;
  iVar2 = *piVar4;
  puVar3[3] = uVar1;
  puVar3[4] = piVar4;
  (**(code **)(iVar2 + 0x34))(puVar3);
  return;
}

