// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TInvadeMission.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0053F080
// GHIDRA_NAME TInvadeMission::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TInvadeMission::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_006344a2;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x38);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    func_0x004064a1(0xffffffff);
    *(undefined2 *)(puVar1 + 0xc) = 0xffff;
    *(undefined2 *)((int)puVar1 + 0x32) = 0xffff;
    puVar1[0xd] = 0;
    *puVar1 = &_vftable_;
    *unaff_FS_OFFSET = puVar1;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F160
// GHIDRA_NAME TInvadeMission::ForwardInvadeMissionArgToBeachheadSlot90
// GHIDRA_PROTO undefined __thiscall ForwardInvadeMissionArgToBeachheadSlot90(void)

void TInvadeMission::ForwardInvadeMissionArgToBeachheadSlot90()

{
  (**(code **)(**(int **)(this + 0x34) + 0x90))();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F190
// GHIDRA_NAME TInvadeMission::ForwardInvadeMissionArgsToBeachheadSlot84
// GHIDRA_PROTO undefined __thiscall ForwardInvadeMissionArgsToBeachheadSlot84(void)

void TInvadeMission::ForwardInvadeMissionArgsToBeachheadSlot84()

{
  (**(code **)(**(int **)(this + 0x34) + 0x84))();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F1C0
// GHIDRA_NAME TInvadeMission::ForwardInvadeMissionArgsToBeachheadSlot8C
// GHIDRA_PROTO undefined __thiscall ForwardInvadeMissionArgsToBeachheadSlot8C(void)

void TInvadeMission::ForwardInvadeMissionArgsToBeachheadSlot8C()

{
  (**(code **)(**(int **)(this + 0x34) + 0x8c))();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F1F0
// GHIDRA_NAME TInvadeMission::ComputeInvadeMissionCompositeScoreWithBeachhead
// GHIDRA_PROTO undefined __thiscall ComputeInvadeMissionCompositeScoreWithBeachhead(void)

float10 TInvadeMission::ComputeInvadeMissionCompositeScoreWithBeachhead()

{
  float fVar1;
  float fVar2;
  float fVar3;
  float *pfVar4;
  TInvadeMission *pTVar5;
  float10 fVar6;
  
  pfVar4 = (float *)&DAT_00697980;
  pTVar5 = this + 0x1c;
  fVar3 = g_Recompute_Nation_Order_LookupTable_0065A9E8;
  do {
    fVar1 = *(float *)pTVar5;
    fVar2 = *pfVar4;
    pfVar4 = pfVar4 + 1;
    pTVar5 = pTVar5 + 4;
    fVar3 = fVar1 * fVar2 + fVar3;
  } while ((int)pfVar4 < 0x697994);
  fVar6 = (float10)(**(code **)(**(int **)(this + 0x34) + 0x6c))();
  return fVar6 + (float10)fVar3;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F260
// GHIDRA_NAME TInvadeMission::GetRuntimeClass
// GHIDRA_PROTO undefined GetRuntimeClass()

undefined ** TInvadeMission::GetRuntimeClass(void)

{
  return &PTR_s_TInvadeMission_00697a70;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F3C0
// GHIDRA_NAME TInvadeMission::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TInvadeMission * TInvadeMission::_scalar_deleting_destructor_(byte param_1)

{
  func_0x004022fc();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F410
// GHIDRA_NAME TInvadeMission::CleanupTInvadeMissionAndReleaseOwnedOrders
// GHIDRA_PROTO undefined __thiscall CleanupTInvadeMissionAndReleaseOwnedOrders(void)

void TInvadeMission::CleanupTInvadeMissionAndReleaseOwnedOrders()

{
  int iVar1;
  int iVar2;
  
  (**(code **)(**(int **)(this + 0x34) + 0x1c))();
  (*g_apNationStates[*(short *)(this + 4)]->vftable->ConstructTTaskBaseState)();
  func_0x00402491((int)*(short *)(this + 0x30),0);
  iVar1 = func_0x00401118();
  iVar2 = func_0x00403620();
  while (iVar2 != 0) {
    *(undefined4 *)(iVar1 + 0x40) = 0;
    iVar1 = func_0x00406d20();
    iVar2 = func_0x00403620();
  }
  (**(code **)(**(int **)(this + 0x18) + 0x5c))();
  if (*(int **)(this + 0x18) != (int *)0x0) {
    (**(code **)(**(int **)(this + 0x18) + 0x58))();
  }
  *(undefined4 *)(this + 0x18) = 0;
  if (this != (TInvadeMission *)0x0) {
    (**(code **)(*(int *)this + 4))(1);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F4E0
// GHIDRA_NAME TInvadeMission::EvaluateInvadeMissionBeachheadAndQueueEligibleUnits
// GHIDRA_PROTO undefined __thiscall EvaluateInvadeMissionBeachheadAndQueueEligibleUnits(void)

uint TInvadeMission::EvaluateInvadeMissionBeachheadAndQueueEligibleUnits()

{
  short sVar1;
  uint uVar2;
  undefined4 uVar3;
  int iVar4;
  
  uVar2 = (**(code **)(**(int **)(this + 0x34) + 0x98))();
  if ((char)uVar2 == '\0') {
    return uVar2 & 0xffffff00;
  }
  uVar3 = func_0x00401118();
  iVar4 = func_0x00403620();
  while (iVar4 != 0) {
    sVar1 = func_0x00407e64();
    if (sVar1 != 0) {
      (**(code **)(*(int *)this + 0x88))(uVar3,1);
    }
    uVar3 = func_0x00406d20();
    iVar4 = func_0x00403620();
  }
  return 1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F580
// GHIDRA_NAME TInvadeMission::InitializeInvadeMissionFromNationAndTargetTile
// GHIDRA_PROTO undefined __thiscall InitializeInvadeMissionFromNationAndTargetTile(void)

void TInvadeMission::InitializeInvadeMissionFromNationAndTargetTile()

{
  func_0x0040163b(*(undefined2 *)(this + 4));
  this[0x11] = (TInvadeMission)0x1;
  if (*(short *)(this + 0x30) != -1) {
    *(short *)(this + 6) =
         (short)*(char *)(*(int *)&g_pGlobalMapState->field_0x10 + *(short *)(this + 0x30) * 0xa8);
  }
  this[0x11] = (TInvadeMission)0x3;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F5F0
// GHIDRA_NAME TInvadeMission::SetInvadeMissionKindTag2
// GHIDRA_PROTO undefined __thiscall SetInvadeMissionKindTag2(void)

void TInvadeMission::SetInvadeMissionKindTag2()

{
  this[8] = (TInvadeMission)0x2;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F640
// GHIDRA_NAME TInvadeMission::SerializeTInvadeMission
// GHIDRA_PROTO undefined __thiscall SerializeTInvadeMission(int * param_1)

void TInvadeMission::SerializeTInvadeMission(int *param_1)

{
  code *pcVar1;
  
  func_0x00407ec8(param_1);
  pcVar1 = *(code **)(*param_1 + 0x78);
  (*pcVar1)(this + 0x30,2);
  (*pcVar1)(this + 0x32,2);
  (**(code **)(**(int **)(this + 0x34) + 0x14))(param_1);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053F7D0
// GHIDRA_NAME TInvadeMission::AdvanceInvadeMissionCompositeHandlers
// GHIDRA_PROTO undefined __thiscall AdvanceInvadeMissionCompositeHandlers(void)

void TInvadeMission::AdvanceInvadeMissionCompositeHandlers()

{
  int iVar1;
  
  (**(code **)(**(int **)(this + 0x34) + 0x40))();
  iVar1 = *(int *)this;
  (**(code **)(iVar1 + 0x34))();
  (**(code **)(iVar1 + 0x38))();
  (**(code **)(iVar1 + 0x3c))();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053FAC0
// GHIDRA_NAME TInvadeMission::ComputeInvadeMissionWeightedScoreDelta
// GHIDRA_PROTO undefined __thiscall ComputeInvadeMissionWeightedScoreDelta(float param_1)

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

float10 TInvadeMission::ComputeInvadeMissionWeightedScoreDelta(float param_1)

{
  char cVar1;
  float10 fVar2;
  float10 fVar3;
  
  if (this[0x10] == (TInvadeMission)0x0) {
    if (*(TInvadeMission **)((int)param_1 + 0x40) == this) {
      fVar2 = (float10)(**(code **)(*(int *)this + 0x68))();
      fVar3 = (float10)func_0x00406686(param_1);
      fVar3 = (float10)(float)fVar2 - fVar3;
    }
    else {
      func_0x004031f2(param_1);
      fVar3 = (float10)(**(code **)(*(int *)this + 0x68))();
      fVar3 = (float10)param_1 - fVar3;
    }
    param_1 = (float)fVar3;
  }
  else {
    param_1 = 0.0;
  }
  cVar1 = (**(code **)(*(int *)this + 0x50))();
  if (cVar1 == '\0') {
    return (float10)param_1 * (float10)_DAT_0065aa58;
  }
  return (float10)param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053FB60
// GHIDRA_NAME TInvadeMission::ComputeInvadeMissionBeachheadScoreIfEnabled
// GHIDRA_PROTO undefined __thiscall ComputeInvadeMissionBeachheadScoreIfEnabled(void)

float10 TInvadeMission::ComputeInvadeMissionBeachheadScoreIfEnabled()

{
  float10 fVar1;
  
  if (this[0x10] != (TInvadeMission)0x0) {
    return (float10)g_Recompute_Nation_Order_LookupTable_0065A9E8;
  }
  fVar1 = (float10)(**(code **)(**(int **)(this + 0x34) + 0x74))();
  return fVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053FB90
// GHIDRA_NAME TInvadeMission::SetInvadeMissionBeachheadDisabledFlag
// GHIDRA_PROTO undefined __thiscall SetInvadeMissionBeachheadDisabledFlag(TInvadeMission param_1)

void TInvadeMission::SetInvadeMissionBeachheadDisabledFlag(undefined4 param_2)

{
  this[0x10] = SUB41(param_2,0);
  (**(code **)(**(int **)(this + 0x34) + 0x94))(param_2);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053FBC0
// GHIDRA_NAME TInvadeMission::HandleInvadeMissionActionOnTargetViaBeachhead
// GHIDRA_PROTO undefined __thiscall HandleInvadeMissionActionOnTargetViaBeachhead(int param_1, int param_2)

undefined4 __thiscall
TInvadeMission::HandleInvadeMissionActionOnTargetViaBeachhead
          (TInvadeMission *this,int param_1,int param_2)

{
  char cVar1;
  
  if (((param_1 == 2) && (param_2 == *(short *)(this + 0x30))) &&
     (*(int **)(this + 0x34) != (int *)0x0)) {
    cVar1 = (**(code **)(**(int **)(this + 0x34) + 0x4c))(2,param_2);
    if (cVar1 != '\0') {
      return 1;
    }
  }
  return 0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0053FC10
// GHIDRA_NAME TInvadeMission::BuildInvadeMissionUnitPriorityVectorAndScore
// GHIDRA_PROTO undefined __thiscall BuildInvadeMissionUnitPriorityVectorAndScore(undefined4 * param_1, undefined4 param_2)

int __thiscall
TInvadeMission::BuildInvadeMissionUnitPriorityVectorAndScore
          (TInvadeMission *this,undefined4 *param_1,undefined4 param_2)

{
  code *pcVar1;
  short sVar2;
  int *piVar3;
  int iVar4;
  undefined4 uVar5;
  int unaff_EBP;
  undefined4 *puVar6;
  int local_28;
  undefined4 local_1c [2];
  undefined4 local_14;
  undefined4 local_10;
  undefined4 local_c;
  undefined4 local_8;
  undefined4 local_4;
  
  local_14 = 0;
  local_10 = 0;
  local_1c[0] = *(undefined4 *)(this + 0x18);
  local_c = 0;
  local_8 = 0;
  local_4 = 0;
  piVar3 = (int *)func_0x00401118();
  iVar4 = func_0x00403620();
  if (iVar4 != 0) {
    pcVar1 = *(code **)(*(int *)this + 0x9c);
    do {
      (**(code **)(*piVar3 + 0xc))();
      uVar5 = (*pcVar1)();
      func_0x0040527c(uVar5);
      uVar5 = (*pcVar1)();
      sVar2 = func_0x00405dc1(uVar5);
      func_0x004072fc(piVar3,local_1c,0,(float)(int)sVar2);
      piVar3 = (int *)func_0x00406d20();
      iVar4 = func_0x00403620();
    } while (iVar4 != 0);
  }
  local_28 = 5;
  puVar6 = param_1;
  do {
    uVar5 = ftol();
    *puVar6 = uVar5;
    puVar6 = puVar6 + 1;
    local_28 = local_28 + -1;
  } while (local_28 != 0);
  iVar4 = (**(code **)(**(int **)(this + 0x34) + 0x2c))(param_1,param_2);
  return iVar4 + unaff_EBP;
}

