// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TLoadSavePicture.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0043D8F0
// GHIDRA_NAME TLoadSavePicture::ConstructUiBaseBackdropPictureEntry
// GHIDRA_PROTO undefined __thiscall ConstructUiBaseBackdropPictureEntry(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Derived picture constructor used with dominant 'base' tag call paths. Clears extended picture-state bytes before registration.
// GHIDRA_COMMENT_END

/* Derived picture constructor used with dominant 'base' tag call paths. Clears extended
   picture-state bytes before registration. */

TLoadSavePicture * __thiscall
TLoadSavePicture::ConstructUiBaseBackdropPictureEntry(TLoadSavePicture *this)

{
  thunk_TPictureButton::TPictureButton((thunk_TPictureButton *)this);
  this->field_0x9a = 0;
  this->field_0x9b = 0;
  this->field_0x9c = 0;
  this->field_0x9d = 0;
  this->field_0xa4 = 0;
  this->field_0xa5 = 0;
  this->field_0xa6 = 0;
  this->field_0xa7 = 0;
  this->vftable = &TLoadSavePictureVtbl_006426b8;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0043DA40
// GHIDRA_NAME TLoadSavePicture::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TLoadSavePicture * __thiscall
TLoadSavePicture::_scalar_deleting_destructor_(TLoadSavePicture *this,byte param_1)

{
  TView::DestructCityDialogSharedBaseState((TView *)this);
  if ((param_1 & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056BCA0
// GHIDRA_NAME TLoadSavePicture::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall TSoundPlayer::GetTEventHandlerClassNamePointer(void)

CRuntimeClass * __thiscall
TLoadSavePicture::GetTEventHandlerClassNamePointer(TLoadSavePicture *this)

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056BCC0
// GHIDRA_NAME TLoadSavePicture::OrphanLeaf_NoCall_Ins07_004d8920
// GHIDRA_PROTO undefined __thiscall TCommand::OrphanLeaf_NoCall_Ins07_004d8920(void)

void __thiscall TLoadSavePicture::OrphanLeaf_NoCall_Ins07_004d8920(TLoadSavePicture *this)

{
  TLoadSavePicture_slot_0x04_0x04 *pTVar1;
  int iVar2;
  undefined uVar3;
  char cVar4;
  short sVar5;
  undefined3 extraout_var;
  undefined3 extraout_var_00;
  undefined3 extraout_var_01;
  TLoadSavePicture *this_00;
  undefined3 extraout_var_02;
  undefined4 uVar6;
  undefined3 extraout_var_03;
  undefined3 extraout_var_04;
  undefined3 extraout_var_05;
  uint uVar7;
  uint uVar8;
  int iVar9;
  char *pcVar10;
  char *unaff_EDI;
  CString CVar11;
  char *pcVar12;
  int *unaff_FS_OFFSET;
  CString CStack_b0;
  CString *pCStack_ac;
  undefined *puStack_a8;
  CString CStack_a4;
  CString CStack_8c;
  CString CStack_88;
  CString CStack_84;
  CString CStack_80;
  CString CStack_7c;
  CString CStack_68;
  CString aCStack_64 [2];
  int iStack_5c;
  int aiStack_58 [2];
  TView *pTStack_50;
  CString aCStack_48 [2];
  undefined1 uStack_40;
  undefined1 uStack_38;
  undefined1 uStack_2c;
  undefined1 uStack_1c;
  CString CStack_18;
  CString CStack_14;
  CString CStack_10;
  int iStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  uStack_4 = 0xffffffff;
  puStack_8 = &LAB_00635e88;
  iStack_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = (int)&iStack_c;
  this->field_0x90 = DAT_00695278 == -2;
  *(undefined2 *)&this->field_0x92 = 0xffff;
  CStack_80.m_pchData = "hh+";
  TMapDialog::OrphanLeaf_NoCall_Ins07_004d8920((TView *)this);
  CStack_7c.m_pchData = (char *)0x2b68;
  CStack_80.m_pchData = (char *)0xc;
  CStack_88.m_pchData = &this->field_0x94;
  CStack_84.m_pchData = (char *)0x1;
  CStack_8c.m_pchData = (char *)0x56bd1c;
  BuildUiTextStyleDescriptor();
  CStack_88.m_pchData = &this->field_0x9e;
  CStack_7c.m_pchData = (char *)0x2b6c;
  CStack_80.m_pchData = (char *)0xc;
  CStack_84.m_pchData = (char *)0x0;
  CStack_8c.m_pchData = (char *)0x56bd35;
  BuildUiTextStyleDescriptor();
  pTVar1 = this->vftable[0x12].slot_0x04;
  CStack_7c.m_pchData = (char *)0x63757273;
  CStack_80.m_pchData = (char *)0x56bd49;
  uVar3 = (*pTVar1)();
  g_pCursorControlPanel = (TControl *)CONCAT31(extraout_var,uVar3);
  CStack_80.m_pchData = (char *)0x56bd55;
  (*g_pCursorControlPanel->vftable[1].slot_0x04)();
  CStack_80.m_pchData = (char *)0x2b6c;
  CStack_84.m_pchData = (char *)0x2b6b;
  CStack_88.m_pchData = (char *)0x56bd6d;
  (*g_pCursorControlPanel->vftable[0x40].slot_0x04)();
  CStack_88.m_pchData = (char *)0x1;
  CStack_8c.m_pchData = (char *)0x1;
  (*g_pCursorControlPanel->vftable[0x38].slot_0x04)();
  CString::CString(&CStack_10);
  CStack_18.m_pchData = (char *)0x0;
  CString::CString((CString *)&stack0xffffff88);
  CStack_18.m_pchData._0_1_ = 1;
  CStack_7c.m_pchData = (char *)0x0;
  do {
    uVar3 = (*pTVar1)();
    iVar9 = *(int *)CONCAT31(extraout_var_00,uVar3);
    (**(code **)(iVar9 + 0xc))();
    pcVar10 = PTR_DAT_0065ddd0;
    if (*(int *)&g_pLocalizationTable->field_0x44 != 0) {
      pcVar10 = PTR_DAT_0065ddd4;
    }
    CString::CString((CString *)&stack0xffffff88);
    uStack_1c = 2;
    if (CStack_80.m_pchData == (char *)0xa1) {
      CString::CString((CString *)&stack0xffffff8c,&DAT_0069872c);
      uStack_1c = 3;
      AssignStringSharedRefFromPointer();
      uStack_1c = 2;
      CString::~CString((CString *)&stack0xffffff8c);
    }
    else {
      FormatStringWithVarArgsToSharedRef();
    }
    TToolBarCluster::WrapperFor_ConstructSharedStringFromCStrOrResourceId_At004ac370
              ((TToolBarCluster *)&stack0xffffff90,s_Save__00698724);
    uStack_1c = 4;
    AssignStringSharedRefFromPointer();
    uStack_1c = 2;
    CString::~CString((CString *)&stack0xffffff90);
    CString::AssignFromCStr(&CStack_14,pcVar10);
    AssignStringSharedFromRef();
    CString::AssignFromCStr(&CStack_14,PTR_DAT_0065ddd8);
    uStack_1c = 1;
    CString::~CString((CString *)&stack0xffffff88);
    cVar4 = TryGetFileMetadataForPath();
    if (cVar4 == '\0') {
      if (this->field_0x90 == '\0') {
        (**(code **)(iVar9 + 0x1cc))();
        goto LAB_0056bf9f;
      }
      (**(code **)(iVar9 + 0xa4))();
      CStack_a4.m_pchData = (char *)0x56bf8e;
      (**(code **)(iVar9 + 0xa8))();
    }
    else {
      OpenBufferedStreamWithMode40();
      CStack_a4.m_pchData = (char *)0x56bee4;
      ReadBufferedStreamLocked();
      CloseBufferedStreamAndReleaseResources();
      iVar2 = iStack_5c;
      CString::CString(&CStack_68,(char *)aiStack_58);
      uStack_1c = 5;
      CString::AssignFromPtr(&CStack_7c,&CStack_68);
      uStack_1c = 1;
      CString::~CString(&CStack_68);
      if (((*(int *)&g_pLocalizationTable->field_0x44 == 1) &&
          (iVar2 == *(int *)&g_pGameFlowState->field_0x64)) && (this->field_0x90 == '\0')) {
        uVar7 = 0xffffffff;
        CVar11.m_pchData = CStack_7c.m_pchData;
        goto code_r0x0056c450;
      }
      (**(code **)(iVar9 + 0x1c8))();
LAB_0056bf9f:
      CStack_a4.m_pchData = (char *)0x56bfb0;
      (**(code **)(iVar9 + 0x1b4))();
    }
    CStack_7c.m_pchData = CStack_7c.m_pchData + 1;
  } while ((int)CStack_7c.m_pchData < 8);
  if (this->field_0x90 == '\0') {
LAB_0056c0cb:
    uVar3 = (*pTVar1)();
    iVar9 = *(int *)CONCAT31(extraout_var_01,uVar3);
    (**(code **)(iVar9 + 0xc))();
    (**(code **)(iVar9 + 0xa4))();
    this_00 = (TLoadSavePicture *)(**(code **)(iVar9 + 0x94))();
    (*this_00->vftable[1].slot_0x04)();
    CStack_a4.m_pchData = (char *)0x56c108;
    TLoadSavePicture::RasterizeHexNeighborTerrainPaletteMap(this_00,0);
    sVar5 = UiRuntimeContext::GetActiveNationId();
    *(int *)&this_00->field_0x68 = (int)sVar5;
    ApplyPaletteMaskToTileBufferByEventCode();
    CStack_a4.m_pchData = (char *)0x56c129;
    uVar3 = (*pTVar1)();
    iVar9 = *(int *)CONCAT31(extraout_var_02,uVar3);
    CStack_a4.m_pchData = (char *)0x56c132;
    (**(code **)(iVar9 + 0xc))();
    CStack_a4.m_pchData = (char *)0x56c13b;
    CString::CString(&CStack_88);
    uStack_2c = 0xb;
    CStack_a4.m_pchData = (char *)0x56c149;
    CString::CString(&CStack_84);
    uStack_2c = 0xc;
    CStack_a4.m_pchData = (char *)0x56c157;
    CString::CString((CString *)&stack0xffffff70);
    CStack_a4.m_pchData = (char *)&CStack_88;
    uStack_2c = 0xd;
    puStack_a8 = (undefined *)0x56c16c;
    UiRuntimeContext::GetActiveNationId();
    puStack_a8 = (undefined *)0x56c17b;
    FormatOverlayTerrainLabelText();
    pCStack_ac = &CStack_84;
    CStack_a4.m_pchData =
         (char *)((short)((int)((int)*(short *)&g_pLocalizationTable->field_0x2c +
                               ((int)*(short *)&g_pLocalizationTable->field_0x2c >> 0x1f & 3U)) >> 2
                         ) + 0x717);
    puStack_a8 = &g_szDecimalFormat;
    CStack_b0.m_pchData = (char *)0x56c1a6;
    FormatStringWithVarArgsToSharedRef();
    CStack_a4.m_pchData = &stack0xffffff70;
    puStack_a8 = (undefined *)(*(int *)&g_pLocalizationTable->field_0x40 + 0xd);
    pCStack_ac = (CString *)0x2737;
    CStack_b0.m_pchData = (char *)0x56c1c8;
    (*g_pLocalizationTable->vftable[0x10].slot_0x04)();
    CStack_b0.m_pchData = &stack0xffffff64;
    uVar6 = AssignSharedStringConcatCStrAndRef(&CStack_8c,&DAT_00695880);
    CStack_b0.m_pchData = &DAT_00695760;
    uStack_38 = 0xe;
    uVar6 = AssignSharedStringConcatRefAndCStr(&CStack_88,uVar6);
    CStack_b0.m_pchData = &stack0xffffff70;
    uStack_38 = 0xf;
    CStack_b0.m_pchData = (char *)AssignSharedStringConcatRefAndRef(&CStack_84,uVar6);
    uStack_38 = 0x10;
    AssignStringSharedFromRef();
    uStack_38 = 0xf;
    CStack_b0.m_pchData = (char *)0x56c226;
    CString::~CString(&CStack_84);
    uStack_38 = 0xe;
    CStack_b0.m_pchData = (char *)0x56c234;
    CString::~CString(&CStack_88);
    uStack_38 = 0xd;
    CStack_b0.m_pchData = (char *)0x56c242;
    CString::~CString(&CStack_8c);
    CStack_b0.m_pchData = (char *)0x0;
    (**(code **)(iVar9 + 0x1c8))(&stack0xffffff6c);
    uStack_40 = 0xc;
    CString::~CString(&CStack_a4);
    uStack_40 = 0xb;
    CString::~CString((CString *)&stack0xffffff68);
    uStack_40 = 1;
    CString::~CString((CString *)&stack0xffffff64);
  }
  else {
    pcVar10 = PTR_DAT_0065ddd4;
    if (*(int *)&g_pLocalizationTable->field_0x44 == 0) {
      pcVar10 = PTR_DAT_0065ddd0;
    }
    CString::CString((CString *)&stack0xffffff8c);
    CStack_18.m_pchData._0_1_ = 8;
    CString::CString(aCStack_64,&DAT_0069872c);
    CStack_18.m_pchData._0_1_ = 9;
    CString::AssignFromPtr((CString *)&stack0xffffff8c,aCStack_64);
    CStack_18.m_pchData._0_1_ = 8;
    CString::~CString(aCStack_64);
    CString::CString(aCStack_64,s_Save__00698724);
    CStack_18.m_pchData._0_1_ = 10;
    AssignStringSharedRefFromPointer();
    CStack_18.m_pchData._0_1_ = 8;
    CString::~CString(aCStack_64);
    CString::AssignFromCStr(&CStack_10,pcVar10);
    AssignStringSharedFromRef();
    CString::AssignFromCStr(&CStack_10,PTR_DAT_0065ddd8);
    CStack_18.m_pchData._0_1_ = 1;
    CString::~CString((CString *)&stack0xffffff8c);
    cVar4 = TryGetFileMetadataForPath();
    if (cVar4 != '\0') {
      (*pTVar1)();
      QueueDeferredUiEventPacket();
    }
    if (this->field_0x90 == '\0') goto LAB_0056c0cb;
    uVar3 = (*pTVar1)();
    iVar9 = *(int *)CONCAT31(extraout_var_03,uVar3);
    (**(code **)(iVar9 + 0xc))();
    (**(code **)(iVar9 + 0x1c8))();
  }
  RefreshActiveControlThenApplyThemeStyleAndCaption(0x696e666f,0,0xc,0x2b6a,0,0);
  if (this->field_0x90 == '\0') {
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0xb,this);
    uVar3 = (*pTVar1)(0x6f74746f);
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0xb,uVar3);
    uVar3 = (*pTVar1)(0x636e636c);
    LoadUiStringByGroupAndIndexToControlObject(0x2758,0x15,uVar3);
    uVar3 = (*pTVar1)(0x6d617020);
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0x16,uVar3);
    uVar3 = (*pTVar1)(0x6f6b6179);
    LoadUiStringByGroupAndIndexToControlObject(0x2743,2,uVar3);
    iVar9 = 0;
    do {
      uVar3 = (*pTVar1)(iVar9 + 0x736c7430);
      (**(code **)(*(int *)CONCAT31(extraout_var_05,uVar3) + 0xc))();
      LoadUiStringByGroupAndIndexToControlObject(0x2758,0x16,(int *)CONCAT31(extraout_var_05,uVar3))
      ;
      iVar9 = iVar9 + 1;
    } while (iVar9 < 8);
  }
  else {
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0xc,this);
    uVar3 = (*pTVar1)(0x6f74746f);
    LoadUiStringByGroupAndIndexToControlObject(0x2758,0x11,uVar3);
    uVar3 = (*pTVar1)(0x636e636c);
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0x14,uVar3);
    uVar3 = (*pTVar1)(0x6d617020);
    LoadUiStringByGroupAndIndexToControlObject(0x2737,0x16,uVar3);
    uVar3 = (*pTVar1)(0x6f6b6179);
    LoadUiStringByGroupAndIndexToControlObject(0x2758,0x14,uVar3);
    iVar9 = 0;
    do {
      uVar3 = (*pTVar1)(iVar9 + 0x736c7430);
      (**(code **)(*(int *)CONCAT31(extraout_var_04,uVar3) + 0xc))();
      LoadUiStringByGroupAndIndexToControlObject(0x2758,0x12,(int *)CONCAT31(extraout_var_04,uVar3))
      ;
      iVar9 = iVar9 + 1;
    } while (iVar9 < 8);
  }
LAB_0056c411:
  pTStack_50 = (TView *)((uint)pTStack_50 & 0xffffff00);
  CString::~CString(&CStack_b0);
  pTStack_50 = (TView *)0xffffffff;
  CString::~CString(aCStack_48);
  *unaff_FS_OFFSET = aiStack_58[0];
  return;
  while( true ) {
    uVar7 = uVar7 - 1;
    pcVar10 = CVar11.m_pchData + 1;
    cVar4 = *CVar11.m_pchData;
    CVar11.m_pchData = pcVar10;
    if (cVar4 == '\0') break;
code_r0x0056c450:
    pcVar10 = CVar11.m_pchData;
    if (uVar7 == 0) break;
  }
  uVar7 = ~uVar7;
  pcVar10 = pcVar10 + -uVar7;
  pcVar12 = (char *)&DAT_006a2178;
  for (uVar8 = uVar7 >> 2; uVar8 != 0; uVar8 = uVar8 - 1) {
    *(undefined4 *)pcVar12 = *(undefined4 *)pcVar10;
    pcVar10 = pcVar10 + 4;
    pcVar12 = pcVar12 + 4;
  }
  for (uVar7 = uVar7 & 3; uVar7 != 0; uVar7 = uVar7 - 1) {
    *pcVar12 = *pcVar10;
    pcVar10 = pcVar10 + 1;
    pcVar12 = pcVar12 + 1;
  }
  cVar4 = TrySaveGameAndMaybeShowFailureDialog();
  if (cVar4 != '\0') {
    CString::CString(&CStack_80);
    uStack_1c = 6;
    CString::CString((CString *)&stack0xffffff88);
    uStack_1c = 7;
    LoadUiStringResourceByGroupAndIndex();
    CStack_a4.m_pchData = (char *)0x56c4d8;
    scanBracketExpressions(g_pLocalizationTable,&CStack_80,unaff_EDI);
    CreateModalMessageCommandAndQueue();
    uStack_1c = 6;
    CString::~CString((CString *)&stack0xffffff88);
    uStack_1c = 1;
    CString::~CString(&CStack_80);
  }
  (*g_pLocalizationTable->vftable[8].slot_0x04)();
  goto LAB_0056c411;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056C740
// GHIDRA_NAME TLoadSavePicture::DestructTLoadSavePictureAndMaybeFree
// GHIDRA_PROTO undefined __thiscall TLoadSavePicture::DestructTLoadSavePictureAndMaybeFree(int param_1)

void __thiscall
TLoadSavePicture::DestructTLoadSavePictureAndMaybeFree(TLoadSavePicture *this,int param_1)

{
  TLoadSavePicture_slot_0x04_0x04 *pTVar1;
  char cVar2;
  undefined uVar3;
  int iVar4;
  undefined3 extraout_var;
  undefined3 extraout_var_00;
  undefined3 extraout_var_01;
  undefined4 uVar5;
  undefined4 unaff_EBP;
  char *text;
  undefined4 *unaff_FS_OFFSET;
  CString local_a0;
  undefined1 local_9c [52];
  int iStack_68;
  int iStack_64;
  int iStack_60;
  tagRECT tStack_5c;
  char local_4c [40];
  undefined1 uStack_24;
  undefined1 uStack_18;
  undefined4 uStack_c;
  undefined1 *puStack_8;
  int local_4;
  TLoadSavePicture *this_00;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00635f36;
  uStack_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &uStack_c;
  CString::CString((CString *)(local_9c + 4));
  local_4 = 0;
  text = PTR_DAT_0065ddd4;
  if (*(int *)&g_pLocalizationTable->field_0x44 == 0) {
    text = PTR_DAT_0065ddd0;
  }
  CString::CString(&local_a0);
  local_4._0_1_ = 1;
  if (param_1 == 0xa1) {
    TToolBarCluster::WrapperFor_ConstructSharedStringFromCStrOrResourceId_At004ac370
              ((TToolBarCluster *)local_9c,&DAT_0069872c);
    local_4._0_1_ = 2;
    AssignStringSharedRefFromPointer();
    local_4._0_1_ = 1;
    CString::~CString((CString *)local_9c);
  }
  else {
    FormatStringWithVarArgsToSharedRef();
  }
  TToolBarCluster::WrapperFor_ConstructSharedStringFromCStrOrResourceId_At004ac370
            ((TToolBarCluster *)local_9c,s_Save__00698724);
  local_4._0_1_ = 3;
  AssignStringSharedRefFromPointer();
  local_4._0_1_ = 1;
  CString::~CString((CString *)local_9c);
  CString::AssignFromCStr((CString *)(local_9c + 4),text);
  AssignStringSharedFromRef();
  CString::AssignFromCStr((CString *)(local_9c + 4),PTR_DAT_0065ddd8);
  local_4 = (uint)local_4._1_3_ << 8;
  CString::~CString(&local_a0);
  cVar2 = TryGetFileMetadataForPath();
  if (cVar2 != '\0') {
    iVar4 = AllocateWithFallbackHandler();
    if (iVar4 == 0) {
      MessageBoxA((HWND)0x0,s_Nil_Pointer_00694fc8,s_Failure_00694fd8,0x30);
      TemporarilyClearAndRestoreUiInvalidationFlag();
    }
    OpenBufferedStreamWithMode40();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    ReadBufferedStreamLocked();
    CloseBufferedStreamAndReleaseResources();
    pTVar1 = this->vftable[0x12].slot_0x04;
    uVar3 = (*pTVar1)();
    this_00 = (TLoadSavePicture *)CONCAT31(extraout_var,uVar3);
    local_9c._8_4_ = this_00->vftable;
    (*((TLoadSavePictureVtbl *)(local_9c._8_4_ + 8))->slot_0x04)();
    TLoadSavePicture::RasterizeHexNeighborTerrainPaletteMap(this_00,iVar4);
    *(int *)&this_00->field_0x68 = (int)local_9c[7];
    ApplyPaletteMaskToTileBufferByEventCode();
    (*((TLoadSavePictureVtbl *)(local_9c._8_4_ + 0xe0))->slot_0x04)();
    FreeHeapBufferIfNotNull();
    uVar3 = (*pTVar1)();
    iVar4 = *(int *)CONCAT31(extraout_var_00,uVar3);
    (**(code **)(iVar4 + 0xc))();
    (**(code **)(iVar4 + 0xa4))();
    uVar3 = (*pTVar1)(0x696e666f);
    iVar4 = *(int *)CONCAT31(extraout_var_01,uVar3);
    (**(code **)(iVar4 + 0xc))();
    CString::CString((CString *)&stack0xffffff4c);
    uStack_18 = 4;
    CString::CString((CString *)&stack0xffffff50);
    uStack_18 = 5;
    CString::CString(&local_a0);
    uStack_18 = 6;
    FormatStringWithVarArgsToSharedRef
              (&stack0xffffff50,&g_szDecimalFormat,(short)local_9c._2_2_ + 0x717);
    (*g_pLocalizationTable->vftable[0x10].slot_0x04)
              (0x2737,CONCAT22((short)((uint)&local_a0 >> 0x10),
                               (short)(char)((uint)unaff_EBP >> 0x10)) + 0xd,&local_a0);
    CString::CString((CString *)&stack0xffffff50,local_9c + 0x30);
    uStack_24 = 7;
    CString::AssignFromPtr((CString *)&stack0xffffff40,(CString *)&stack0xffffff50);
    uStack_24 = 6;
    CString::~CString((CString *)&stack0xffffff50);
    CString::AssignFromCStr((CString *)&stack0xffffff40,&DAT_00695880);
    CString::AssignFromCStr((CString *)&stack0xffffff40,local_4c);
    uVar5 = AssignSharedStringConcatCStrAndRef(&local_a0,&DAT_00695880,&stack0xffffff54);
    uStack_24 = 8;
    uVar5 = AssignSharedStringConcatRefAndCStr(&stack0xffffff5c,uVar5,&DAT_00695760);
    uStack_24 = 9;
    uVar5 = AssignSharedStringConcatRefAndRef(&stack0xffffff50,uVar5,&stack0xffffff44);
    uStack_24 = 10;
    AssignStringSharedFromRef(uVar5);
    uStack_24 = 9;
    CString::~CString((CString *)&stack0xffffff50);
    uStack_24 = 8;
    CString::~CString((CString *)&stack0xffffff5c);
    uStack_24 = 6;
    CString::~CString(&local_a0);
    (**(code **)(iVar4 + 0x1c8))(&stack0xffffff40,0);
    (**(code **)(iVar4 + 300))(&stack0xffffff5c);
    iStack_68 = local_9c._36_4_;
    iStack_64 = local_9c._40_4_;
    local_9c._48_4_ = local_9c._32_4_;
    iStack_60 = local_9c._44_4_;
    CopyRect(&tStack_5c,(RECT *)(local_9c + 0x30));
    InvalidateCityDialogRectRegion();
    local_4._0_1_ = 5;
    CString::~CString((CString *)(local_9c + 0x10));
    local_4._0_1_ = 4;
    CString::~CString((CString *)local_9c);
    local_4 = (uint)local_4._1_3_ << 8;
    CString::~CString(&local_a0);
  }
  local_4 = 0xffffffff;
  CString::~CString((CString *)(local_9c + 4));
  *unaff_FS_OFFSET = uStack_c;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056CD10
// GHIDRA_NAME TLoadSavePicture::ReleaseRuntimeSelectionOwnerAndDestroyObject
// GHIDRA_PROTO undefined __thiscall TEventHandler::ReleaseRuntimeSelectionOwnerAndDestroyObject(int param_1, CString param_2)

void __thiscall
TLoadSavePicture::ReleaseRuntimeSelectionOwnerAndDestroyObject
          (TLoadSavePicture *this,int param_1,CString param_2)

{
  short sVar1;
  int iVar2;
  CString CVar3;
  undefined uVar4;
  undefined3 extraout_var;
  TEditText *this_00;
  undefined3 extraout_var_00;
  undefined3 extraout_var_01;
  short sVar5;
  int *piVar6;
  undefined4 *unaff_FS_OFFSET;
  RECT RStack_3c;
  RECT RStack_2c;
  tagRECT tStack_1c;
  undefined4 uStack_c;
  undefined1 *puStack_8;
  int iStack_4;
  
  CVar3.m_pchData = param_2.m_pchData;
  uStack_c = *unaff_FS_OFFSET;
  iStack_4 = -1;
  puStack_8 = &LAB_00635f72;
  *unaff_FS_OFFSET = &uStack_c;
  if (param_1 == 0xd) {
    sVar1 = *(short *)&this->field_0x92;
    sVar5 = *(short *)(param_2.m_pchData + 0x1c) + -0x7430;
    if (sVar5 != sVar1) {
      if (this->field_0x90 == '\0') {
        if (sVar1 == -1) {
          CString::CString(&param_2);
          piVar6 = (int *)0x0;
          iStack_4 = 0;
          (**(code **)(*(int *)CVar3.m_pchData + 0xc))();
          this_00 = (TEditText *)AllocateWithFallbackHandler(0xa0);
          iStack_4._0_1_ = 1;
          if (this_00 != (TEditText *)0x0) {
            piVar6 = (int *)TEditText::ConstructUiNumericTextEntryBase(this_00);
          }
          iStack_4 = (uint)iStack_4._1_3_ << 8;
          WrapperFor_thunk_InitializeTextEntryBaseAndOptionalStringResource_At004905e0
                    (this,CVar3.m_pchData + 0x24,CVar3.m_pchData + 0x34,0x1f);
          *(short *)&this->field_0x92 = sVar5;
          iVar2 = *(int *)CVar3.m_pchData;
          (**(code **)(iVar2 + 0xa4))(0,1);
          (**(code **)(iVar2 + 0x1d0))(&stack0x00000000);
          iVar2 = *piVar6;
          (**(code **)(iVar2 + 0x1b4))(&this->field_0x9e,0);
          (**(code **)(iVar2 + 0x1e0))(&uStack_c,0);
          (**(code **)(iVar2 + 0xf8))();
          (**(code **)(iVar2 + 0x7c))();
          (**(code **)(iVar2 + 0x1d8))(0,*(undefined4 *)(tStack_1c.right + -8),0);
          piVar6[7] = 0x736c6f74;
          (**(code **)(g_pUiRuntimeContext->vftable + 0x30))(0x10);
          iStack_4 = -1;
          CString::~CString(&param_2);
        }
      }
      else {
        if ((sVar1 != -1) && (sVar1 != 0xa1)) {
          uVar4 = (*this->vftable[0x12].slot_0x04)(sVar1 + 0x736c7430);
          iVar2 = *(int *)CONCAT31(extraout_var,uVar4);
          (**(code **)(iVar2 + 0xc))();
          (**(code **)(iVar2 + 0x1b4))(&this->field_0x9e,0);
          (**(code **)(iStack_4 + 300))(&stack0xffffffb8);
          RStack_2c.top = RStack_3c.top;
          RStack_2c.right = RStack_3c.right;
          RStack_2c.left = RStack_3c.left;
          RStack_2c.bottom = RStack_3c.bottom;
          CopyRect(&tStack_1c,&RStack_2c);
          InvalidateCityDialogRectRegion(&tStack_1c,1);
        }
        iVar2 = *(int *)CVar3.m_pchData;
        (**(code **)(iVar2 + 0x1b4))(&this->field_0x94,0);
        (**(code **)(iVar2 + 300))(&stack0xffffffbc);
        RStack_2c.top = RStack_3c.top;
        RStack_2c.right = RStack_3c.right;
        RStack_2c.left = RStack_3c.left;
        RStack_2c.bottom = RStack_3c.bottom;
        CopyRect(&tStack_1c,&RStack_2c);
        InvalidateCityDialogRectRegion(&tStack_1c,1);
        *(short *)&this->field_0x92 = sVar5;
        TLoadSavePicture::DestructTLoadSavePictureAndMaybeFree(this,(int)sVar5);
      }
    }
    if (1 < *(int *)&g_pApplicationUiRootController->field_0x24) {
      uVar4 = (*this->vftable[0x12].slot_0x04)(0x6f6b6179);
      if (CONCAT31(extraout_var_00,uVar4) != 0) {
        QueueDeferredUiEventPacket(this,10,CONCAT31(extraout_var_00,uVar4));
      }
    }
  }
  else if (param_1 == 0x14) {
    if (*(int *)(param_2.m_pchData + 0x1c) == 0x636e636c) {
      (*this->vftable[0x3a].GetTEventHandlerClassNamePointer)();
    }
    if ((this->field_0x90 != '\0') && (*(int *)(CVar3.m_pchData + 0x1c) == 0x6f74746f)) {
      sVar1 = *(short *)&this->field_0x92;
      if ((sVar1 != -1) && (sVar1 != 0xa1)) {
        uVar4 = (*this->vftable[0x12].slot_0x04)(sVar1 + 0x736c7430);
        iVar2 = *(int *)CONCAT31(extraout_var_01,uVar4);
        (**(code **)(iVar2 + 0xc))();
        (**(code **)(iVar2 + 0x1b4))(&this->field_0x9e,0);
        (**(code **)(iVar2 + 300))(&RStack_3c.top);
        RStack_3c.top = RStack_2c.top;
        RStack_3c.right = RStack_2c.right;
        RStack_3c.left = RStack_2c.left;
        RStack_3c.bottom = RStack_2c.bottom;
        CopyRect(&tStack_1c,&RStack_3c);
        InvalidateCityDialogRectRegion(&tStack_1c,1);
      }
      *(undefined2 *)&this->field_0x92 = 0xa1;
      TLoadSavePicture::DestructTLoadSavePictureAndMaybeFree(this,0xa1);
    }
  }
  else if ((param_1 == 10) && (*(int *)(param_2.m_pchData + 0x1c) == 0x6f6b6179)) {
    (*this->vftable[0x39].slot_0x04)();
  }
  *unaff_FS_OFFSET = uStack_c;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056D190
// GHIDRA_NAME TLoadSavePicture::HandleTurnFlowStateTickOrPostTurnEvent5DC
// GHIDRA_PROTO undefined __thiscall HandleTurnFlowStateTickOrPostTurnEvent5DC(void)

void __thiscall TLoadSavePicture::HandleTurnFlowStateTickOrPostTurnEvent5DC(TLoadSavePicture *this)

{
  if (*(int *)&g_pLocalizationTable->field_0x8 != 1) {
                    /* WARNING: Could not recover jumptable at 0x0056d1c8. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*g_pLocalizationTable->vftable[8].slot_0x04)();
    return;
  }
  if (*(int *)&g_pLocalizationTable->field_0x44 != 0) {
    ResetLocalUiStateAndPostTurnEvent5E5();
    return;
  }
  PostTurnEventCodeMessage2420(0x5dc);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056D1E0
// GHIDRA_NAME TLoadSavePicture::OrphanTiny_ReturnZero_0048a730
// GHIDRA_PROTO undefined __thiscall TDropShadowText::OrphanTiny_ReturnZero_0048a730(int param_1)

void __thiscall TLoadSavePicture::OrphanTiny_ReturnZero_0048a730(TLoadSavePicture *this,int param_1)

{
  short sVar1;
  TLoadSavePicture_slot_0x04_0x04 *pTVar2;
  undefined uVar3;
  undefined3 extraout_var;
  int iVar4;
  undefined2 extraout_var_01;
  undefined3 extraout_var_00;
  
  sVar1 = *(short *)(param_1 + 0x1c);
  if ((sVar1 == 3) || (sVar1 == 0xd)) {
    uVar3 = (*this->vftable[0x12].slot_0x04)(0x6f6b6179);
    iVar4 = CONCAT31(extraout_var_00,uVar3);
    if (iVar4 != 0) {
      (*g_pSfxPlaybackSystem->vftable[0x17].GetTEventHandlerClassNamePointer)
                (CONCAT22(extraout_var_01,*(undefined2 *)(iVar4 + 0x92)),0,1);
      QueueDeferredUiEventPacket(this,10,iVar4);
    }
  }
  else if (sVar1 == 0x1b) {
    pTVar2 = this->vftable[0x12].slot_0x04;
    uVar3 = (*pTVar2)(0x636e636c);
    if (CONCAT31(extraout_var,uVar3) != 0) {
      uVar3 = (*pTVar2)(0x636e636c);
      QueueDeferredUiEventPacket(this,0x14,uVar3);
      return;
    }
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0056D2A0
// GHIDRA_NAME TLoadSavePicture::HandleSaveGameSlotSelectionAndPromptFlow
// GHIDRA_PROTO undefined __thiscall HandleSaveGameSlotSelectionAndPromptFlow(void)

void __thiscall TLoadSavePicture::HandleSaveGameSlotSelectionAndPromptFlow(TLoadSavePicture *this)

{
  short sVar1;
  int iVar2;
  char cVar3;
  undefined uVar4;
  undefined3 extraout_var;
  undefined3 extraout_var_00;
  int iVar5;
  CString *src_ref;
  uint uVar6;
  uint uVar7;
  char *unaff_EBP;
  char *pcVar8;
  undefined *puVar9;
  char *pcVar10;
  undefined4 *unaff_FS_OFFSET;
  CString aCStack_14 [2];
  undefined4 uStack_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  uStack_c = *unaff_FS_OFFSET;
  uStack_4 = 0xffffffff;
  puStack_8 = &LAB_00635fa8;
  *unaff_FS_OFFSET = &uStack_c;
  if (*(short *)&this->field_0x92 == -1) {
    if (this->field_0x90 == '\0') {
      ShowLocalizedUiPromptByGroupAndIndex(0x2758,0x17,1,0);
      *unaff_FS_OFFSET = uStack_c;
      return;
    }
    goto LAB_0056d50c;
  }
  if (this->field_0x90 == '\0') {
    CString::CString(aCStack_14);
    uStack_4 = 1;
    uVar4 = (*this->vftable[0x12].slot_0x04)(0x736c6f74);
    iVar2 = *(int *)CONCAT31(extraout_var_00,uVar4);
    (**(code **)(iVar2 + 0xc))();
    (**(code **)(iVar2 + 0x1dc))(&stack0xffffffe8);
    iVar5 = CompareAnsiStringsWithMbcsAwareness(unaff_EBP,PTR_g_szEmptyString_0065ddc8);
    if (iVar5 == 0) {
      src_ref = (CString *)BuildSharedStringFromMappedFlavorTextIndex(&stack0xffffffe8,0xd);
      uStack_c._0_1_ = 2;
      CString::AssignFromPtr((CString *)&stack0xffffffe4,src_ref);
      uStack_c = CONCAT31(uStack_c._1_3_,1);
      CString::~CString((CString *)&stack0xffffffe8);
      (**(code **)(iVar2 + 0x1e0))(&stack0xffffffe4,1);
      (**(code **)(iVar2 + 0x13c))();
    }
    uVar6 = 0xffffffff;
    do {
      pcVar8 = unaff_EBP;
      if (uVar6 == 0) break;
      uVar6 = uVar6 - 1;
      pcVar8 = unaff_EBP + 1;
      cVar3 = *unaff_EBP;
      unaff_EBP = pcVar8;
    } while (cVar3 != '\0');
    uVar6 = ~uVar6;
    pcVar8 = pcVar8 + -uVar6;
    pcVar10 = (char *)&DAT_006a2178;
    for (uVar7 = uVar6 >> 2; uVar7 != 0; uVar7 = uVar7 - 1) {
      *(undefined4 *)pcVar10 = *(undefined4 *)pcVar8;
      pcVar8 = pcVar8 + 4;
      pcVar10 = pcVar10 + 4;
    }
    for (uVar6 = uVar6 & 3; uVar6 != 0; uVar6 = uVar6 - 1) {
      *pcVar10 = *pcVar8;
      pcVar8 = pcVar8 + 1;
      pcVar10 = pcVar10 + 1;
    }
    if (*(int *)&g_pLocalizationTable->field_0x44 == 0) {
      SaveGameWithModeAndOptionalLabel((int)*(short *)&this->field_0x92,PTR_DAT_0065ddd0);
    }
    else {
      TrySaveGameAndMaybeShowFailureDialog
                ((int)*(short *)&this->field_0x92,PTR_DAT_0065ddd4,1);
    }
    (*g_pLocalizationTable->vftable[8].slot_0x04)();
LAB_0056d4d7:
    uStack_4 = 0xffffffff;
    CString::~CString(aCStack_14);
  }
  else if ((*(int *)&g_pLocalizationTable->field_0x8 == 1) ||
          (cVar3 = DispatchGameStateEventIfLocalizedPromptAccepted(0x6c6f6164), cVar3 != '\0')) {
    uVar4 = (*this->vftable[0xb].GetTEventHandlerClassNamePointer)();
    (**(code **)(*(int *)CONCAT31(extraout_var,uVar4) + 0x13c))();
    puVar9 = PTR_DAT_0065ddd4;
    if (*(int *)&g_pLocalizationTable->field_0x44 == 0) {
      puVar9 = PTR_DAT_0065ddd0;
    }
    sVar1 = *(short *)&this->field_0x92;
    CString::CString(aCStack_14);
    uStack_4 = 0;
    BuildSavePathStringForMode(aCStack_14,(int)sVar1,puVar9);
    cVar3 = TryGetFileMetadataForPath(aCStack_14);
    if (cVar3 != '\0') {
      SetLoadedTagOnLocalizationEntryIfPresent(aCStack_14);
    }
    goto LAB_0056d4d7;
  }
  ResetDualAudioCuePools();
  PushCueToDualAudioCuePools(2);
  PushCueToDualAudioCuePools(3);
  SelectAndScheduleRandomAudioCue();
LAB_0056d50c:
  *unaff_FS_OFFSET = uStack_c;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00578C10
// GHIDRA_NAME TLoadSavePicture::RasterizeHexNeighborTerrainPaletteMap
// GHIDRA_PROTO undefined __thiscall TLoadSavePicture::RasterizeHexNeighborTerrainPaletteMap(int param_1)

void __thiscall
TLoadSavePicture::RasterizeHexNeighborTerrainPaletteMap(TLoadSavePicture *this,int param_1)

{
  uint uVar1;
  uint uVar2;
  uint uVar3;
  undefined1 uVar4;
  undefined4 uVar5;
  int *piVar6;
  short *psVar7;
  short sVar8;
  int iVar9;
  uint uVar10;
  int iVar11;
  int iVar12;
  int local_20;
  uint local_1c;
  int local_18;
  int local_14;
  short local_10 [4];
  short local_8;
  short local_6;
  short local_4;
  
  uVar5 = GetSurfaceObjectAtContextOffset24(*(undefined4 *)&this->field_0x60);
  local_18 = GetSurfaceHeaderFromSurfaceObject(uVar5);
  piVar6 = (int *)GetSurfaceObjectAtContextOffset24(*(undefined4 *)&this->field_0x60);
  uVar10 = *(ushort *)(*piVar6 + 4) & 0x3fff;
  local_14 = 0;
  do {
    iVar9 = local_14;
    SplitTileIndexToHexRasterColumnX2AndRow(local_14,&local_20,&local_1c);
    uVar1 = local_1c & 1;
    uVar2 = local_1c & 1;
    uVar3 = local_1c & 1;
    local_20 = ((short)local_20 * 3) / 2;
    local_1c = local_1c * 3;
    ComputeHexNeighborTileIndices((short)iVar9,local_10,'\x01');
    local_4 = (short)iVar9;
    if (param_1 == 0) {
      psVar7 = local_10;
      iVar9 = 7;
      do {
        if (*psVar7 == -1) {
          sVar8 = -1;
        }
        else {
          sVar8 = (short)*(char *)(*(int *)&g_pGlobalMapState->field_0xc + 4 + *psVar7 * 0x24);
        }
        *psVar7 = sVar8;
        psVar7 = psVar7 + 1;
        iVar9 = iVar9 + -1;
      } while (iVar9 != 0);
    }
    else {
      psVar7 = local_10;
      iVar9 = 7;
      do {
        if (*psVar7 == -1) {
          sVar8 = -1;
        }
        else {
          sVar8 = (short)*(char *)(param_1 + *psVar7);
        }
        *psVar7 = sVar8;
        psVar7 = psVar7 + 1;
        iVar9 = iVar9 + -1;
      } while (iVar9 != 0);
    }
    psVar7 = local_10;
    iVar9 = 7;
    do {
      sVar8 = *psVar7;
      if (0x16 < sVar8) {
        sVar8 = -1;
      }
      *psVar7 = sVar8;
      psVar7 = psVar7 + 1;
      iVar9 = iVar9 + -1;
    } while (iVar9 != 0);
    if (local_4 == local_6) {
      iVar9 = (int)local_4;
    }
    else if (((uVar1 == 0) || (local_6 != local_8)) &&
            ((uVar2 != 0 || ((local_6 != local_10[0] || (local_8 != local_10[0])))))) {
      iVar9 = -2;
    }
    else {
      iVar9 = (int)local_6;
    }
    iVar12 = (int)(short)local_20;
    iVar11 = (int)(short)local_1c;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)(iVar11 * uVar10 + iVar12 + local_18) = uVar4;
    if (uVar3 == 0) {
      if ((local_4 == local_10[0]) || (local_4 == local_6)) {
        iVar9 = (int)local_4;
      }
      else {
        iVar9 = -2;
      }
      iVar12 = (int)(short)local_20;
      iVar11 = (int)(short)local_1c;
      if ((6 < iVar9) && (iVar9 < 0x17)) {
        iVar9 = 0xb;
      }
      if (iVar9 == -1) {
        uVar4 = 0x10;
      }
      else if (iVar9 == -2) {
        uVar4 = 0;
      }
      else {
        uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
      }
      *(undefined1 *)(iVar11 * uVar10 + iVar12 + 1 + local_18) = uVar4;
      iVar9 = (int)local_4;
      if (local_4 != local_10[0]) {
        iVar9 = -2;
      }
      iVar11 = (int)(short)local_1c;
      iVar12 = (short)local_20 + 2;
      if ((6 < iVar9) && (iVar9 < 0x17)) {
        iVar9 = 0xb;
      }
      if (iVar9 == -1) {
        uVar4 = 0x10;
      }
      else {
        if (iVar9 != -2) goto LAB_00578f07;
        uVar4 = 0;
      }
    }
    else {
      iVar9 = (int)local_4;
      if (local_4 != local_6) {
        iVar9 = -2;
      }
      iVar12 = (int)(short)local_20;
      iVar11 = (int)(short)local_1c;
      if ((6 < iVar9) && (iVar9 < 0x17)) {
        iVar9 = 0xb;
      }
      if (iVar9 == -1) {
        uVar4 = 0x10;
      }
      else if (iVar9 == -2) {
        uVar4 = 0;
      }
      else {
        uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
      }
      *(undefined1 *)(iVar11 * uVar10 + iVar12 + 1 + local_18) = uVar4;
      if ((local_4 == local_10[0]) || ((local_4 == local_10[1] && (local_4 == local_6)))) {
        iVar9 = (int)local_4;
      }
      else {
        iVar9 = -2;
      }
      iVar11 = (int)(short)local_1c;
      iVar12 = (short)local_20 + 2;
      if ((6 < iVar9) && (iVar9 < 0x17)) {
        iVar9 = 0xb;
      }
      if (iVar9 == -1) {
        uVar4 = 0x10;
      }
      else if (iVar9 == -2) {
        uVar4 = 0;
      }
      else {
LAB_00578f07:
        uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
      }
    }
    *(undefined1 *)(iVar11 * uVar10 + iVar12 + local_18) = uVar4;
    iVar9 = (int)local_4;
    if (local_4 != local_8) {
      iVar9 = -2;
    }
    iVar11 = (int)(short)local_1c;
    iVar12 = (int)(short)local_20;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 1) * uVar10 + iVar12 + local_18) = uVar4;
    iVar9 = (int)local_4;
    if (local_4 != local_8) {
      iVar9 = -2;
    }
    iVar11 = (int)(short)local_1c;
    iVar12 = (int)(short)local_20;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 2) * uVar10 + iVar12 + local_18) = uVar4;
    iVar12 = (int)(short)local_20;
    iVar11 = (int)(short)local_1c;
    iVar9 = (int)local_4;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 1) * uVar10 + iVar12 + 1 + local_18) = uVar4;
    iVar12 = (int)(short)local_20;
    iVar11 = (int)(short)local_1c;
    iVar9 = (int)local_4;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 2) * uVar10 + iVar12 + 1 + local_18) = uVar4;
    iVar12 = (int)(short)local_20;
    iVar11 = (int)(short)local_1c;
    iVar9 = (int)local_4;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 1) * uVar10 + iVar12 + 2 + local_18) = uVar4;
    iVar12 = (int)(short)local_20;
    iVar11 = (int)(short)local_1c;
    iVar9 = (int)local_4;
    if ((6 < iVar9) && (iVar9 < 0x17)) {
      iVar9 = 0xb;
    }
    if (iVar9 == -1) {
      uVar4 = 0x10;
    }
    else if (iVar9 == -2) {
      uVar4 = 0;
    }
    else {
      uVar4 = UiRuntimeContext::MapTurnEventCodeToPaletteIndex(iVar9);
    }
    *(undefined1 *)((iVar11 + 2) * uVar10 + iVar12 + 2 + local_18) = uVar4;
    local_14 = local_14 + 1;
    if (0x194f < local_14) {
      return;
    }
  } while( true );
}

