// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TMilitaryUnit.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005C2CB0
// GHIDRA_NAME TMilitaryUnit::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TMilitaryUnit::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  CString local_14;
  undefined4 *local_10;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_006398e5;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x44);
  if (puVar1 != (undefined4 *)0x0) {
    *puVar1 = &TUnit::_vftable_;
    puVar1[4] = 0;
    puVar1[5] = 0;
    *(undefined2 *)((int)puVar1 + 6) = 0xffff;
    *(undefined1 *)(puVar1 + 7) = 0;
    local_4._0_1_ = 1;
    local_4._1_3_ = 0;
    local_10 = puVar1;
    CString::CString((CString *)(puVar1 + 9));
    local_4._0_1_ = 2;
    *(undefined2 *)(puVar1 + 0xe) = 0;
    *(undefined2 *)((int)puVar1 + 0x3a) = 0;
    *(undefined2 *)(puVar1 + 0xf) = 0;
    puVar1[0x10] = 0;
    *puVar1 = &TMilitaryUnitOrderState::_vftable_;
    *(undefined1 *)(puVar1 + 7) = 1;
    *(undefined2 *)(puVar1 + 0xd) = 500;
    *(undefined2 *)((int)puVar1 + 0x36) = 0;
    CString::CString(&local_14,(char *)&g_szEmptyString);
    local_4._0_1_ = 3;
    CString::operator=((CString *)(puVar1 + 9),&local_14);
    local_4 = CONCAT31(local_4._1_3_,2);
    CString::~CString(&local_14);
    *unaff_FS_OFFSET = local_c;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005C2DD0
// GHIDRA_NAME TMilitaryUnit::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TMilitaryUnit::GetRuntimeClass()

{
  return &classRuntimeClass;
}

