// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TMiniArmyLine.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004022F2
// GHIDRA_NAME TMiniArmyLine::thunk_ConstructTMiniArmyLineBaseState
// GHIDRA_PROTO void * __thiscall thunk_ConstructTMiniArmyLineBaseState(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to Cluster_TurnStateHint_004aa960 [FID:thunk_target_sync]
// GHIDRA_COMMENT_END

/* Single-JMP thunk to Cluster_TurnStateHint_004aa960 [FID:thunk_target_sync] */

void * __thiscall TMiniArmyLine::thunk_ConstructTMiniArmyLineBaseState(TMiniArmyLine *this)

{
  void *pvVar1;
  
  pvVar1 = ConstructTMiniArmyLineBaseState(this);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00405F33
// GHIDRA_NAME TMiniArmyLine::thunk_GetTMiniArmyLineClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetTMiniArmyLineClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTMiniArmyLineClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTMiniArmyLineClassNamePointer */

void * __cdecl TMiniArmyLine::thunk_GetTMiniArmyLineClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetTMiniArmyLineClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00408AB7
// GHIDRA_NAME TMiniArmyLine::thunk_DestructTMiniArmyLineAndMaybeFree
// GHIDRA_PROTO void * __thiscall thunk_DestructTMiniArmyLineAndMaybeFree(byte freeSelfFlag)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to DestructTMiniArmyLineAndMaybeFree
// GHIDRA_COMMENT_END

/* Single-JMP thunk to DestructTMiniArmyLineAndMaybeFree */

void * __thiscall
TMiniArmyLine::thunk_DestructTMiniArmyLineAndMaybeFree(TMiniArmyLine *this,byte freeSelfFlag)

{
  void *pvVar1;
  
  pvVar1 = DestructTMiniArmyLineAndMaybeFree(this,freeSelfFlag);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004AA890
// GHIDRA_NAME TMiniArmyLine::CreateTMiniArmyLineInstance
// GHIDRA_PROTO void * __cdecl CreateTMiniArmyLineInstance(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [ClassQuad] create inferred for TMiniArmyLine; alloc factory pattern.
// GHIDRA_COMMENT_END

/* [ClassQuad] create inferred for TMiniArmyLine; alloc factory pattern. */

void * __cdecl TMiniArmyLine::CreateTMiniArmyLineInstance(void)

{
  TLineData *pThis;
  TLineData *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063050a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  pThis = AllocateWithFallbackHandler();
  local_4 = 0;
  pTVar1 = (TLineData *)0x0;
  if (pThis != (TLineData *)0x0) {
    TLineData::ConstructTLineDataBaseState(pThis);
    pThis->field0_0x0 = &PTR_thunk_GetTMiniArmyLineClassNamePointer_0064d510;
    pTVar1 = pThis;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004AA900
// GHIDRA_NAME TMiniArmyLine::GetTMiniArmyLineClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTMiniArmyLineClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for TMiniArmyLine.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for TMiniArmyLine. */

void * __cdecl TMiniArmyLine::GetTMiniArmyLineClassNamePointer(void)

{
  return &g_pClassDescTMiniArmyLine;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004AA960
// GHIDRA_NAME TMiniArmyLine::ConstructTMiniArmyLineBaseState
// GHIDRA_PROTO void * __thiscall ConstructTMiniArmyLineBaseState(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [ClassLane] TMiniArmyLine initializer constructing line control, assigning base text resources, and conditionally attaching grouped TGWorldButton child.
// GHIDRA_COMMENT_END

/* [ClassLane] TMiniArmyLine initializer constructing line control, assigning base text resources,
   and conditionally attaching grouped TGWorldButton child. */

void * __thiscall TMiniArmyLine::ConstructTMiniArmyLineBaseState(TMiniArmyLine *this)

{
  undefined4 uVar1;
  bool bVar2;
  TControl *pTVar3;
  undefined3 extraout_var;
  int *piVar5;
  void *extraout_EAX;
  short unaff_SI;
  undefined4 *unaff_FS_OFFSET;
  undefined1 **ppuStack_48;
  TControl *pTStack_44;
  undefined1 auStack_34 [4];
  char *pcStack_30;
  int iStack_2c;
  undefined1 **ppuStack_28;
  undefined1 auStack_24 [4];
  TGWorldButton *local_20;
  int local_1c;
  TControl *local_18;
  undefined1 *local_14;
  int *local_10;
  undefined4 local_c;
  undefined1 *puStack_8;
  void *local_4;
  void *pvVar4;
  
  local_4 = (void *)0xffffffff;
  puStack_8 = &LAB_00630564;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  pTStack_44 = (TControl *)0x88;
  ppuStack_48 = (undefined1 **)0x4aa987;
  pTVar3 = AllocateWithFallbackHandler();
  local_4 = (void *)0x0;
  local_18 = pTVar3;
  if (pTVar3 == (TControl *)0x0) {
    pTVar3 = (TControl *)0x0;
  }
  else {
    pTStack_44 = (TControl *)0x4aa9a3;
    TControl::thunk_ConstructUiCommandTagResourceEntryBase(pTVar3);
    (pTVar3->base).pVtable = &PTR_thunk_GetTMiniArmyViewClassNamePointer_0064d550;
  }
  uVar1 = this->field13_0x10;
  pTStack_44 = (TControl *)0x0;
  ppuStack_48 = (undefined1 **)&DAT_00000005;
  local_4 = (void *)0xffffffff;
  thunk_InitializeUiResourceEntryFrameAndParent();
  *(undefined4 *)&pTVar3->field_0x84 = uVar1;
  pTVar3->hasCommandTagResource60 = (void *)0x22;
  pTStack_44 = pTVar3;
  TToolBarCluster::WrapperFor_ConstructSharedStringFromCStrOrResourceId_At004ac370
            ((TToolBarCluster *)&ppuStack_48);
  TToolBarCluster::InitializeAndRunMainRoutine();
  pTStack_44 = (TControl *)0x4aaa05;
  bVar2 = WrapperFor_ResolveEraCapabilityFallbackSlot_At005c3650();
  pvVar4 = (void *)CONCAT31(extraout_var,bVar2);
  if (bVar2) {
    pTStack_44 = (TControl *)0x8c;
    ppuStack_48 = (undefined1 **)0x4aaa17;
    local_20 = AllocateWithFallbackHandler();
    local_4 = (void *)0x1;
    if (local_20 == (TGWorldButton *)0x0) {
      piVar5 = (int *)0x0;
    }
    else {
      pTStack_44 = (TControl *)0x4aaa31;
      piVar5 = TGWorldButton::ConstructTGWorldButtonBaseState(local_20);
    }
    ppuStack_48 = &local_14;
    pTStack_44 = (TControl *)0xdae;
    local_4 = (void *)0xffffffff;
    local_14 = (undefined1 *)0x13;
    local_10 = (int *)0x12;
    local_20 = (TGWorldButton *)0x73;
    local_1c = 0;
    WrapperFor_thunk_InitializeUiResourceEntryFrameAndParent_At005721b0();
    pTStack_44 = (TControl *)0x0;
    ppuStack_48 = (undefined1 **)0x1;
    (**(code **)(*piVar5 + 0xa8))();
    piVar5[7] = 0x75706772;
    InitializeSharedStringRefFromEmpty();
    local_c = 2;
    InitializeSharedStringRefFromEmpty();
    local_c._0_1_ = 3;
    InitializeSharedStringRefFromEmpty();
    local_c._0_1_ = 4;
    InitializeSharedStringRefFromEmpty();
    local_c._0_1_ = 5;
    InitializeSharedStringRefFromEmpty();
    local_c._0_1_ = 6;
    WrapperFor_ResolveEraCapabilityFallbackSlot_At005c3840
              ((int)&stack0xffffffc6,(int)&local_4,(int)&stack0xffffffc4,(int)&stack0x00000000);
    FormatStringWithVarArgsToSharedRef();
    (**(code **)(*(int *)g_pLocalizationTable + 0x74))((int)unaff_SI,auStack_34);
    if ((short)puStack_8 == 0) {
      (**(code **)(*(int *)g_pLocalizationTable + 0x84))(&DAT_00002746,2,&stack0xffffffc0);
      pTStack_44 = (TControl *)iStack_2c;
      ppuStack_48 = ppuStack_28;
      scanBracketExpressions(g_pLocalizationTable,auStack_24,pcStack_30);
    }
    else {
      InitializeSharedStringRefFromEmpty();
      local_14 = (undefined1 *)CONCAT31(local_14._1_3_,7);
      FormatStringWithVarArgsToSharedRef();
      (**(code **)(*(int *)g_pLocalizationTable + 0x84))(&DAT_00002746,6,&stack0xffffffc0);
      pTStack_44 = (TControl *)iStack_2c;
      ppuStack_48 = (undefined1 **)local_20;
      scanBracketExpressions(g_pLocalizationTable,auStack_24,pcStack_30);
      local_4 = (void *)CONCAT31(local_4._1_3_,6);
      pTStack_44 = (TControl *)0x4aabda;
      ReleaseSharedStringRefIfNotEmpty();
    }
    local_14 = (undefined1 *)&ppuStack_48;
    pTStack_44 = (TControl *)piVar5;
    thunk_AssignStringSharedRefAndReturnThis();
    TToolBarCluster::InitializeAndRunMainRoutine();
    local_4._0_1_ = 5;
    pTStack_44 = (TControl *)0x4aac02;
    ReleaseSharedStringRefIfNotEmpty();
    local_4._0_1_ = 4;
    pTStack_44 = (TControl *)0x4aac10;
    ReleaseSharedStringRefIfNotEmpty();
    local_4._0_1_ = 3;
    pTStack_44 = (TControl *)0x4aac1e;
    ReleaseSharedStringRefIfNotEmpty();
    local_4 = (void *)CONCAT31(local_4._1_3_,2);
    pTStack_44 = (TControl *)0x4aac2c;
    ReleaseSharedStringRefIfNotEmpty();
    local_4 = (void *)0xffffffff;
    pTStack_44 = (TControl *)0x4aac3d;
    ReleaseSharedStringRefIfNotEmpty();
    pvVar4 = extraout_EAX;
  }
  *unaff_FS_OFFSET = local_c;
  return pvVar4;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004AAD40
// GHIDRA_NAME TMiniArmyLine::DestructTMiniArmyLineAndMaybeFree
// GHIDRA_PROTO void * __thiscall DestructTMiniArmyLineAndMaybeFree(byte freeSelfFlag)

void * __thiscall
TMiniArmyLine::DestructTMiniArmyLineAndMaybeFree(TMiniArmyLine *this,byte freeSelfFlag)

{
  TView::thunk_DestructTViewBaseState((TView *)this);
  if ((freeSelfFlag & 1) != 0) {
    FreeHeapBufferIfNotNull();
  }
  return this;
}

