// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TMultiMessagePicture.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x0044FA80
// GHIDRA_NAME TMultiMessagePicture::WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80
// GHIDRA_PROTO undefined __thiscall TMultiMessagePicture::WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80(void)

TMultiMessagePicture * __thiscall
TMultiMessagePicture::WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80
          (TMultiMessagePicture *this)

{
  thunk_TPictureButton::TPictureButton((thunk_TPictureButton *)this);
  this->vftable = &TMultiMessagePictureVtbl_00643818;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0044FB10
// GHIDRA_NAME TMultiMessagePicture::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TMultiMessagePicture * TMultiMessagePicture::_scalar_deleting_destructor_(byte param_1)

{
  TView::DestructCityDialogSharedBaseState((TView *)this);
  if ((param_1 & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0054ECA0
// GHIDRA_NAME TMultiMessagePicture::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall TSoundPlayer::GetTEventHandlerClassNamePointer(void)

CRuntimeClass * TMultiMessagePicture::GetTEventHandlerClassNamePointer()

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0054ECC0
// GHIDRA_NAME TMultiMessagePicture::ReleaseRuntimeSelectionOwnerAndDestroyObject
// GHIDRA_PROTO undefined __thiscall TEventHandler::ReleaseRuntimeSelectionOwnerAndDestroyObject(CString param_1, CString param_2, TMultiMessagePicture_slot_0x04_0x04 * param_3)

void __thiscall
TMultiMessagePicture::ReleaseRuntimeSelectionOwnerAndDestroyObject
          (TMultiMessagePicture *this,CString param_1,CString param_2,
          TMultiMessagePicture_slot_0x04_0x04 *param_3)

{
  _vslot_fn *p_Var1;
  int iVar2;
  TApplicationVtbl *pTVar3;
  undefined uVar4;
  char cVar5;
  undefined3 extraout_var;
  undefined3 extraout_var_00;
  undefined4 uVar6;
  int iVar7;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 uStack_4;
  
  local_c = *unaff_FS_OFFSET;
  uStack_4 = 0xffffffff;
  puStack_8 = &LAB_00634fc8;
  *unaff_FS_OFFSET = &local_c;
  if (((param_1.m_pchData == (char *)0x14) || (param_1.m_pchData == (char *)0xa)) ||
     (param_1.m_pchData == (char *)0x22)) {
    iVar7 = *(int *)(param_2.m_pchData + 0x1c);
    if ((iVar7 != 0x63616e63) && (iVar7 != 0x636e636c)) {
      if (iVar7 != 0x6f6b6179) {
        TMapDialog::ReleaseRuntimeSelectionOwnerAndDestroyObject
                  ((TMapDialog *)this,(int)param_1.m_pchData);
        goto LAB_0054edfd;
      }
      p_Var1 = this->vftable->OrphanLeaf_NoCall_Ins07_004d8920_25;
      uVar4 = (*p_Var1)(0x6d657367);
      iVar7 = *(int *)CONCAT31(extraout_var,uVar4);
      (**(code **)(iVar7 + 0xc))();
      CString::CString(&param_1);
      puStack_8 = (undefined1 *)0x0;
      (**(code **)(iVar7 + 0x1dc))(&param_1);
      iVar7 = 0;
      param_1.m_pchData = (char *)0x0;
      do {
        uVar4 = (*p_Var1)(iVar7 + 0x626f7830);
        iVar2 = *(int *)CONCAT31(extraout_var_00,uVar4);
        (**(code **)(iVar2 + 0xc))();
        cVar5 = (**(code **)(iVar2 + 0x28))();
        if ((cVar5 != '\0') && (cVar5 = (**(code **)(iVar2 + 0x1d0))(), cVar5 != '\0')) {
          param_1.m_pchData = param_1.m_pchData | 1 << ((byte)iVar7 & 0x1f);
        }
        iVar7 = iVar7 + 1;
      } while (iVar7 < 7);
      uVar6 = FindActiveNationSlotIndexInGameFlowList();
      CreateAndSendTurnEvent0C_Text256AndTwoFlags(&param_2,param_1.m_pchData,uVar6);
      uStack_4 = 0xffffffff;
      CString::~CString(&param_2);
    }
    pTVar3 = g_pGlobalUiRootController->vftable;
    uVar4 = (*this->vftable->SetForeignMinisterReadyFlag14)();
    (**(code **)&pTVar3->field_0xb4)(uVar4);
  }
LAB_0054edfd:
  *unaff_FS_OFFSET = local_c;
  return;
}

