// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TNavyMgr.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00556530
// GHIDRA_NAME TNavyMgr::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TNavyMgr::CreateObject(void)

{
  undefined4 *puVar1;
  
  puVar1 = (undefined4 *)operator_new(0x10);
  if (puVar1 != (undefined4 *)0x0) {
    *puVar1 = &_vftable_;
    puVar1[1] = 0;
    *(undefined2 *)(puVar1 + 2) = 0xffff;
    puVar1[3] = 0;
    return puVar1;
  }
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00556570
// GHIDRA_NAME TNavyMgr::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * TNavyMgr::GetRuntimeClass()

{
  return &classTNavyMgr;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005565C0
// GHIDRA_NAME TNavyMgr::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TNavyMgr * TNavyMgr::_scalar_deleting_destructor_(byte param_1)

{
  func_0x00401dcf();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005567A0
// GHIDRA_NAME TNavyMgr::Free
// GHIDRA_PROTO undefined __thiscall Free(void)

void TNavyMgr::Free()

{
  int *piVar1;
  
  while (g_pNavyPrimaryOrderListHead != (TShip *)0x0) {
    (*g_pNavyPrimaryOrderListHead->vftable[3].DestructTShipAndFreeIfOwned)();
  }
  g_pNavyPrimaryOrderListHead = (TShip *)0x0;
  while (g_pNavySecondaryOrderListHead != (int *)0x0) {
    (**(code **)(*g_pNavySecondaryOrderListHead + 0x1c))();
  }
  piVar1 = *(int **)&this->field_0x4;
  if (piVar1 != (int *)0x0) {
    func_0x00406d16();
    (**(code **)(*piVar1 + 0x1c))();
  }
  if (this != (TNavyMgr *)0x0) {
    (*this->vftable->~TNavyMgr)(1);
  }
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005568C0
// GHIDRA_NAME TNavyMgr::WriteTo
// GHIDRA_PROTO undefined __thiscall WriteTo(undefined4 param_1)

void TNavyMgr::WriteTo(undefined4 param_1)

{
  func_0x0040583a(param_1);
  func_0x00403940(param_1,0xffffffff);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00556AA0
// GHIDRA_NAME TNavyMgr::ReadFrom
// GHIDRA_PROTO undefined __thiscall ReadFrom(undefined4 param_1)

void TNavyMgr::ReadFrom(undefined4 param_1)

{
  func_0x00403517(param_1);
  func_0x0040774d(param_1,0xffffffff);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00557080
// GHIDRA_NAME TNavyMgr::MoveMapOrderEntryToQueueHeadIfValid
// GHIDRA_PROTO undefined MoveMapOrderEntryToQueueHeadIfValid()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Ensures a map-order entry is queued in the global order list (manager+0x04).
// GHIDRA_COMMENT If the entry has no children, it is discarded via vfunc +0x1C.
// GHIDRA_COMMENT Otherwise, the entry is detached from its previous queue position and moved to queue head.
// GHIDRA_COMMENT_END

/* Ensures a map-order entry is queued in the global order list (manager+0x04).
   If the entry has no children, it is discarded via vfunc +0x1C.
   Otherwise, the entry is detached from its previous queue position and moved to queue head. */

uint __thiscall TNavyMgr::MoveMapOrderEntryToQueueHeadIfValid(int param_1,int *param_2)

{
  int *piVar1;
  int iVar2;
  uint uVar3;
  int *piVar4;
  short sVar5;
  
  piVar1 = *(int **)(param_1 + 4);
  for (piVar4 = piVar1; piVar4 != (int *)0x0; piVar4 = (int *)piVar4[0xb]) {
    if (piVar4 == param_2) goto LAB_005570f4;
  }
  if (param_2 == (int *)0x0) {
    sVar5 = 0;
  }
  else {
    sVar5 = 0;
    for (iVar2 = param_2[4]; iVar2 != 0; iVar2 = *(int *)(iVar2 + 4)) {
      sVar5 = sVar5 + 1;
    }
  }
  if (sVar5 < 1) {
    uVar3 = (**(code **)(*param_2 + 0x1c))();
    return uVar3 & 0xffffff00;
  }
  if (param_2[10] != 0) {
    *(int *)(param_2[10] + 0x2c) = param_2[0xb];
  }
  piVar4 = (int *)param_2[0xb];
  if (piVar4 != (int *)0x0) {
    piVar4[10] = param_2[10];
  }
  param_2[10] = 0;
  param_2[0xb] = (int)piVar1;
  if (piVar1 != (int *)0x0) {
    piVar1[10] = (int)param_2;
  }
  *(int **)(param_1 + 4) = param_2;
LAB_005570f4:
  return CONCAT31((int3)((uint)piVar4 >> 8),1);
}

