// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TNextMoveCommand.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005A64D0
// GHIDRA_NAME TNextMoveCommand::CreateObject
// GHIDRA_PROTO undefined CreateObject()

undefined4 * TNextMoveCommand::CreateObject(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063873a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)operator_new(0x1c);
  local_4 = 0;
  puVar2 = (undefined4 *)0x0;
  if (puVar1 != (undefined4 *)0x0) {
    func_0x00403d5f();
    *puVar1 = &_vftable_;
    puVar2 = puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return puVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005A6540
// GHIDRA_NAME TNextMoveCommand::GetRuntimeClass
// GHIDRA_PROTO undefined __thiscall GetRuntimeClass(void)

CRuntimeClass * __thiscall TNextMoveCommand::GetRuntimeClass(TNextMoveCommand *this)

{
  return &classTNextMoveCommand;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005A6560
// GHIDRA_NAME TNextMoveCommand::ConstructTNextMoveCommandBaseState
// GHIDRA_PROTO undefined __thiscall ConstructTNextMoveCommandBaseState(void)

TNextMoveCommand * __thiscall
TNextMoveCommand::ConstructTNextMoveCommandBaseState(TNextMoveCommand *this)

{
  func_0x00403d5f();
  this->vftable = &_vftable_;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005A6590
// GHIDRA_NAME TNextMoveCommand::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TNextMoveCommand * __thiscall
TNextMoveCommand::_scalar_deleting_destructor_(TNextMoveCommand *this,byte param_1)

{
  func_0x0040312f();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005A6620
// GHIDRA_NAME TNextMoveCommand::DoIt
// GHIDRA_PROTO undefined __thiscall DoIt(void)

void __thiscall TNextMoveCommand::DoIt(TNextMoveCommand *this)

{
  int *piVar1;
  bool bVar2;
  
  piVar1 = *(int **)&this->field_0x18;
  if (piVar1 == (int *)g_pMapContextActionManager[0xe9]) {
    if (piVar1[0x11] != 0) {
      bVar2 = piVar1[0x11] == 1;
      (**(code **)(*(int *)piVar1[5] + 0x34))(bVar2);
      (**(code **)(*(int *)piVar1[6] + 0x34))(!bVar2);
      (**(code **)(*piVar1 + 0x48))(bVar2);
      return;
    }
    *(undefined1 *)(piVar1 + 0x12) = 1;
    func_0x00404700();
  }
  return;
}

