// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TNoHiliteText.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005B6960
// GHIDRA_NAME TNoHiliteText::CreateTNoHiliteTextInstance
// GHIDRA_PROTO undefined CreateTNoHiliteTextInstance()

TStaticText * TNoHiliteText::CreateTNoHiliteTextInstance(void)

{
  TStaticText *this;
  TStaticText *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;

  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063905a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (TStaticText *)__2_YAPAXI_Z(0x94);
  local_4 = 0;
  pTVar1 = (TStaticText *)0x0;
  if (this != (TStaticText *)0x0) {
    TStaticText::TStaticText(this);
    this->vftable = (TStaticTextVtbl *)&TNoHiliteTextVtbl_0066d500;
    pTVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B69E0
// GHIDRA_NAME TNoHiliteText::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall TSoundPlayer::GetTEventHandlerClassNamePointer(void)

CRuntimeClass * TNoHiliteText::GetTEventHandlerClassNamePointer()

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B6A00
// GHIDRA_NAME TNoHiliteText::ConstructUiStatusListTextEntry
// GHIDRA_PROTO undefined __thiscall ConstructUiStatusListTextEntry(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Constructs a status-list text entry used by turn-event status row builders and related list text panels.
// GHIDRA_COMMENT
// GHIDRA_COMMENT Algorithm:
// GHIDRA_COMMENT 1. Calls ConstructUiTextResourceEntryBase.
// GHIDRA_COMMENT 2. Installs status-list text vtable.
// GHIDRA_COMMENT
// GHIDRA_COMMENT Returns:
// GHIDRA_COMMENT - this pointer.
// GHIDRA_COMMENT_END

/* Constructs a status-list text entry used by turn-event status row builders and related list text
   panels.

   Algorithm:
   1. Calls ConstructUiTextResourceEntryBase.
   2. Installs status-list text vtable.

   Returns:
   - this pointer. */

TNoHiliteText * TNoHiliteText::ConstructUiStatusListTextEntry()

{
  TStaticText::TStaticText((TStaticText *)this);
  this->vftable = &TNoHiliteTextVtbl_0066d500;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B6A30
// GHIDRA_NAME TNoHiliteText::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TNoHiliteText * TNoHiliteText::_scalar_deleting_destructor_(byte param_1)

{
  TStaticText::~TStaticText((TStaticText *)this);
  if ((param_1 & 1) != 0) {
    __3_YAXPAX_Z(this);
  }
  return this;
}

