// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TPlaceCityDialog.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004D1760
// GHIDRA_NAME TPlaceCityDialog::CreateTPlaceCityDialogInstance
// GHIDRA_PROTO undefined CreateTPlaceCityDialogInstance()

thunk_TPictureButton * TPlaceCityDialog::CreateTPlaceCityDialogInstance(void)

{
  thunk_TPictureButton *this;
  thunk_TPictureButton *ptVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00631b6a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (thunk_TPictureButton *)AllocateWithFallbackHandler(0x94);
  local_4 = 0;
  ptVar1 = (thunk_TPictureButton *)0x0;
  if (this != (thunk_TPictureButton *)0x0) {
    thunk_TPictureButton::TPictureButton(this);
    *(TPlaceCityDialogVtbl **)this = &TPlaceCityDialogVtbl_00652f58;
    ptVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return ptVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004D17E0
// GHIDRA_NAME TPlaceCityDialog::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall GetTEventHandlerClassNamePointer(void)

CRuntimeClass * __thiscall
TPlaceCityDialog::GetTEventHandlerClassNamePointer(TPlaceCityDialog *this)

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004D1800
// GHIDRA_NAME TPlaceCityDialog::ConstructTPlaceCityDialogBaseState
// GHIDRA_PROTO undefined __thiscall ConstructTPlaceCityDialogBaseState(void)

TPlaceCityDialog * __thiscall
TPlaceCityDialog::ConstructTPlaceCityDialogBaseState(TPlaceCityDialog *this)

{
  thunk_TPictureButton::TPictureButton((thunk_TPictureButton *)this);
  this->vftable = &TPlaceCityDialogVtbl_00652f58;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004D1830
// GHIDRA_NAME TPlaceCityDialog::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(byte param_1)

TPlaceCityDialog * __thiscall
TPlaceCityDialog::_scalar_deleting_destructor_(TPlaceCityDialog *this,byte param_1)

{
  TView::thunk_DestructCityDialogSharedBaseState((TView *)this);
  if ((param_1 & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004D1E40
// GHIDRA_NAME TPlaceCityDialog::OrphanTiny_ReturnZero_0048a730
// GHIDRA_PROTO undefined __thiscall OrphanTiny_ReturnZero_0048a730(void)

void __thiscall TPlaceCityDialog::OrphanTiny_ReturnZero_0048a730(TPlaceCityDialog *this)

{
  THQButton::thunk_RenderHintHelperWithCtrlModifierOverlay((THQButton *)this);
  return;
}

