// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TRadioPictureButton.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00571700
// GHIDRA_NAME TRadioPictureButton::CreateTRadioPictureButtonInstance
// GHIDRA_PROTO undefined CreateTRadioPictureButtonInstance()

undefined4 * TRadioPictureButton::CreateTRadioPictureButtonInstance(void)

{
  undefined4 *puVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063642a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)AllocateWithFallbackHandler(0x98);
  local_4 = 0;
  if (puVar1 != (undefined4 *)0x0) {
    thunk_TPictureButton::TPictureButton();
    *(undefined2 *)((int)puVar1 + 0x92) = 7000;
    *puVar1 = &PTR_LAB_0065f670;
    puVar1[0x18] = 0xc;
    *(undefined1 *)(puVar1 + 0x25) = 0;
    *unaff_FS_OFFSET = local_c;
    return puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return (undefined4 *)0x0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005717A0
// GHIDRA_NAME TRadioPictureButton::GetTRadioPictureButtonClassNamePointer
// GHIDRA_PROTO undefined GetTRadioPictureButtonClassNamePointer()

undefined ** TRadioPictureButton::GetTRadioPictureButtonClassNamePointer(void)

{
  return &PTR_s_TRadioPictureButton_0065e5e0;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005717C0
// GHIDRA_NAME TRadioPictureButton::TRadioPictureButton
// GHIDRA_PROTO undefined TRadioPictureButton()
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Clickable picture/icon entry constructor. Derived picture resource class used for civ/agr/command icon slots in multiple UI builders.
// GHIDRA_COMMENT_END

/* Clickable picture/icon entry constructor. Derived picture resource class used for civ/agr/command
   icon slots in multiple UI builders. */

undefined4 * __fastcall TRadioPictureButton::TRadioPictureButton(undefined4 *param_1)

{
  thunk_TPictureButton::TPictureButton();
  *(undefined2 *)((int)param_1 + 0x92) = 7000;
  *param_1 = &PTR_LAB_0065f670;
  param_1[0x18] = 0xc;
  *(undefined1 *)(param_1 + 0x25) = 0;
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00571800
// GHIDRA_NAME TRadioPictureButton::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined 'scalar_deleting_destructor'()

undefined4 __thiscall
TRadioPictureButton::_scalar_deleting_destructor_(undefined4 param_1,byte param_2)

{
  thunk_DestructCityDialogSharedBaseState();
  if ((param_2 & 1) != 0) {
    FreeHeapBufferIfNotNull(param_1);
  }
  return param_1;
}

