// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TShipPlacard.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00403A08
// GHIDRA_NAME TShipPlacard::TShipPlacard_VtblSlot000
// GHIDRA_PROTO void * __cdecl TShipPlacard_VtblSlot000(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTShipPlacardClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTShipPlacardClassNamePointer */

void * __cdecl TShipPlacard::TShipPlacard_VtblSlot000(void)

{
  void *pvVar1;
  
  pvVar1 = GetTShipPlacardClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00404584
// GHIDRA_NAME TShipPlacard::TShipPlacard_VtblSlot068
// GHIDRA_PROTO void __cdecl TShipPlacard_VtblSlot068(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to RenderCenteredPositiveCountLabelAtFixedOrigin
// GHIDRA_COMMENT_END

/* Single-JMP thunk to RenderCenteredPositiveCountLabelAtFixedOrigin */

void __cdecl TShipPlacard::TShipPlacard_VtblSlot068(void)

{
  RenderCenteredPositiveCountLabelAtFixedOrigin();
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0040674E
// GHIDRA_NAME TShipPlacard::TShipPlacard_VtblSlot001
// GHIDRA_PROTO void * __thiscall TShipPlacard_VtblSlot001(byte freeSelfFlag)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to DestructTShipPlacardAndMaybeFree
// GHIDRA_COMMENT_END

/* Single-JMP thunk to DestructTShipPlacardAndMaybeFree */

void * __thiscall TShipPlacard::TShipPlacard_VtblSlot001(TShipPlacard *this,byte freeSelfFlag)

{
  void *pvVar1;
  
  pvVar1 = DestructTShipPlacardAndMaybeFree(this,freeSelfFlag);
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005691D0
// GHIDRA_NAME TShipPlacard::CreateTShipPlacardInstance
// GHIDRA_PROTO void * __cdecl CreateTShipPlacardInstance(void)

void * __cdecl TShipPlacard::CreateTShipPlacardInstance(void)

{
  TNoHilitePicture *this;
  TNoHilitePicture *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_00635b5a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = AllocateWithFallbackHandler();
  local_4 = 0;
  pTVar1 = (TNoHilitePicture *)0x0;
  if (this != (TNoHilitePicture *)0x0) {
    TNoHilitePicture::thunk_ConstructPictureResourceEntryType606E8(this);
    this->field0_0x0 = &g_vtblTShipPlacard;
    pTVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00569250
// GHIDRA_NAME TShipPlacard::GetTShipPlacardClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTShipPlacardClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for TShipPlacard.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for TShipPlacard. */

void * __cdecl TShipPlacard::GetTShipPlacardClassNamePointer(void)

{
  return &g_pClassDescTShipPlacard;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00569270
// GHIDRA_NAME TShipPlacard::ConstructTShipPlacardBaseState
// GHIDRA_PROTO void * __thiscall ConstructTShipPlacardBaseState(void)

void * __thiscall TShipPlacard::ConstructTShipPlacardBaseState(TShipPlacard *this)

{
  TNoHilitePicture::thunk_ConstructPictureResourceEntryType606E8((TNoHilitePicture *)this);
  this->field0_0x0 = &g_vtblTShipPlacard;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005692A0
// GHIDRA_NAME TShipPlacard::DestructTShipPlacardAndMaybeFree
// GHIDRA_PROTO void * __thiscall DestructTShipPlacardAndMaybeFree(byte freeSelfFlag)

void * __thiscall
TShipPlacard::DestructTShipPlacardAndMaybeFree(TShipPlacard *this,byte freeSelfFlag)

{
  thunk_DestructCityDialogSharedBaseState();
  if ((freeSelfFlag & 1) != 0) {
    FreeHeapBufferIfNotNull();
  }
  return this;
}

