// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TTechStorePage.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005B0E70
// GHIDRA_NAME TTechStorePage::CreateTTechStorePageInstance
// GHIDRA_PROTO undefined CreateTTechStorePageInstance()

undefined4 * TTechStorePage::CreateTTechStorePageInstance(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063897a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  puVar1 = (undefined4 *)AllocateWithFallbackHandler(0x84);
  local_4 = 0;
  puVar2 = (undefined4 *)0x0;
  if (puVar1 != (undefined4 *)0x0) {
    TPageView::ConstructTPageViewBaseState();
    *puVar1 = &PTR_LAB_00645ca8;
    puVar2 = puVar1;
  }
  *unaff_FS_OFFSET = local_c;
  return puVar2;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B0EF0
// GHIDRA_NAME TTechStorePage::GetTTechStorePageClassNamePointer
// GHIDRA_PROTO undefined GetTTechStorePageClassNamePointer()

undefined ** TTechStorePage::GetTTechStorePageClassNamePointer(void)

{
  return &PTR_s_TTechStorePage_0066ae10;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B0F10
// GHIDRA_NAME TTechStorePage::ConstructTTechStorePageBaseState
// GHIDRA_PROTO undefined ConstructTTechStorePageBaseState()

void __thiscall TTechStorePage::ConstructTTechStorePageBaseState(int *param_1,undefined4 param_2)

{
  int iVar1;
  undefined4 *puVar2;
  int iVar3;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_14;
  undefined4 local_10;
  undefined4 uStack_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  uStack_c = *unaff_FS_OFFSET;
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063899a;
  *unaff_FS_OFFSET = &uStack_c;
  iVar3 = 0x1c;
  do {
    if (*(char *)((short)iVar3 + 0x180 + (int)g_pCityOrderCapabilityState) != '\0') {
      puVar2 = (undefined4 *)AllocateWithFallbackHandler(0x18);
      local_4 = 0;
      if (puVar2 == (undefined4 *)0x0) {
        puVar2 = (undefined4 *)0x0;
      }
      else {
        TLineData::ConstructTLineDataBaseState();
        *puVar2 = &PTR_LAB_0066aec8;
      }
      local_4 = 0xffffffff;
      local_14 = 0x232;
      local_10 = 0x3f;
      TLineData::SetLineDataRowAndBounds(0,0,&local_14);
      iVar1 = *param_1;
      puVar2[4] = param_2;
      puVar2[5] = iVar3;
      (**(code **)(iVar1 + 0x1a0))(puVar2);
    }
    iVar3 = iVar3 + -1;
  } while (0 < iVar3);
  iVar3 = *param_1;
  (**(code **)(iVar3 + 0x1ac))();
  (**(code **)(iVar3 + 0x1b0))(1);
  UpdatePagedListNavigationButtonState((int)*(short *)((int)param_1 + 0x62));
  InitializeMainRoutineContextAndRun(PTR_g_szEmptyString_0066ae08,param_1[7]);
  *unaff_FS_OFFSET = local_10;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005B1040
// GHIDRA_NAME TTechStorePage::DestructTTechStorePageAndMaybeFree
// GHIDRA_PROTO undefined DestructTTechStorePageAndMaybeFree()

undefined4 __thiscall
TTechStorePage::DestructTTechStorePageAndMaybeFree(undefined4 param_1,byte param_2)

{
  DestructTTechStorePageAndMaybeFree_Impl();
  if ((param_2 & 1) != 0) {
    FreeHeapBufferIfNotNull(param_1);
  }
  return param_1;
}

