// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TTerrainHelpWindow.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00504CA0
// GHIDRA_NAME TTerrainHelpWindow::CreateTTerrainHelpWindowInstance
// GHIDRA_PROTO undefined CreateTTerrainHelpWindowInstance()

TControl * TTerrainHelpWindow::CreateTTerrainHelpWindowInstance(void)

{
  TControl *this;
  TControl *pTVar1;
  undefined4 *unaff_FS_OFFSET;
  undefined4 local_c;
  undefined1 *puStack_8;
  undefined4 local_4;
  
  local_4 = 0xffffffff;
  puStack_8 = &LAB_0063368a;
  local_c = *unaff_FS_OFFSET;
  *unaff_FS_OFFSET = &local_c;
  this = (TControl *)AllocateWithFallbackHandler(0xa0);
  local_4 = 0;
  pTVar1 = (TControl *)0x0;
  if (this != (TControl *)0x0) {
    TControl::thunk_ConstructUiWindowResourceEntryType4B340(this);
    this->vftable = (TControlVtbl *)&TTerrainHelpWindowVtbl_00657500;
    pTVar1 = this;
  }
  *unaff_FS_OFFSET = local_c;
  return pTVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00504D20
// GHIDRA_NAME TTerrainHelpWindow::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall GetTEventHandlerClassNamePointer(void)

CRuntimeClass * __thiscall
TTerrainHelpWindow::GetTEventHandlerClassNamePointer(TTerrainHelpWindow *this)

{
  return &classRuntimeClass;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00504D40
// GHIDRA_NAME TTerrainHelpWindow::ConstructTTerrainHelpWindowBaseState
// GHIDRA_PROTO undefined __thiscall ConstructTTerrainHelpWindowBaseState(void)

TTerrainHelpWindow * __thiscall
TTerrainHelpWindow::ConstructTTerrainHelpWindowBaseState(TTerrainHelpWindow *this)

{
  TControl::thunk_ConstructUiWindowResourceEntryType4B340((TControl *)this);
  this->vftable = &TTerrainHelpWindowVtbl_00657500;
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00504D70
// GHIDRA_NAME TTerrainHelpWindow::'scalar_deleting_destructor'
// GHIDRA_PROTO undefined __thiscall 'scalar_deleting_destructor'(void)

TTerrainHelpWindow * __thiscall
TTerrainHelpWindow::_scalar_deleting_destructor_(TTerrainHelpWindow *this)

{
  byte in_stack_00000004;
  
  TView::DestructTWindowViewAndUnlinkGlobalLists((TView *)this);
  if ((in_stack_00000004 & 1) != 0) {
    FreeHeapBufferIfNotNull(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00504DC0
// GHIDRA_NAME TTerrainHelpWindow::GetTEventHandlerClassNamePointer
// GHIDRA_PROTO undefined __thiscall GetTEventHandlerClassNamePointer(void)

void __thiscall TTerrainHelpWindow::GetTEventHandlerClassNamePointer(TTerrainHelpWindow *this)

{
  TFloatWindow::GetTEventHandlerClassNamePointer((TFloatWindow *)this);
  *(undefined4 *)(DAT_006a21b8 + 0xc) = 0;
  return;
}

