// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TTooltipRelayWindowState.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x005E5EEE
// GHIDRA_NAME TTooltipRelayWindowState::CListCtrl::OnChildNotify
// GHIDRA_PROTO undefined CListCtrl::OnChildNotify()

undefined4 __thiscall
TTooltipRelayWindowState::CListCtrl__OnChildNotify
          (int *param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5)

{
  undefined4 uVar1;
  
  if (param_2 == 0x2b) {
    (**(code **)(*param_1 + 0xc0))(param_4);
    uVar1 = 1;
  }
  else {
    uVar1 = CWnd__OnChildNotify(param_2,param_3,param_4,param_5);
  }
  return uVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E663C
// GHIDRA_NAME TTooltipRelayWindowState::CListCtrl::OnChildNotify
// GHIDRA_PROTO undefined CListCtrl::OnChildNotify()

undefined4 __thiscall
TTooltipRelayWindowState::CListCtrl__OnChildNotify
          (int *param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5)

{
  undefined4 uVar1;
  
  if (param_2 == 0x2b) {
    (**(code **)(*param_1 + 0xc0))(param_4);
    uVar1 = 1;
  }
  else {
    uVar1 = CWnd__OnChildNotify(param_2,param_3,param_4,param_5);
  }
  return uVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005E6784
// GHIDRA_NAME TTooltipRelayWindowState::CListCtrl::OnChildNotify
// GHIDRA_PROTO undefined CListCtrl::OnChildNotify()

undefined4 __thiscall
TTooltipRelayWindowState::CListCtrl__OnChildNotify
          (int *param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5)

{
  undefined4 uVar1;
  
  if (param_2 == 0x2b) {
    (**(code **)(*param_1 + 0xc0))(param_4);
    uVar1 = 1;
  }
  else {
    uVar1 = CWnd__OnChildNotify(param_2,param_3,param_4,param_5);
  }
  return uVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005FA87E
// GHIDRA_NAME TTooltipRelayWindowState::??_GCMonikerFile@@UAEPAXI@Z
// GHIDRA_PROTO undefined __thiscall ??_GCMonikerFile@@UAEPAXI@Z(byte param_1)

TTooltipRelayWindowState * TTooltipRelayWindowState::___GCMonikerFile__UAEPAXI_Z(byte param_1)

{
  CToolTipCtrl::~CToolTipCtrl();
  if ((param_1 & 1) != 0) {
    operator_delete(this);
  }
  return this;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00604BA8
// GHIDRA_NAME TTooltipRelayWindowState::CDialog::PreTranslateMessage
// GHIDRA_PROTO undefined __thiscall CDialog::PreTranslateMessage(undefined4 * param_1)

undefined4 __thiscall
TTooltipRelayWindowState::CDialog__PreTranslateMessage
          (TTooltipRelayWindowState *this,undefined4 *param_1)

{
  int iVar1;
  uint uVar2;
  HWND hWnd;
  BOOL BVar3;
  undefined4 uVar4;
  
  iVar1 = CWnd::PreTranslateMessage((CWnd *)this,param_1);
  if (iVar1 == 0) {
    iVar1 = CWnd::GetTopLevelFrame();
    if ((iVar1 != 0) && (*(int *)(iVar1 + 0x50) != 0)) {
      return 0;
    }
    if ((((param_1[1] != 0x100) ||
         (((param_1[2] != 0x1b && (param_1[2] != 3)) ||
          (uVar2 = GetWindowLongA((HWND)*param_1,-0x10), (uVar2 & 4) == 0)))) ||
        (iVar1 = _AfxCompareClassName(*param_1,&DAT_0066fc20), iVar1 == 0)) ||
       ((hWnd = GetDlgItem(*(HWND *)(this + 0x1c),2), hWnd != (HWND)0x0 &&
        (BVar3 = IsWindowEnabled(hWnd), BVar3 == 0)))) {
      uVar4 = CWnd::PreTranslateInput(param_1);
      return uVar4;
    }
    SendMessageA(*(HWND *)(this + 0x1c),0x111,2,0);
  }
  return 1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x0061E87C
// GHIDRA_NAME TTooltipRelayWindowState::CListCtrl::OnChildNotify
// GHIDRA_PROTO undefined CListCtrl::OnChildNotify()

undefined4 __thiscall
TTooltipRelayWindowState::CListCtrl__OnChildNotify
          (int *param_1,int param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5)

{
  undefined4 uVar1;
  
  if (param_2 == 0x2b) {
    (**(code **)(*param_1 + 0xc0))(param_4);
    uVar1 = 1;
  }
  else {
    uVar1 = CWnd__OnChildNotify(param_2,param_3,param_4,param_5);
  }
  return uVar1;
}

