// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TTraderForeignMinister.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x00533880
// GHIDRA_NAME TTraderForeignMinister::GetTTraderForeignMinisterClassNamePointer
// GHIDRA_PROTO undefined GetTTraderForeignMinisterClassNamePointer()

undefined ** TTraderForeignMinister::GetTTraderForeignMinisterClassNamePointer(void)

{
  return &PTR_s_TTraderForeignMinister_00659b10;
}

// GHIDRA_FUNCTION IMPERIALISM 0x005338A0
// GHIDRA_NAME TTraderForeignMinister::ConstructTTraderForeignMinister
// GHIDRA_PROTO undefined ConstructTTraderForeignMinister()

undefined4 * __fastcall TTraderForeignMinister::ConstructTTraderForeignMinister(undefined4 *param_1)

{
  int iVar1;
  undefined4 *puVar2;
  
  *(undefined4 *)((int)param_1 + 0x49) = 0x1010101;
  *(undefined2 *)((int)param_1 + 0x4d) = 0x101;
  *(undefined1 *)((int)param_1 + 0x4f) = 1;
  puVar2 = param_1 + 0x14;
  for (iVar1 = 0xb; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = 0;
    puVar2 = puVar2 + 1;
  }
  *(undefined2 *)puVar2 = 0;
  *(undefined2 *)((int)param_1 + 0x1a) = 5;
  *(undefined2 *)((int)param_1 + 0x16) = 0;
  *(undefined1 *)(param_1 + 0x12) = 0;
  *(undefined2 *)(param_1 + 7) = 2;
  *param_1 = &PTR_LAB_0065a0c8;
  *(undefined2 *)(param_1 + 3) = 1;
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00533910
// GHIDRA_NAME TTraderForeignMinister::DeletingDestructTTraderForeignMinister
// GHIDRA_PROTO undefined DeletingDestructTTraderForeignMinister()

undefined4 __thiscall
TTraderForeignMinister::DeletingDestructTTraderForeignMinister(undefined4 param_1,byte param_2)

{
  DestructTTraderForeignMinister();
  if ((param_2 & 1) != 0) {
    FreeHeapBufferIfNotNull(param_1);
  }
  return param_1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00533940
// GHIDRA_NAME TTraderForeignMinister::DestructTTraderForeignMinister
// GHIDRA_PROTO undefined DestructTTraderForeignMinister()

void __fastcall TTraderForeignMinister::DestructTTraderForeignMinister(undefined4 *param_1)

{
  *param_1 = &PTR_GetCObjectRuntimeClass_RuntimeObjectBaseState_0066FEC4;
  return;
}

