// AUTOGENERATED FROM GHIDRA. DO NOT EDIT.
// Script: SyncExports_Ghidra.py
// Program: Imperialism.exe
// Bucket: TTransFocusAnimation.cpp

// GHIDRA_FUNCTION IMPERIALISM 0x004033B9
// GHIDRA_NAME TTransFocusAnimation::thunk_DestructTTransFocusAnimation
// GHIDRA_PROTO void __thiscall thunk_DestructTTransFocusAnimation(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [Thunk] Direct JMP thunk to DestructTTransFocusAnimation.
// GHIDRA_COMMENT_END

/* [Thunk] Direct JMP thunk to DestructTTransFocusAnimation. */

void __thiscall TTransFocusAnimation::thunk_DestructTTransFocusAnimation(TTransFocusAnimation *this)

{
  DestructTTransFocusAnimationAndMaybeFree(this);
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00403666
// GHIDRA_NAME TTransFocusAnimation::thunk_GetTTransFocusAnimationRuntimeClass
// GHIDRA_PROTO void * __thiscall thunk_GetTTransFocusAnimationRuntimeClass(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Thunk forwarding to GetTTransFocusAnimationRuntimeClass.
// GHIDRA_COMMENT_END

/* Thunk forwarding to GetTTransFocusAnimationRuntimeClass. */

void * __thiscall
TTransFocusAnimation::thunk_GetTTransFocusAnimationRuntimeClass(TTransFocusAnimation *this)

{
  void *in_EAX;
  
  *(undefined ***)this = &PTR_GetCObjectRuntimeClass_0066fec4;
  return in_EAX;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00403D41
// GHIDRA_NAME TTransFocusAnimation::thunk_GetTTransFocusAnimationClassNamePointer
// GHIDRA_PROTO void * __cdecl thunk_GetTTransFocusAnimationClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Single-JMP thunk to GetTTransFocusAnimationClassNamePointer
// GHIDRA_COMMENT_END

/* Single-JMP thunk to GetTTransFocusAnimationClassNamePointer */

void * __cdecl TTransFocusAnimation::thunk_GetTTransFocusAnimationClassNamePointer(void)

{
  void *pvVar1;
  
  pvVar1 = GetTTransFocusAnimationClassNamePointer();
  return pvVar1;
}

// GHIDRA_FUNCTION IMPERIALISM 0x00406799
// GHIDRA_NAME TTransFocusAnimation::thunk_InitializeTransFocusAnimationBoundsAndLoadBitmapSurface
// GHIDRA_PROTO void __cdecl thunk_InitializeTransFocusAnimationBoundsAndLoadBitmapSurface(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Thunk wrapper for InitializeTransFocusAnimationBoundsAndLoadBitmapSurface.
// GHIDRA_COMMENT_END

/* Thunk wrapper for InitializeTransFocusAnimationBoundsAndLoadBitmapSurface. */

void __cdecl
TTransFocusAnimation::thunk_InitializeTransFocusAnimationBoundsAndLoadBitmapSurface(void)

{
  int iVar1;
  void *pvVar2;
  int in_ECX;
  undefined4 in_stack_00000004;
  int *in_stack_00000008;
  undefined2 in_stack_0000000c;
  int in_stack_00000010;
  undefined4 in_stack_00000014;
  undefined4 in_stack_00000018;
  undefined4 uStack_10;
  undefined4 uStack_c;
  int iStack_8;
  int iStack_4;
  
  *(undefined4 *)(in_ECX + 4) = in_stack_00000004;
  *(int *)(in_ECX + 0x1c) = *in_stack_00000008;
  *(int *)(in_ECX + 0x20) = in_stack_00000008[1];
  *(int *)(in_ECX + 0x24) = in_stack_00000008[2];
  iVar1 = in_stack_00000008[3];
  *(short *)(in_ECX + 0xc) = (short)in_stack_00000010;
  *(int *)(in_ECX + 0x28) = iVar1;
  *(undefined2 *)(in_ECX + 10) = in_stack_0000000c;
  *(undefined4 *)(in_ECX + 0x14) = in_stack_00000014;
  *(undefined4 *)(in_ECX + 0x18) = in_stack_00000018;
  *(undefined2 *)(in_ECX + 8) = 0;
  *(undefined4 *)(in_ECX + 0x10) = 0;
  uStack_10 = 0;
  uStack_c = 0;
  iStack_8 = in_stack_00000008[2] - *in_stack_00000008;
  iStack_4 = in_stack_00000008[3] - in_stack_00000008[1];
  (**(code **)(*(int *)g_pDisplayManager + 0x2c))(in_ECX + 0x30,8,&uStack_10);
  pvVar2 = thunk_LoadBitmapResourceSurfaceAndRestoreQuickDrawContext(in_stack_00000010);
  *(void **)(in_ECX + 0x34) = pvVar2;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004A0460
// GHIDRA_NAME TTransFocusAnimation::CreateTTransFocusAnimationInstance
// GHIDRA_PROTO void * __thiscall CreateTTransFocusAnimationInstance(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns TTransFocusAnimation runtime class descriptor pointer.
// GHIDRA_COMMENT_END

/* Returns TTransFocusAnimation runtime class descriptor pointer. */

void * __thiscall
TTransFocusAnimation::CreateTTransFocusAnimationInstance(TTransFocusAnimation *this)

{
  void *in_EAX;
  
  *(undefined ***)this = &PTR_GetCObjectRuntimeClass_0066fec4;
  return in_EAX;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004A0480
// GHIDRA_NAME TTransFocusAnimation::GetTTransFocusAnimationClassNamePointer
// GHIDRA_PROTO void * __cdecl GetTTransFocusAnimationClassNamePointer(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Returns class descriptor pointer for TTransFocusAnimation.
// GHIDRA_COMMENT_END

/* Returns class descriptor pointer for TTransFocusAnimation. */

void * __cdecl TTransFocusAnimation::GetTTransFocusAnimationClassNamePointer(void)

{
  return &g_pClassDescTTransFocusAnimation;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004A04A0
// GHIDRA_NAME TTransFocusAnimation::ConstructTTransFocusAnimationBaseState
// GHIDRA_PROTO void __cdecl ConstructTTransFocusAnimationBaseState(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT Initializes trans-focus animation bounds/rect fields and loads bitmap surface for current resource id.
// GHIDRA_COMMENT_END

/* Initializes trans-focus animation bounds/rect fields and loads bitmap surface for current
   resource id. */

void __cdecl TTransFocusAnimation::ConstructTTransFocusAnimationBaseState(void)

{
  int iVar1;
  void *pvVar2;
  int in_ECX;
  undefined4 in_stack_00000004;
  int *in_stack_00000008;
  undefined2 in_stack_0000000c;
  int in_stack_00000010;
  undefined4 in_stack_00000014;
  undefined4 in_stack_00000018;
  undefined4 local_10;
  undefined4 local_c;
  int local_8;
  int local_4;
  
  *(undefined4 *)(in_ECX + 4) = in_stack_00000004;
  *(int *)(in_ECX + 0x1c) = *in_stack_00000008;
  *(int *)(in_ECX + 0x20) = in_stack_00000008[1];
  *(int *)(in_ECX + 0x24) = in_stack_00000008[2];
  iVar1 = in_stack_00000008[3];
  *(short *)(in_ECX + 0xc) = (short)in_stack_00000010;
  *(int *)(in_ECX + 0x28) = iVar1;
  *(undefined2 *)(in_ECX + 10) = in_stack_0000000c;
  *(undefined4 *)(in_ECX + 0x14) = in_stack_00000014;
  *(undefined4 *)(in_ECX + 0x18) = in_stack_00000018;
  *(undefined2 *)(in_ECX + 8) = 0;
  *(undefined4 *)(in_ECX + 0x10) = 0;
  local_10 = 0;
  local_c = 0;
  local_8 = in_stack_00000008[2] - *in_stack_00000008;
  local_4 = in_stack_00000008[3] - in_stack_00000008[1];
  (**(code **)(*(int *)g_pDisplayManager + 0x2c))(in_ECX + 0x30,8,&local_10);
  pvVar2 = thunk_LoadBitmapResourceSurfaceAndRestoreQuickDrawContext(in_stack_00000010);
  *(void **)(in_ECX + 0x34) = pvVar2;
  return;
}

// GHIDRA_FUNCTION IMPERIALISM 0x004A0570
// GHIDRA_NAME TTransFocusAnimation::DestructTTransFocusAnimationAndMaybeFree
// GHIDRA_PROTO void __thiscall DestructTTransFocusAnimationAndMaybeFree(void)
// GHIDRA_COMMENT_BEGIN
// GHIDRA_COMMENT [ClassMethod] Releases transition focus animation buffers and forwards to base destructor slot.
// GHIDRA_COMMENT_END

/* [ClassMethod] Releases transition focus animation buffers and forwards to base destructor slot.
    */

void __thiscall
TTransFocusAnimation::DestructTTransFocusAnimationAndMaybeFree(TTransFocusAnimation *this)

{
  if (*(int *)(this + 0x30) != 0) {
    WrapperFor_FreeHeapBufferIfNotNull_At004010e6(this + 0x30);
  }
  if (*(int *)(this + 0x34) != 0) {
    WrapperFor_FreeHeapBufferIfNotNull_At004010e6(this + 0x34);
  }
  if (this != (TTransFocusAnimation *)0x0) {
    (**(code **)(*(int *)this + 4))(1);
  }
  return;
}

