#pragma once
// Transitional umbrella over per-subsystem global declarations. New semantic globals
// belong in exactly one owning subsystem header; cross-subsystem state requires a
// narrowly named owner rather than defaulting to shared_globals.h.
#include "game/globals/prelude.h"
#include "game/globals/assets_globals.h"
#include "game/globals/city_globals.h"
#include "game/globals/city_ui_globals.h"
#include "game/globals/core_globals.h"
#include "game/globals/diplomacy_ui_globals.h"
#include "game/globals/gfx_globals.h"
#include "game/globals/map_globals.h"
#include "game/globals/map_ui_globals.h"
#include "game/globals/military_globals.h"
#include "game/globals/military_ui_globals.h"
#include "game/globals/nation_globals.h"
#include "game/globals/navy_globals.h"
#include "game/globals/navy_ui_globals.h"
#include "game/globals/net_globals.h"
#include "game/globals/shared_globals.h"
#include "game/globals/tactical_globals.h"
#include "game/globals/tactical_ui_globals.h"
#include "game/globals/trade_ui_globals.h"
#include "game/globals/ui_core_globals.h"
#include "game/globals/ui_screens_globals.h"
#include "game/globals/ui_widgets_globals.h"
