#pragma once

class TStreamView {
public:
  virtual void ReadRaw00(void* outBuf, int sizeBytes) = 0;
  virtual void dummy1() = 0;
  virtual void dummy2() = 0;
  virtual void dummy3() = 0;
  virtual void dummy4() = 0;
  virtual void dummy5() = 0;
  virtual void dummy6() = 0;
  virtual void dummy7() = 0;
  virtual void dummy8() = 0;
  virtual void dummy9() = 0;
  virtual void dummy10() = 0;
  virtual void dummy11() = 0;
  virtual void dummy12() = 0;
  virtual void dummy13() = 0;
  virtual void dummy14() = 0;
  virtual void ReadAt3C(void* outBuf, int sizeBytes) = 0;
  virtual int ReadInt40() = 0;
  virtual void dummy17() = 0;
  virtual void dummy18() = 0;
  virtual short ReadShort4C() = 0;
  virtual void dummy20() = 0;
  virtual void dummy21() = 0;
  virtual void dummy22() = 0;
  virtual void dummy23() = 0;
  virtual void dummy24() = 0;
  virtual void dummy25() = 0;
  virtual void dummy26() = 0;
  virtual void dummy27() = 0;
  virtual void dummy28() = 0;
  virtual void dummy29() = 0;
  virtual void WriteRaw78(void* data, int sizeBytes) = 0;
  virtual void dummy31() = 0;
  virtual void dummy32() = 0;
  virtual void dummy33() = 0;
  virtual void WriteCount88(int count) = 0;
  virtual void dummy35() = 0;
  virtual void dummy36() = 0;
  virtual void dummy37() = 0;
  virtual void dummy38() = 0;
  virtual void dummy39() = 0;
  virtual void dummy40() = 0;
  virtual void dummy41() = 0;
  virtual void dummy42() = 0;
  virtual void dummy43() = 0;
  virtual char ReadByteB0(void* outByte) = 0;
};
