class: TBatRepDetLine
generated:
  vtable_addr: 0x0064e9d0
  object_size: 0x18
  base: TLineData
  ancestry: [TBatRepDetLine, TLineData, TObject, CObject]
  root: TObject
  slots:
    - {index: 0x00, byte: 0x00, target: 0x004b0020, kind: override, is_thunk: false, is_null: false, ghidra_name: TBatRepDetLine::GetTLineDataClassNamePointer, size: 6, prototype: "undefined GetTLineDataClassNamePointer(void)"}
    - {index: 0x01, byte: 0x04, target: 0x004affd0, kind: override, is_thunk: false, is_null: false, ghidra_name: TBatRepDetLine::WrapperFor_FreeHeapBufferIfNotNull_At004affd0, size: 30, prototype: "undefined WrapperFor_FreeHeapBufferIfNotNull_At004affd0(byte param_1)"}
    - {index: 0x02, byte: 0x08, target: 0x00485e90, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::Serialize, size: 143, prototype: "void Serialize(CArchive * archive)"}
    - {index: 0x03, byte: 0x0c, target: 0x00412bf0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::AssertValid, size: 1, prototype: "void AssertValid(void)"}
    - {index: 0x04, byte: 0x10, target: 0x00412c10, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::Dump, size: 3, prototype: "void Dump(undefined4 dc)"}
    - {index: 0x05, byte: 0x14, target: 0x00485f70, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::WriteTo, size: 3, prototype: "void WriteTo(TStream * stream)"}
    - {index: 0x06, byte: 0x18, target: 0x00485f90, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ReadFrom, size: 3, prototype: "void ReadFrom(TStream * stream)"}
    - {index: 0x07, byte: 0x1c, target: 0x004798b0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::Free, size: 12, prototype: "void Free(void)"}
    - {index: 0x08, byte: 0x20, target: 0x004798d0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ShallowClone, size: 5, prototype: "TObject * ShallowClone(void)"}
    - {index: 0x09, byte: 0x24, target: 0x00415ce0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ShallowFree, size: 47, prototype: "TObject * ShallowFree(void)"}
    - {index: 0x0a, byte: 0x28, target: 0x004b0040, kind: override, is_thunk: false, is_null: false, ghidra_name: TBatRepDetLine::OrphanRetStub_0056f460, size: 1214, prototype: "undefined OrphanRetStub_0056f460(int * param_1, undefined4 param_2)"}
    - {index: 0x0b, byte: 0x2c, target: 0x0056f480, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TLineData::OrphanRetStub_0056f480, size: 1, prototype: "undefined OrphanRetStub_0056f480(void)"}
curated:
