class: TNavyMgr
generated:
  vtable_addr: 0x0065c4c8
  object_size: 0x10
  base: TObject
  ancestry: [TNavyMgr, TObject, CObject]
  root: TObject
  slots:
    - {index: 0x00, byte: 0x00, target: 0x00556570, kind: override, is_thunk: false, is_null: false, ghidra_name: TObject::GetRuntimeClass, size: 6, prototype: "undefined SelectCandidateTilesWithLowGroundUnitCount(void)"}
    - {index: 0x01, byte: 0x04, target: 0x005565c0, kind: scalar_dtor, is_thunk: false, is_null: false, ghidra_name: "TAutoGreatPower::OrphanLeaf_NoCall_Ins07_004d8920 (verify scalar deleting destructor)", size: 30, prototype: "undefined OrphanLeaf_NoCall_Ins07_004d8920(byte param_1)"}
    - {index: 0x02, byte: 0x08, target: 0x00485e90, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::Serialize, size: 143, prototype: "void Serialize(CArchive * archive)"}
    - {index: 0x03, byte: 0x0c, target: 0x00412bf0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::AssertValid, size: 1, prototype: "void AssertValid(void)"}
    - {index: 0x04, byte: 0x10, target: 0x00412c10, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::Dump, size: 3, prototype: "void Dump(undefined4 dc)"}
    - {index: 0x05, byte: 0x14, target: 0x005568c0, kind: override, is_thunk: false, is_null: false, ghidra_name: TObject::WriteTo, size: 29, prototype: "undefined ApplyJoinEmpireMode2FinalizeNationNameState(undefined4 param_1)"}
    - {index: 0x06, byte: 0x18, target: 0x00556aa0, kind: override, is_thunk: false, is_null: false, ghidra_name: TObject::ReadFrom, size: 29, prototype: "undefined IsDiplomacyTargetClassCode200Match(undefined4 param_1)"}
    - {index: 0x07, byte: 0x1c, target: 0x005567a0, kind: override, is_thunk: false, is_null: false, ghidra_name: TObject::Free, size: 92, prototype: "undefined RemoveRegionIdFromNationOwnedRegionList(void)"}
    - {index: 0x08, byte: 0x20, target: 0x004798d0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ShallowClone, size: 5, prototype: "TObject * ShallowClone(void)"}
    - {index: 0x09, byte: 0x24, target: 0x00415ce0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ShallowFree, size: 47, prototype: "TObject * ShallowFree(void)"}
curated:
