class: TShip
generated:
  vtable_addr: 0x0065c438
  object_size: 0x38
  base: TObject
  ancestry: [TShip, TObject, CObject]
  root: TObject
  slots:
    - {index: 0x00, byte: 0x00, target: 0x0054f4e0, kind: new, is_thunk: false, is_null: false, ghidra_name: TShip::GetTShipClassNamePointer, size: 6, prototype: "undefined GetTShipClassNamePointer(void)"}
    - {index: 0x01, byte: 0x04, target: 0x0054f5c0, kind: new, is_thunk: false, is_null: false, ghidra_name: TShip::DestructTShipAndFreeIfOwned, size: 30, prototype: "undefined DestructTShipAndFreeIfOwned(void)"}
    - {index: 0x02, byte: 0x08, target: 0x00485e90, kind: new, is_thunk: false, is_null: false, ghidra_name: TCityTask::GetTTaskClassNamePointer, size: 143, prototype: "undefined GetTTaskClassNamePointer(void)"}
    - {index: 0x03, byte: 0x0c, target: 0x00412bf0, kind: new, is_thunk: false, is_null: false, ghidra_name: CDocument::ConstructTTaskBaseState, size: 1, prototype: "undefined ConstructTTaskBaseState(void)"}
    - {index: 0x04, byte: 0x10, target: 0x00412c10, kind: new, is_thunk: false, is_null: false, ghidra_name: CPtrList::GetTEventHandlerClassNamePointer, size: 3, prototype: "undefined GetTEventHandlerClassNamePointer(void)"}
    - {index: 0x05, byte: 0x14, target: 0x0054fab0, kind: new, is_thunk: false, is_null: false, ghidra_name: TShip::SerializeNavyPrimaryOrderNodeToStream, size: 123, prototype: "undefined SerializeNavyPrimaryOrderNodeToStream(void)"}
    - {index: 0x06, byte: 0x18, target: 0x0054fb50, kind: new, is_thunk: false, is_null: false, ghidra_name: TShip::DeserializeNavyPrimaryOrderNodeFromStream, size: 126, prototype: "undefined DeserializeNavyPrimaryOrderNodeFromStream(void)"}
    - {index: 0x07, byte: 0x1c, target: 0x0054f640, kind: new, is_thunk: false, is_null: false, ghidra_name: TShip::DestroyAndUnlinkNavyPrimaryOrderNode, size: 241, prototype: "undefined DestroyAndUnlinkNavyPrimaryOrderNode(void)"}
    - {index: 0x08, byte: 0x20, target: 0x004798d0, kind: new, is_thunk: false, is_null: false, ghidra_name: TCityTask::DeserializeCityProductionQueueCommand, size: 5, prototype: "undefined DeserializeCityProductionQueueCommand(void)"}
    - {index: 0x09, byte: 0x24, target: 0x00415ce0, kind: new, is_thunk: false, is_null: false, ghidra_name: TCityTask::OrphanRetStub_0059add0, size: 47, prototype: "undefined OrphanRetStub_0059add0(void)"}
curated:
