class: TTerrainHelpWindow
generated:
  vtable_addr: 0x00657500
  object_size: 0xa0
  base: TFloatWindow
  ancestry: [TTerrainHelpWindow, TFloatWindow, TWindow, TView, TEventHandler, TObject, CObject]
  root: TObject
  slots:
    - {index: 0x00, byte: 0x00, target: 0x00504d20, kind: override, is_thunk: false, is_null: false, ghidra_name: TTerrainHelpWindow::GetTEventHandlerClassNamePointer, size: 6, prototype: "undefined GetTEventHandlerClassNamePointer(void)"}
    - {index: 0x01, byte: 0x04, target: 0x00504d70, kind: override, is_thunk: false, is_null: false, ghidra_name: "TTerrainHelpWindow::'scalar_deleting_destructor'", size: 30, prototype: "undefined 'scalar_deleting_destructor'(byte param_1)"}
    - {index: 0x02, byte: 0x08, target: 0x00485e90, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::Serialize, size: 143, prototype: "void Serialize(CArchive * archive)"}
    - {index: 0x03, byte: 0x0c, target: 0x00412bf0, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::AssertValid, size: 1, prototype: "void AssertValid(void)"}
    - {index: 0x04, byte: 0x10, target: 0x00412c10, kind: inherited, is_thunk: false, is_null: false, ghidra_name: CObject::Dump, size: 3, prototype: "void Dump(undefined4 dc)"}
    - {index: 0x05, byte: 0x14, target: 0x00485f70, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::WriteTo, size: 3, prototype: "void WriteTo(TStream * stream)"}
    - {index: 0x06, byte: 0x18, target: 0x00485f90, kind: inherited, is_thunk: false, is_null: false, ghidra_name: TObject::ReadFrom, size: 3, prototype: "void ReadFrom(TStream * stream)"}
curated:
