[package]
name = "imperialism-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
accesskit.workspace = true
anyhow.workspace = true
bevy.workspace = true
clap.workspace = true
enum-map.workspace = true
gstreamer = "0.24"
gstreamer-app = "0.24"
gstreamer-video = "0.24"
imperialism-core = { path = "../imperialism-core" }
imperialism-formats = { path = "../imperialism-formats" }
thiserror.workspace = true

[dev-dependencies]
indexmap.workspace = true
tempfile = "3"
