[package]
name = "imperialism-testkit"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
imperialism-core = { path = "../imperialism-core" }
imperialism-formats = { path = "../imperialism-formats" }
serde_json.workspace = true
thiserror.workspace = true
