// AUTOGENERATED FILE. DO NOT EDIT.
// Regenerate with: uv run python -m tools.stubgen

#include "decomp_types.h"

// ghidra_name thunk_GetCityBuildingProductionValueBySlot
// ghidra_proto int __thiscall thunk_GetCityBuildingProductionValueBySlot(short nBuildingSlotId)
// ILT thunk 0x0040257c - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_GetCityBuildingProductionValueBySlot(void)
{
  return 0;
}

// ghidra_name thunk_InitializeCityInteriorMinister
// ghidra_proto undefined thunk_InitializeCityInteriorMinister()
// ILT thunk 0x004028d8 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_InitializeCityInteriorMinister(void)
{
  return 0;
}

// ghidra_name thunk_InitializeUiTextStyleDescriptor
// ghidra_proto undefined thunk_InitializeUiTextStyleDescriptor()
// ILT thunk 0x00402a7c - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_InitializeUiTextStyleDescriptor(void)
{
  return 0;
}

// ghidra_name thunk_WrapperFor_InvalidateCityDialogRectRegion_At004f6d90
// ghidra_proto undefined thunk_WrapperFor_InvalidateCityDialogRectRegion_At004f6d90()
// ILT thunk 0x00403f71 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_WrapperFor_InvalidateCityDialogRectRegion_At004f6d90(void)
{
  return 0;
}

// ghidra_name thunk_ConstructUiResourceEntryType4B0C0
// ghidra_proto undefined thunk_ConstructUiResourceEntryType4B0C0()
// ILT thunk 0x004042c8 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_ConstructUiResourceEntryType4B0C0(void)
{
  return 0;
}

// ghidra_name thunk_DestructEngineerDialogBaseState
// ghidra_proto void __thiscall thunk_DestructEngineerDialogBaseState(void)
// ILT thunk 0x00405c72 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_DestructEngineerDialogBaseState(void)
{
  return 0;
}

// ghidra_name thunk_DestructCityDialogSharedBaseState
// ghidra_proto undefined thunk_DestructCityDialogSharedBaseState()
// ILT thunk 0x004067c1 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_DestructCityDialogSharedBaseState(void)
{
  return 0;
}

// ghidra_name thunk_HandleEngineerConstructionAction
// ghidra_proto bool __thiscall thunk_HandleEngineerConstructionAction(short nTileIndex, undefined2 param_2)
// ILT thunk 0x00406ccb - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_HandleEngineerConstructionAction(void)
{
  return 0;
}

// ghidra_name TCivilianButton::thunk_ConstructUiClickablePictureResourceEntry
// ghidra_proto undefined thunk_ConstructUiClickablePictureResourceEntry()
// ILT thunk 0x00409980 - unannotated on purpose (see ILT_THUNK_RANGE)
undefined4 thunk_ConstructUiClickablePictureResourceEntry(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At004125d0
// ghidra_proto undefined WrapperFor_ftol_At004125d0()
// FUNCTION: IMPERIALISM 0x004125d0
undefined4 WrapperFor_ftol_At004125d0(void)
{
  return 0;
}

// ghidra_name InvokeCallbackForRecordRangeWithStride
// ghidra_proto undefined InvokeCallbackForRecordRangeWithStride()
// FUNCTION: IMPERIALISM 0x00412600
undefined4 InvokeCallbackForRecordRangeWithStride(void)
{
  return 0;
}

// ghidra_name OrphanCallChain_C7_I93_00412720
// ghidra_proto undefined OrphanCallChain_C7_I93_00412720()
// FUNCTION: IMPERIALISM 0x00412720
undefined4 OrphanCallChain_C7_I93_00412720(void)
{
  return 0;
}

// ghidra_name InitializeImperialismAppSingletonGlobal
// ghidra_proto undefined InitializeImperialismAppSingletonGlobal()
// FUNCTION: IMPERIALISM 0x00412d40
undefined4 InitializeImperialismAppSingletonGlobal(void)
{
  return 0;
}

// ghidra_name DestroyImperialismAppSingletonGlobal
// ghidra_proto undefined DestroyImperialismAppSingletonGlobal()
// FUNCTION: IMPERIALISM 0x00412d70
undefined4 DestroyImperialismAppSingletonGlobal(void)
{
  return 0;
}

// ghidra_name OrphanCallChain_C1_I08_004133a0
// ghidra_proto undefined OrphanCallChain_C1_I08_004133a0()
// FUNCTION: IMPERIALISM 0x004133a0
undefined4 OrphanCallChain_C1_I08_004133a0(void)
{
  return 0;
}

// ghidra_name ShowSelectedDibInTemplateDDDialog
// ghidra_proto undefined ShowSelectedDibInTemplateDDDialog()
// FUNCTION: IMPERIALISM 0x00413a50
undefined4 ShowSelectedDibInTemplateDDDialog(void)
{
  return 0;
}

// ghidra_name ShowNationSelectDialogAndRedispatchCurrentTurnEvent
// ghidra_proto undefined ShowNationSelectDialogAndRedispatchCurrentTurnEvent()
// FUNCTION: IMPERIALISM 0x00413d20
undefined4 ShowNationSelectDialogAndRedispatchCurrentTurnEvent(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At0047d3f0_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At0047d3f0_Impl()
// FUNCTION: IMPERIALISM 0x00413ed0
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At0047d3f0_Impl(void)
{
  return 0;
}

// ghidra_name HandleDialogResultAndPostCommand100
// ghidra_proto undefined HandleDialogResultAndPostCommand100()
// FUNCTION: IMPERIALISM 0x00413f60
undefined4 HandleDialogResultAndPostCommand100(void)
{
  return 0;
}

// ghidra_name WrapperFor_CDialog_At00414070
// ghidra_proto undefined WrapperFor_CDialog_At00414070()
// FUNCTION: IMPERIALISM 0x00414070
undefined4 WrapperFor_CDialog_At00414070(void)
{
  return 0;
}

// ghidra_name ApplyDialogSelectionToNationState
// ghidra_proto undefined ApplyDialogSelectionToNationState()
// FUNCTION: IMPERIALISM 0x004140f0
undefined4 ApplyDialogSelectionToNationState(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At0047dc40_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At0047dc40_Impl()
// FUNCTION: IMPERIALISM 0x00414320
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At0047dc40_Impl(void)
{
  return 0;
}

// ghidra_name LoadAndPreviewDibFromDialogInput
// ghidra_proto undefined LoadAndPreviewDibFromDialogInput()
// FUNCTION: IMPERIALISM 0x004143b0
undefined4 LoadAndPreviewDibFromDialogInput(void)
{
  return 0;
}

// ghidra_name AssertAmbitSubsystemReadyOrFailWithBmp3B6
// ghidra_proto undefined AssertAmbitSubsystemReadyOrFailWithBmp3B6()
// FUNCTION: IMPERIALISM 0x00414640
undefined4 AssertAmbitSubsystemReadyOrFailWithBmp3B6(void)
{
  return 0;
}

// ghidra_name WrapperFor_GetOrCreateCrtThreadDataFromTls_At00415000
// ghidra_proto undefined WrapperFor_GetOrCreateCrtThreadDataFromTls_At00415000()
// FUNCTION: IMPERIALISM 0x00415000
undefined4 WrapperFor_GetOrCreateCrtThreadDataFromTls_At00415000(void)
{
  return 0;
}

// ghidra_name GetSettingValueFromSettingsSection
// ghidra_proto undefined GetSettingValueFromSettingsSection()
// FUNCTION: IMPERIALISM 0x004154e0
undefined4 GetSettingValueFromSettingsSection(void)
{
  return 0;
}

// ghidra_name CWinApp::WrapperFor_WriteProfileInt_At00415510
// ghidra_proto undefined WrapperFor_WriteProfileInt_At00415510()
// FUNCTION: IMPERIALISM 0x00415510
undefined4 WrapperFor_WriteProfileInt_At00415510(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At005e1c60_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At005e1c60_Impl()
// FUNCTION: IMPERIALISM 0x00415b70
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At005e1c60_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At00415df0
// ghidra_proto undefined WrapperFor_ftol_At00415df0()
// FUNCTION: IMPERIALISM 0x00415df0
undefined4 WrapperFor_ftol_At00415df0(void)
{
  return 0;
}

// ghidra_name InitializeUiResourcePoolStateAndRegisterAtExit
// ghidra_proto undefined InitializeUiResourcePoolStateAndRegisterAtExit()
// FUNCTION: IMPERIALISM 0x00415e20
undefined4 InitializeUiResourcePoolStateAndRegisterAtExit(void)
{
  return 0;
}

// ghidra_name DestroyUiResourcePoolStateAtExit
// ghidra_proto undefined DestroyUiResourcePoolStateAtExit()
// FUNCTION: IMPERIALISM 0x00415e50
undefined4 DestroyUiResourcePoolStateAtExit(void)
{
  return 0;
}

// ghidra_name InitializeUiResourcePoolRuntimeClassFields
// ghidra_proto undefined InitializeUiResourcePoolRuntimeClassFields()
// FUNCTION: IMPERIALISM 0x00415f50
undefined4 InitializeUiResourcePoolRuntimeClassFields(void)
{
  return 0;
}

// ghidra_name PushUiLinkedListNodeWithPayload
// ghidra_proto undefined PushUiLinkedListNodeWithPayload()
// FUNCTION: IMPERIALISM 0x00426ec0
undefined4 PushUiLinkedListNodeWithPayload(void)
{
  return 0;
}

// ghidra_name GetUiLinkedListNodePayload
// ghidra_proto undefined GetUiLinkedListNodePayload()
// FUNCTION: IMPERIALISM 0x00426f60
undefined4 GetUiLinkedListNodePayload(void)
{
  return 0;
}

// ghidra_name NoOpRuntimeCallback_00426f80
// ghidra_proto undefined NoOpRuntimeCallback_00426f80()
// FUNCTION: IMPERIALISM 0x00426f80
undefined4 NoOpRuntimeCallback_00426f80(void)
{
  return 0;
}

// ghidra_name SetUiResourcePairValues
// ghidra_proto undefined SetUiResourcePairValues()
// FUNCTION: IMPERIALISM 0x00427100
undefined4 SetUiResourcePairValues(void)
{
  return 0;
}

// ghidra_name InitializeCityTradeDiplomacyUiEntries
// ghidra_proto undefined InitializeCityTradeDiplomacyUiEntries()
// FUNCTION: IMPERIALISM 0x0042d240
undefined4 InitializeCityTradeDiplomacyUiEntries(void)
{
  return 0;
}

// ghidra_name BuildOrderStateStaticTextUiResourceEntries
// ghidra_proto undefined BuildOrderStateStaticTextUiResourceEntries()
// FUNCTION: IMPERIALISM 0x0042e0b5
undefined4 BuildOrderStateStaticTextUiResourceEntries(void)
{
  return 0;
}

// ghidra_name BuildUiResourceTree_MultiTextOptionComposite_0042e494
// ghidra_proto undefined BuildUiResourceTree_MultiTextOptionComposite_0042e494()
// FUNCTION: IMPERIALISM 0x0042e494
undefined4 BuildUiResourceTree_MultiTextOptionComposite_0042e494(void)
{
  return 0;
}

// ghidra_name BuildUiResourceTree_TextPictureCursorComposite_0042e864
// ghidra_proto undefined BuildUiResourceTree_TextPictureCursorComposite_0042e864()
// FUNCTION: IMPERIALISM 0x0042e864
undefined4 BuildUiResourceTree_TextPictureCursorComposite_0042e864(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl0063f878
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl0063f878()
// FUNCTION: IMPERIALISM 0x00430320
undefined4 ConstructUiResourceEntry_Vtbl0063f878(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl0063fa70
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl0063fa70()
// FUNCTION: IMPERIALISM 0x004303a0
undefined4 ConstructUiResourceEntry_Vtbl0063fa70(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl0063fc68
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl0063fc68()
// FUNCTION: IMPERIALISM 0x00430420
undefined4 ConstructUiResourceEntry_Vtbl0063fc68(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl0063fe60
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl0063fe60()
// FUNCTION: IMPERIALISM 0x004304a0
undefined4 ConstructUiResourceEntry_Vtbl0063fe60(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl00640060
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl00640060()
// FUNCTION: IMPERIALISM 0x00430520
undefined4 ConstructUiResourceEntry_Vtbl00640060(void)
{
  return 0;
}

// ghidra_name ConstructPictureResourceEntry_Vtbl00640258
// ghidra_proto undefined ConstructPictureResourceEntry_Vtbl00640258()
// FUNCTION: IMPERIALISM 0x00430630
undefined4 ConstructPictureResourceEntry_Vtbl00640258(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At00430660_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At00430660_Impl()
// FUNCTION: IMPERIALISM 0x00430690
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At00430660_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004307a0
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004307a0()
// FUNCTION: IMPERIALISM 0x004307a0
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004307a0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At00430830
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At00430830()
// FUNCTION: IMPERIALISM 0x00430830
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At00430830(void)
{
  return 0;
}

// ghidra_name ConstructPictureResourceEntry_Vtbl006404b0
// ghidra_proto undefined ConstructPictureResourceEntry_Vtbl006404b0()
// FUNCTION: IMPERIALISM 0x004308d0
undefined4 ConstructPictureResourceEntry_Vtbl006404b0(void)
{
  return 0;
}

// ghidra_name ConstructUiResourceEntry_Vtbl00640940
// ghidra_proto undefined ConstructUiResourceEntry_Vtbl00640940()
// FUNCTION: IMPERIALISM 0x00430b50
undefined4 ConstructUiResourceEntry_Vtbl00640940(void)
{
  return 0;
}

// ghidra_name TPageView::WrapperFor_ConstructTPageViewBaseState_At00435590
// ghidra_proto undefined WrapperFor_ConstructTPageViewBaseState_At00435590()
// FUNCTION: IMPERIALISM 0x00435590
undefined4 WrapperFor_ConstructTPageViewBaseState_At00435590(void)
{
  return 0;
}

// ghidra_name TPageView::WrapperFor_ConstructTPageViewBaseState_At00435610
// ghidra_proto undefined WrapperFor_ConstructTPageViewBaseState_At00435610()
// FUNCTION: IMPERIALISM 0x00435610
undefined4 WrapperFor_ConstructTPageViewBaseState_At00435610(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_ConstructPictureResourceEntryBase_At004356e0
// ghidra_proto undefined WrapperFor_thunk_ConstructPictureResourceEntryBase_At004356e0()
// FUNCTION: IMPERIALISM 0x004356e0
undefined4 WrapperFor_thunk_ConstructPictureResourceEntryBase_At004356e0(void)
{
  return 0;
}

// ghidra_name TControl::WrapperFor_thunk_ConstructUiCommandTagResourceEntryBase_At0043d610
// ghidra_proto undefined WrapperFor_thunk_ConstructUiCommandTagResourceEntryBase_At0043d610()
// FUNCTION: IMPERIALISM 0x0043d610
undefined4 WrapperFor_thunk_ConstructUiCommandTagResourceEntryBase_At0043d610(void)
{
  return 0;
}

// ghidra_name TCzechBox::WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0
// ghidra_proto undefined WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0()
// FUNCTION: IMPERIALISM 0x0043d6f0
undefined4 WrapperFor_ConstructTCzechBoxBaseState_At0043d6f0(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d770
// ghidra_proto undefined WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d770()
// FUNCTION: IMPERIALISM 0x0043d770
undefined4 WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d770(void)
{
  return 0;
}

// ghidra_name ConstructTurnEventMainPictureEntry_10CC
// ghidra_proto int * __fastcall ConstructTurnEventMainPictureEntry_10CC(int * pEntry)
// FUNCTION: IMPERIALISM 0x0043d840
undefined4 ConstructTurnEventMainPictureEntry_10CC(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d8c0
// ghidra_proto undefined WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d8c0()
// FUNCTION: IMPERIALISM 0x0043d8c0
undefined4 WrapperFor_thunk_ConstructPictureResourceEntryBase_At0043d8c0(void)
{
  return 0;
}

// ghidra_name ConstructUiBaseBackdropPictureEntry
// ghidra_proto undefined ConstructUiBaseBackdropPictureEntry()
// FUNCTION: IMPERIALISM 0x0043d8f0
undefined4 ConstructUiBaseBackdropPictureEntry(void)
{
  return 0;
}

// ghidra_name ConstructTurnEventMainPictureEntry_1036
// ghidra_proto int * __fastcall ConstructTurnEventMainPictureEntry_1036(int * pEntry)
// FUNCTION: IMPERIALISM 0x0043d960
undefined4 ConstructTurnEventMainPictureEntry_1036(void)
{
  return 0;
}

// ghidra_name ConstructTurnEventMainPictureEntry_104F
// ghidra_proto int * __fastcall ConstructTurnEventMainPictureEntry_104F(int * pEntry)
// FUNCTION: IMPERIALISM 0x0043d9c0
undefined4 ConstructTurnEventMainPictureEntry_104F(void)
{
  return 0;
}

// ghidra_name InitializeTNavyRosterBitmapAndControlResources
// ghidra_proto undefined InitializeTNavyRosterBitmapAndControlResources(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x004472bb
undefined4 InitializeTNavyRosterBitmapAndControlResources(void)
{
  return 0;
}

// ghidra_name TNavyRoster::BuildNavyRosterDialogUiResourceTree
// ghidra_proto undefined BuildNavyRosterDialogUiResourceTree(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x00447353
undefined4 BuildNavyRosterDialogUiResourceTree(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_RegisterDialogFactoryCallback_At0044a7f0
// ghidra_proto undefined WrapperFor_thunk_RegisterDialogFactoryCallback_At0044a7f0()
// FUNCTION: IMPERIALISM 0x0044a7f0
undefined4 WrapperFor_thunk_RegisterDialogFactoryCallback_At0044a7f0(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80
// ghidra_proto undefined WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80()
// FUNCTION: IMPERIALISM 0x0044fa80
undefined4 WrapperFor_thunk_ConstructPictureResourceEntryBase_At0044fa80(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_RegisterDialogFactoryCallback_At0044fba0
// ghidra_proto undefined WrapperFor_thunk_RegisterDialogFactoryCallback_At0044fba0()
// FUNCTION: IMPERIALISM 0x0044fba0
undefined4 WrapperFor_thunk_RegisterDialogFactoryCallback_At0044fba0(void)
{
  return 0;
}

// ghidra_name BuildDifficultyAndNamesSetupUiResources
// ghidra_proto undefined BuildDifficultyAndNamesSetupUiResources(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x00456ba3
undefined4 BuildDifficultyAndNamesSetupUiResources(void)
{
  return 0;
}

// ghidra_name BuildUiResourceTreeWithPlanetListAndCursorEntries_0045762e
// ghidra_proto undefined BuildUiResourceTreeWithPlanetListAndCursorEntries_0045762e(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x0045762e
undefined4 BuildUiResourceTreeWithPlanetListAndCursorEntries_0045762e(void)
{
  return 0;
}

// ghidra_name thunk_BuildMainStatsScoreboardAndDoneUiResourceTree
// ghidra_proto undefined thunk_BuildMainStatsScoreboardAndDoneUiResourceTree(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x00457aee
undefined4 thunk_BuildMainStatsScoreboardAndDoneUiResourceTree(void)
{
  return 0;
}

// ghidra_name BuildMainStatsScoreboardAndDoneUiResourceTree
// ghidra_proto undefined BuildMainStatsScoreboardAndDoneUiResourceTree(undefined4 param_1)
// FUNCTION: IMPERIALISM 0x00457af2
undefined4 BuildMainStatsScoreboardAndDoneUiResourceTree(void)
{
  return 0;
}

// ghidra_name AllocateAndConstructTViewDerivedState_00458ced
// ghidra_proto undefined AllocateAndConstructTViewDerivedState_00458ced()
// FUNCTION: IMPERIALISM 0x00458ced
undefined4 AllocateAndConstructTViewDerivedState_00458ced(void)
{
  return 0;
}

// ghidra_name thunk_InitializeOrderStateUiResourceTreeAndControlEntries
// ghidra_proto undefined thunk_InitializeOrderStateUiResourceTreeAndControlEntries()
// FUNCTION: IMPERIALISM 0x00458d10
undefined4 thunk_InitializeOrderStateUiResourceTreeAndControlEntries(void)
{
  return 0;
}

// ghidra_name InitializeOrderStateUiResourceTreeAndControlEntries
// ghidra_proto undefined InitializeOrderStateUiResourceTreeAndControlEntries()
// FUNCTION: IMPERIALISM 0x00458d14
undefined4 InitializeOrderStateUiResourceTreeAndControlEntries(void)
{
  return 0;
}

// ghidra_name ClearColorRgbaBytes
// ghidra_proto undefined ClearColorRgbaBytes()
// FUNCTION: IMPERIALISM 0x0045b080
undefined4 ClearColorRgbaBytes(void)
{
  return 0;
}

// ghidra_name SetColorRgbAndClearAlphaByte
// ghidra_proto undefined SetColorRgbAndClearAlphaByte()
// FUNCTION: IMPERIALISM 0x0045b0a0
undefined4 SetColorRgbAndClearAlphaByte(void)
{
  return 0;
}

// ghidra_name TOffLimitsPicture::WrapperFor_ConstructTOffLimitsPictureBaseState_At0045d270
// ghidra_proto undefined WrapperFor_ConstructTOffLimitsPictureBaseState_At0045d270()
// FUNCTION: IMPERIALISM 0x0045d270
undefined4 WrapperFor_ConstructTOffLimitsPictureBaseState_At0045d270(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_ConstructPictureResourceEntryBase_At0045d480
// ghidra_proto undefined WrapperFor_thunk_ConstructPictureResourceEntryBase_At0045d480()
// FUNCTION: IMPERIALISM 0x0045d480
undefined4 WrapperFor_thunk_ConstructPictureResourceEntryBase_At0045d480(void)
{
  return 0;
}

// ghidra_name BuildTradeBoardDialogUiLayoutVariantB
// ghidra_proto undefined BuildTradeBoardDialogUiLayoutVariantB()
// FUNCTION: IMPERIALISM 0x0046baa7
undefined4 BuildTradeBoardDialogUiLayoutVariantB(void)
{
  return 0;
}

// ghidra_name BuildUniversityDialogControls
// ghidra_proto undefined BuildUniversityDialogControls()
// FUNCTION: IMPERIALISM 0x00474ac5
undefined4 BuildUniversityDialogControls(void)
{
  return 0;
}

// ghidra_name thunk_BuildUniversityRecruitmentRows
// ghidra_proto undefined thunk_BuildUniversityRecruitmentRows()
// FUNCTION: IMPERIALISM 0x00475f80
undefined4 thunk_BuildUniversityRecruitmentRows(void)
{
  return 0;
}

// ghidra_name BuildUniversityRecruitControls
// ghidra_proto undefined BuildUniversityRecruitControls()
// FUNCTION: IMPERIALISM 0x00475f82
undefined4 BuildUniversityRecruitControls(void)
{
  return 0;
}

// ghidra_name BuildUniversityRecruitmentRows
// ghidra_proto undefined BuildUniversityRecruitmentRows()
// FUNCTION: IMPERIALISM 0x00475f84
undefined4 BuildUniversityRecruitmentRows(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At004798f0_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At004798f0_Impl()
// FUNCTION: IMPERIALISM 0x00479920
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At004798f0_Impl(void)
{
  return 0;
}

// ghidra_name InitializeJoinSelectorDialogControlsAndNationSlots_Impl
// ghidra_proto undefined InitializeJoinSelectorDialogControlsAndNationSlots_Impl()
// FUNCTION: IMPERIALISM 0x00479ba0
undefined4 InitializeJoinSelectorDialogControlsAndNationSlots_Impl(void)
{
  return 0;
}

// ghidra_name InitializeJoinSelectorDialogControlsAndNationSlots_Impl_At00479bc0
// ghidra_proto undefined InitializeJoinSelectorDialogControlsAndNationSlots_Impl_At00479bc0()
// FUNCTION: IMPERIALISM 0x00479bc0
undefined4 InitializeJoinSelectorDialogControlsAndNationSlots_Impl_At00479bc0(void)
{
  return 0;
}

// ghidra_name RegisterUiResourceEntry_Impl
// ghidra_proto undefined RegisterUiResourceEntry_Impl()
// FUNCTION: IMPERIALISM 0x00479e10
undefined4 RegisterUiResourceEntry_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_AFX_CLASSINIT_At00479ef0
// ghidra_proto undefined WrapperFor_AFX_CLASSINIT_At00479ef0()
// FUNCTION: IMPERIALISM 0x00479ef0
undefined4 WrapperFor_AFX_CLASSINIT_At00479ef0(void)
{
  return 0;
}

// ghidra_name ConstructBitmapBlitBufferFromSourceDescriptor
// ghidra_proto undefined ConstructBitmapBlitBufferFromSourceDescriptor()
// FUNCTION: IMPERIALISM 0x0047a200
undefined4 ConstructBitmapBlitBufferFromSourceDescriptor(void)
{
  return 0;
}

// ghidra_name BuildPaletteAndReleaseBitmapSurfaceResources
// ghidra_proto undefined BuildPaletteAndReleaseBitmapSurfaceResources()
// FUNCTION: IMPERIALISM 0x0047a420
undefined4 BuildPaletteAndReleaseBitmapSurfaceResources(void)
{
  return 0;
}

// ghidra_name Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a630
// ghidra_proto undefined Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a630()
// FUNCTION: IMPERIALISM 0x0047a630
undefined4 Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a630(void)
{
  return 0;
}

// ghidra_name Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a8a0
// ghidra_proto undefined Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a8a0()
// FUNCTION: IMPERIALISM 0x0047a8a0
undefined4 Helper_Uses_BuildPaletteFromRgbQuadBuffer_At0047a8a0(void)
{
  return 0;
}

// ghidra_name BlitDibBitsWithStretchDIBits
// ghidra_proto undefined BlitDibBitsWithStretchDIBits()
// FUNCTION: IMPERIALISM 0x0047aae0
undefined4 BlitDibBitsWithStretchDIBits(void)
{
  return 0;
}

// ghidra_name ReinitializeIncludeViewMainPaneAndRedrawWindow_Impl
// ghidra_proto undefined ReinitializeIncludeViewMainPaneAndRedrawWindow_Impl()
// FUNCTION: IMPERIALISM 0x0047af60
undefined4 ReinitializeIncludeViewMainPaneAndRedrawWindow_Impl(void)
{
  return 0;
}

// ghidra_name OrphanDeadLeaf_NoRefs_0047b130
// ghidra_proto undefined OrphanDeadLeaf_NoRefs_0047b130()
// FUNCTION: IMPERIALISM 0x0047b130
undefined4 OrphanDeadLeaf_NoRefs_0047b130(void)
{
  return 0;
}

// ghidra_name thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b53b
// ghidra_proto undefined thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b53b()
// FUNCTION: IMPERIALISM 0x0047b53b
undefined4 thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b53b(void)
{
  return 0;
}

// ghidra_name thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b544
// ghidra_proto undefined thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b544()
// FUNCTION: IMPERIALISM 0x0047b544
undefined4 thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b544(void)
{
  return 0;
}

// ghidra_name thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b54d
// ghidra_proto undefined thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b54d()
// FUNCTION: IMPERIALISM 0x0047b54d
undefined4 thunk_WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d_At0047b54d(void)
{
  return 0;
}

// ghidra_name WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d
// ghidra_proto undefined WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d()
// FUNCTION: IMPERIALISM 0x0047b55d
undefined4 WrapperFor_BuildPaletteFromRgbQuadBuffer_At0047b55d(void)
{
  return 0;
}

// ghidra_name OrphanCallChain_C3_I20_0047bd90
// ghidra_proto undefined OrphanCallChain_C3_I20_0047bd90()
// FUNCTION: IMPERIALISM 0x0047bd90
undefined4 OrphanCallChain_C3_I20_0047bd90(void)
{
  return 0;
}

// ghidra_name LoadBmpResourceByIdCached_Impl
// ghidra_proto undefined LoadBmpResourceByIdCached_Impl()
// FUNCTION: IMPERIALISM 0x0047bf90
undefined4 LoadBmpResourceByIdCached_Impl(void)
{
  return 0;
}

// ghidra_name LoadAndPreviewDibFromDialogInput_Impl
// ghidra_proto undefined LoadAndPreviewDibFromDialogInput_Impl()
// FUNCTION: IMPERIALISM 0x0047c1f0
undefined4 LoadAndPreviewDibFromDialogInput_Impl(void)
{
  return 0;
}

// ghidra_name RebuildSurfaceRowsWithTemporaryRowBuffer
// ghidra_proto undefined RebuildSurfaceRowsWithTemporaryRowBuffer()
// FUNCTION: IMPERIALISM 0x0047c980
undefined4 RebuildSurfaceRowsWithTemporaryRowBuffer(void)
{
  return 0;
}

// ghidra_name WrapperFor_DeleteRegionHandleFromClipState_At0047cac0
// ghidra_proto undefined WrapperFor_DeleteRegionHandleFromClipState_At0047cac0()
// FUNCTION: IMPERIALISM 0x0047cac0
undefined4 WrapperFor_DeleteRegionHandleFromClipState_At0047cac0(void)
{
  return 0;
}

// ghidra_name WrapperFor_DeleteRegionHandleFromClipState_At0047cb60
// ghidra_proto undefined WrapperFor_DeleteRegionHandleFromClipState_At0047cb60()
// FUNCTION: IMPERIALISM 0x0047cb60
undefined4 WrapperFor_DeleteRegionHandleFromClipState_At0047cb60(void)
{
  return 0;
}

// ghidra_name SendMciCommand804IfDeviceOpenAndClearHandle_FastcallBridge
// ghidra_proto undefined SendMciCommand804IfDeviceOpenAndClearHandle_FastcallBridge()
// FUNCTION: IMPERIALISM 0x0047cd30
undefined4 SendMciCommand804IfDeviceOpenAndClearHandle_FastcallBridge(void)
{
  return 0;
}

// ghidra_name ForwardMciCommand808ToDevice
// ghidra_proto undefined ForwardMciCommand808ToDevice()
// FUNCTION: IMPERIALISM 0x0047cd80
undefined4 ForwardMciCommand808ToDevice(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At0047cfa0
// ghidra_proto undefined WrapperFor_ftol_At0047cfa0()
// FUNCTION: IMPERIALISM 0x0047cfa0
undefined4 WrapperFor_ftol_At0047cfa0(void)
{
  return 0;
}

// ghidra_name DestroyDialogWithListBoxAndHotKeyControl_Alias
// ghidra_proto undefined DestroyDialogWithListBoxAndHotKeyControl_Alias()
// FUNCTION: IMPERIALISM 0x0047d0c0
undefined4 DestroyDialogWithListBoxAndHotKeyControl_Alias(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At0047d250_Impl
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At0047d250_Impl()
// FUNCTION: IMPERIALISM 0x0047d280
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At0047d250_Impl(void)
{
  return 0;
}

