// AUTOGENERATED FILE. DO NOT EDIT.
// Regenerate with: uv run python -m tools.stubgen

#include "decomp_types.h"

// ghidra_name PlanAiDevelopmentActionsFromResourcePools_Impl_At004be6f0
// ghidra_proto undefined PlanAiDevelopmentActionsFromResourcePools_Impl_At004be6f0()
// FUNCTION: IMPERIALISM 0x004be6f0
undefined4 PlanAiDevelopmentActionsFromResourcePools_Impl_At004be6f0(void)
{
  return 0;
}

// ghidra_name DestroyTCityInteriorMinister_Impl
// ghidra_proto undefined DestroyTCityInteriorMinister_Impl()
// FUNCTION: IMPERIALISM 0x004be8b0
undefined4 DestroyTCityInteriorMinister_Impl(void)
{
  return 0;
}

// ghidra_name TLinkedBlockChainState_00650A50::DestructLinkedBlockChainState_00650A50_AndFreeChain_At004bec40
// ghidra_proto undefined DestructLinkedBlockChainState_00650A50_AndFreeChain_At004bec40()
// FUNCTION: IMPERIALISM 0x004bec40
undefined4 DestructLinkedBlockChainState_00650A50_AndFreeChain_At004bec40(void)
{
  return 0;
}

// ghidra_name AppendInteriorMinisterValueGrowShortBuffer
// ghidra_proto undefined AppendInteriorMinisterValueGrowShortBuffer()
// FUNCTION: IMPERIALISM 0x004c18a0
undefined4 AppendInteriorMinisterValueGrowShortBuffer(void)
{
  return 0;
}

// ghidra_name WrapperFor_ComputeBestNationTileDevelopmentScore_At004c1990
// ghidra_proto undefined WrapperFor_ComputeBestNationTileDevelopmentScore_At004c1990()
// FUNCTION: IMPERIALISM 0x004c1990
undefined4 WrapperFor_ComputeBestNationTileDevelopmentScore_At004c1990(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004c1fc0
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004c1fc0()
// FUNCTION: IMPERIALISM 0x004c1fc0
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004c1fc0(void)
{
  return 0;
}

// ghidra_name TraceDescendingTileScoreGradientToSource
// ghidra_proto undefined TraceDescendingTileScoreGradientToSource()
// FUNCTION: IMPERIALISM 0x004c30b0
undefined4 TraceDescendingTileScoreGradientToSource(void)
{
  return 0;
}

// ghidra_name OrphanCallChain_C1_I20_004c4c4c
// ghidra_proto undefined OrphanCallChain_C1_I20_004c4c4c()
// FUNCTION: IMPERIALISM 0x004c4c4c
undefined4 OrphanCallChain_C1_I20_004c4c4c(void)
{
  return 0;
}

// ghidra_name PlanAiDevelopmentActionsFromResourcePools_Impl
// ghidra_proto undefined PlanAiDevelopmentActionsFromResourcePools_Impl()
// FUNCTION: IMPERIALISM 0x004c4f90
undefined4 PlanAiDevelopmentActionsFromResourcePools_Impl(void)
{
  return 0;
}

// ghidra_name TryApplyCityOrderCapabilitySelectionBySlot
// ghidra_proto undefined TryApplyCityOrderCapabilitySelectionBySlot()
// FUNCTION: IMPERIALISM 0x004c56e0
undefined4 TryApplyCityOrderCapabilitySelectionBySlot(void)
{
  return 0;
}

// ghidra_name DestructTSteelCityMinisterAndMaybeFree_Impl
// ghidra_proto undefined DestructTSteelCityMinisterAndMaybeFree_Impl()
// FUNCTION: IMPERIALISM 0x004c5a50
undefined4 DestructTSteelCityMinisterAndMaybeFree_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_InitializeCityInteriorMinister_At004c5a70
// ghidra_proto undefined WrapperFor_thunk_InitializeCityInteriorMinister_At004c5a70()
// FUNCTION: IMPERIALISM 0x004c5a70
undefined4 WrapperFor_thunk_InitializeCityInteriorMinister_At004c5a70(void)
{
  return 0;
}

// ghidra_name DestructTShipBuilderCityMinisterAndMaybeFree_Impl
// ghidra_proto undefined DestructTShipBuilderCityMinisterAndMaybeFree_Impl()
// FUNCTION: IMPERIALISM 0x004c5d50
undefined4 DestructTShipBuilderCityMinisterAndMaybeFree_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_InitializeCityInteriorMinister_At004c5d70
// ghidra_proto undefined WrapperFor_thunk_InitializeCityInteriorMinister_At004c5d70()
// FUNCTION: IMPERIALISM 0x004c5d70
undefined4 WrapperFor_thunk_InitializeCityInteriorMinister_At004c5d70(void)
{
  return 0;
}

// ghidra_name DestructTEvenCityMinisterAndMaybeFree_Impl
// ghidra_proto undefined DestructTEvenCityMinisterAndMaybeFree_Impl()
// FUNCTION: IMPERIALISM 0x004c6050
undefined4 DestructTEvenCityMinisterAndMaybeFree_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_InitializeCityInteriorMinister_At004c6070
// ghidra_proto undefined WrapperFor_thunk_InitializeCityInteriorMinister_At004c6070()
// FUNCTION: IMPERIALISM 0x004c6070
undefined4 WrapperFor_thunk_InitializeCityInteriorMinister_At004c6070(void)
{
  return 0;
}

// ghidra_name DestructTRailCityMinisterAndMaybeFree_Impl
// ghidra_proto undefined DestructTRailCityMinisterAndMaybeFree_Impl()
// FUNCTION: IMPERIALISM 0x004c6360
undefined4 DestructTRailCityMinisterAndMaybeFree_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_InitializeCityInteriorMinister_At004c6380
// ghidra_proto undefined WrapperFor_thunk_InitializeCityInteriorMinister_At004c6380()
// FUNCTION: IMPERIALISM 0x004c6380
undefined4 WrapperFor_thunk_InitializeCityInteriorMinister_At004c6380(void)
{
  return 0;
}

// ghidra_name WrapperFor_FreeHeapBufferIfNotNull_At004c6aa0
// ghidra_proto undefined WrapperFor_FreeHeapBufferIfNotNull_At004c6aa0()
// FUNCTION: IMPERIALISM 0x004c6aa0
undefined4 WrapperFor_FreeHeapBufferIfNotNull_At004c6aa0(void)
{
  return 0;
}

// ghidra_name TLinkedBlockChainState_00650A50::DestructLinkedBlockChainState_00650A50_AndFreeChain_At004c6ad0
// ghidra_proto undefined DestructLinkedBlockChainState_00650A50_AndFreeChain_At004c6ad0()
// FUNCTION: IMPERIALISM 0x004c6ad0
undefined4 DestructLinkedBlockChainState_00650A50_AndFreeChain_At004c6ad0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At004c6cb0
// ghidra_proto undefined WrapperFor_ftol_At004c6cb0()
// FUNCTION: IMPERIALISM 0x004c6cb0
undefined4 WrapperFor_ftol_At004c6cb0(void)
{
  return 0;
}

// ghidra_name TShipyardView::ConstructTShipyardViewBaseState
// ghidra_proto undefined ConstructTShipyardViewBaseState()
// FUNCTION: IMPERIALISM 0x004c82c0
undefined4 ConstructTShipyardViewBaseState(void)
{
  return 0;
}

// ghidra_name WrapperFor_thunk_LoadBitmapResourceSurfaceAndRestoreQuickDrawContext_At004c8a20
// ghidra_proto undefined WrapperFor_thunk_LoadBitmapResourceSurfaceAndRestoreQuickDrawContext_At004c8a20()
// FUNCTION: IMPERIALISM 0x004c8a20
undefined4 WrapperFor_thunk_LoadBitmapResourceSurfaceAndRestoreQuickDrawContext_At004c8a20(void)
{
  return 0;
}

// ghidra_name UpdateCityViewCountControlAndRefreshSelection
// ghidra_proto undefined UpdateCityViewCountControlAndRefreshSelection()
// FUNCTION: IMPERIALISM 0x004c8c09
undefined4 UpdateCityViewCountControlAndRefreshSelection(void)
{
  return 0;
}

// ghidra_name UpdateCityViewCountControlAndRefreshSelectionAlt
// ghidra_proto undefined UpdateCityViewCountControlAndRefreshSelectionAlt()
// FUNCTION: IMPERIALISM 0x004c8c3f
undefined4 UpdateCityViewCountControlAndRefreshSelectionAlt(void)
{
  return 0;
}

// ghidra_name UpdateUniversityCountControlAndRefreshView
// ghidra_proto undefined UpdateUniversityCountControlAndRefreshView()
// FUNCTION: IMPERIALISM 0x004cb9cd
undefined4 UpdateUniversityCountControlAndRefreshView(void)
{
  return 0;
}

// ghidra_name UpdateUniversityCountControlAndRefreshViewAlt
// ghidra_proto undefined UpdateUniversityCountControlAndRefreshViewAlt()
// FUNCTION: IMPERIALISM 0x004cba03
undefined4 UpdateUniversityCountControlAndRefreshViewAlt(void)
{
  return 0;
}

// ghidra_name DispatchCityViewSelectionChangeAndRefresh
// ghidra_proto undefined DispatchCityViewSelectionChangeAndRefresh()
// FUNCTION: IMPERIALISM 0x004ccfa2
undefined4 DispatchCityViewSelectionChangeAndRefresh(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStatePap1
// ghidra_proto undefined UpdateUniversityRequirementBadgeStatePap1()
// FUNCTION: IMPERIALISM 0x004ce0be
undefined4 UpdateUniversityRequirementBadgeStatePap1(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStatePap2
// ghidra_proto undefined UpdateUniversityRequirementBadgeStatePap2()
// FUNCTION: IMPERIALISM 0x004ce12c
undefined4 UpdateUniversityRequirementBadgeStatePap2(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStateMon1
// ghidra_proto undefined UpdateUniversityRequirementBadgeStateMon1()
// FUNCTION: IMPERIALISM 0x004ce19a
undefined4 UpdateUniversityRequirementBadgeStateMon1(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStateMon2
// ghidra_proto undefined UpdateUniversityRequirementBadgeStateMon2()
// FUNCTION: IMPERIALISM 0x004ce230
undefined4 UpdateUniversityRequirementBadgeStateMon2(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStateUntV
// ghidra_proto undefined UpdateUniversityRequirementBadgeStateUntV()
// FUNCTION: IMPERIALISM 0x004ce2c8
undefined4 UpdateUniversityRequirementBadgeStateUntV(void)
{
  return 0;
}

// ghidra_name UpdateUniversityRequirementBadgeStateTraV
// ghidra_proto undefined UpdateUniversityRequirementBadgeStateTraV()
// FUNCTION: IMPERIALISM 0x004ce341
undefined4 UpdateUniversityRequirementBadgeStateTraV(void)
{
  return 0;
}

// ghidra_name ConstructBuildingExpansionView
// ghidra_proto undefined ConstructBuildingExpansionView()
// FUNCTION: IMPERIALISM 0x004ce520
undefined4 ConstructBuildingExpansionView(void)
{
  return 0;
}

// ghidra_name ConstructArmoryView
// ghidra_proto undefined ConstructArmoryView()
// FUNCTION: IMPERIALISM 0x004ceda0
undefined4 ConstructArmoryView(void)
{
  return 0;
}

// ghidra_name UpdateUniversitySpecialistCountControlAndRefreshView
// ghidra_proto undefined UpdateUniversitySpecialistCountControlAndRefreshView()
// FUNCTION: IMPERIALISM 0x004cf46f
undefined4 UpdateUniversitySpecialistCountControlAndRefreshView(void)
{
  return 0;
}

// ghidra_name UpdateUniversitySpecialistCountControlAndRefreshViewAlt
// ghidra_proto undefined UpdateUniversitySpecialistCountControlAndRefreshViewAlt()
// FUNCTION: IMPERIALISM 0x004cf4a5
undefined4 UpdateUniversitySpecialistCountControlAndRefreshViewAlt(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At004d1fb0
// ghidra_proto undefined WrapperFor_ftol_At004d1fb0()
// FUNCTION: IMPERIALISM 0x004d1fb0
undefined4 WrapperFor_ftol_At004d1fb0(void)
{
  return 0;
}

// ghidra_name CivilianMapInteractionManager::InitializeCivilianMapInteractionManagerVtable
// ghidra_proto undefined InitializeCivilianMapInteractionManagerVtable()
// FUNCTION: IMPERIALISM 0x004d2050
undefined4 InitializeCivilianMapInteractionManagerVtable(void)
{
  return 0;
}

// ghidra_name InitializeCivilianMapInteractionManagerBaseVtable
// ghidra_proto undefined InitializeCivilianMapInteractionManagerBaseVtable()
// FUNCTION: IMPERIALISM 0x004d20a0
undefined4 InitializeCivilianMapInteractionManagerBaseVtable(void)
{
  return 0;
}

// ghidra_name NoOpCivilianMapInteractionManagerVirtualHook
// ghidra_proto undefined NoOpCivilianMapInteractionManagerVirtualHook()
// FUNCTION: IMPERIALISM 0x004d20c0
undefined4 NoOpCivilianMapInteractionManagerVirtualHook(void)
{
  return 0;
}

// ghidra_name ClearCivilianSelectionHighlightsForNation
// ghidra_proto undefined ClearCivilianSelectionHighlightsForNation()
// FUNCTION: IMPERIALISM 0x004d20e0
undefined4 ClearCivilianSelectionHighlightsForNation(void)
{
  return 0;
}

// ghidra_name SelectFirstAvailableCivilianForNation
// ghidra_proto void * __thiscall SelectFirstAvailableCivilianForNation(short nNationId)
// FUNCTION: IMPERIALISM 0x004d2160
undefined4 SelectFirstAvailableCivilianForNation(void)
{
  return 0;
}

// ghidra_name TMapMgr::QueueCivilianWorkOrderWithCostCheck
// ghidra_proto bool __thiscall QueueCivilianWorkOrderWithCostCheck(short nTileIndex)
// FUNCTION: IMPERIALISM 0x004d3310
undefined4 QueueCivilianWorkOrderWithCostCheck(void)
{
  return 0;
}

// ghidra_name TCivToolbar::PromptAndQueueDeveloperTilePurchaseOrder
// ghidra_proto bool __thiscall PromptAndQueueDeveloperTilePurchaseOrder(short nTileIndex)
// FUNCTION: IMPERIALISM 0x004d3610
undefined4 PromptAndQueueDeveloperTilePurchaseOrder(void)
{
  return 0;
}

// ghidra_name QueueProspectingOrderAndPlayFeedback
// ghidra_proto undefined QueueProspectingOrderAndPlayFeedback()
// FUNCTION: IMPERIALISM 0x004d39d0
undefined4 QueueProspectingOrderAndPlayFeedback(void)
{
  return 0;
}

// ghidra_name ResolveCompetingDeveloperTilePurchaseOrders
// ghidra_proto undefined ResolveCompetingDeveloperTilePurchaseOrders()
// FUNCTION: IMPERIALISM 0x004d4740
undefined4 ResolveCompetingDeveloperTilePurchaseOrders(void)
{
  return 0;
}

// ghidra_name DestructLandSaleEventToBase
// ghidra_proto undefined DestructLandSaleEventToBase()
// FUNCTION: IMPERIALISM 0x004d49d0
undefined4 DestructLandSaleEventToBase(void)
{
  return 0;
}

// ghidra_name HandleMapHotkeyW_ResetSelectedActionableObjects
// ghidra_proto undefined HandleMapHotkeyW_ResetSelectedActionableObjects()
// FUNCTION: IMPERIALISM 0x004d49f0
undefined4 HandleMapHotkeyW_ResetSelectedActionableObjects(void)
{
  return 0;
}

// ghidra_name DiscardTileTokenArgumentAndReturn
// ghidra_proto undefined DiscardTileTokenArgumentAndReturn()
// FUNCTION: IMPERIALISM 0x004d4bd0
undefined4 DiscardTileTokenArgumentAndReturn(void)
{
  return 0;
}

// ghidra_name TDiplomacyMapView::AppendPackedColorDwordToMaskBuffers
// ghidra_proto undefined AppendPackedColorDwordToMaskBuffers()
// FUNCTION: IMPERIALISM 0x004d4bf0
undefined4 AppendPackedColorDwordToMaskBuffers(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4dd0
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4dd0()
// FUNCTION: IMPERIALISM 0x004d4dd0
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4dd0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4ed0
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4ed0()
// FUNCTION: IMPERIALISM 0x004d4ed0
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4ed0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4f50
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4f50()
// FUNCTION: IMPERIALISM 0x004d4f50
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d4f50(void)
{
  return 0;
}

// ghidra_name AppendCallbackGeneratedByteToGrowableBuffer
// ghidra_proto undefined AppendCallbackGeneratedByteToGrowableBuffer()
// FUNCTION: IMPERIALISM 0x004d4ff0
undefined4 AppendCallbackGeneratedByteToGrowableBuffer(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d5970
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d5970()
// FUNCTION: IMPERIALISM 0x004d5970
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d5970(void)
{
  return 0;
}

// ghidra_name WrapperFor_IsPointInsideHitRegion_At004d59a0
// ghidra_proto undefined WrapperFor_IsPointInsideHitRegion_At004d59a0()
// FUNCTION: IMPERIALISM 0x004d59a0
undefined4 WrapperFor_IsPointInsideHitRegion_At004d59a0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d62d0
// ghidra_proto undefined WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d62d0()
// FUNCTION: IMPERIALISM 0x004d62d0
undefined4 WrapperFor_ReallocateHeapBlockWithAllocatorTracking_At004d62d0(void)
{
  return 0;
}

// ghidra_name BuildDiplomacyOverlayHitMaskOpcodeStream_Impl
// ghidra_proto undefined BuildDiplomacyOverlayHitMaskOpcodeStream_Impl()
// FUNCTION: IMPERIALISM 0x004d6310
undefined4 BuildDiplomacyOverlayHitMaskOpcodeStream_Impl(void)
{
  return 0;
}

// ghidra_name WrapperFor_ftol_At004d64d0
// ghidra_proto undefined WrapperFor_ftol_At004d64d0()
// FUNCTION: IMPERIALISM 0x004d64d0
undefined4 WrapperFor_ftol_At004d64d0(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004d6880
// ghidra_proto undefined WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004d6880()
// FUNCTION: IMPERIALISM 0x004d6880
undefined4 WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004d6880(void)
{
  return 0;
}

// ghidra_name CString::operator=
// ghidra_proto CString & __thiscall operator=(CString const &)
// FUNCTION: IMPERIALISM 0x004d6b70
undefined4 CString_operator(void)
{
  return 0;
}

// ghidra_name ClassifyNationMilitaryPowerBandAgainstGlobalMean
// ghidra_proto undefined ClassifyNationMilitaryPowerBandAgainstGlobalMean()
// FUNCTION: IMPERIALISM 0x004d84b0
undefined4 ClassifyNationMilitaryPowerBandAgainstGlobalMean(void)
{
  return 0;
}

// ghidra_name TDeluxeText::BuildCityInfluenceLevelMap
// ghidra_proto char * __thiscall BuildCityInfluenceLevelMap(void)
// FUNCTION: IMPERIALISM 0x004dbbb0
undefined4 BuildCityInfluenceLevelMap(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackA
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackA()
// FUNCTION: IMPERIALISM 0x004dd810
undefined4 GetCityProductionValueTimesTwoCallbackA(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackB
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackB()
// FUNCTION: IMPERIALISM 0x004dd823
undefined4 GetCityProductionValueTimesTwoCallbackB(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueCallbackBase
// ghidra_proto undefined GetCityProductionValueCallbackBase()
// FUNCTION: IMPERIALISM 0x004dd836
undefined4 GetCityProductionValueCallbackBase(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackC
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackC()
// FUNCTION: IMPERIALISM 0x004dd847
undefined4 GetCityProductionValueTimesTwoCallbackC(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackD
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackD()
// FUNCTION: IMPERIALISM 0x004dd85a
undefined4 GetCityProductionValueTimesTwoCallbackD(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackE
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackE()
// FUNCTION: IMPERIALISM 0x004dd86d
undefined4 GetCityProductionValueTimesTwoCallbackE(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackF
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackF()
// FUNCTION: IMPERIALISM 0x004dd880
undefined4 GetCityProductionValueTimesTwoCallbackF(void)
{
  return 0;
}

// ghidra_name GetCityProductionValueTimesTwoCallbackG
// ghidra_proto undefined GetCityProductionValueTimesTwoCallbackG()
// FUNCTION: IMPERIALISM 0x004dd893
undefined4 GetCityProductionValueTimesTwoCallbackG(void)
{
  return 0;
}

// ghidra_name ComputeNationNavyOrderWeightedMovementScore
// ghidra_proto undefined ComputeNationNavyOrderWeightedMovementScore()
// FUNCTION: IMPERIALISM 0x004e3060
undefined4 ComputeNationNavyOrderWeightedMovementScore(void)
{
  return 0;
}

// ghidra_name RecomputeNationComparativePowerMetrics_Impl
// ghidra_proto undefined RecomputeNationComparativePowerMetrics_Impl()
// FUNCTION: IMPERIALISM 0x004e3220
undefined4 RecomputeNationComparativePowerMetrics_Impl(void)
{
  return 0;
}

// ghidra_name RecomputeNationEconomyAndDiplomacySummaryMetrics
// ghidra_proto undefined RecomputeNationEconomyAndDiplomacySummaryMetrics()
// FUNCTION: IMPERIALISM 0x004e32a0
undefined4 RecomputeNationEconomyAndDiplomacySummaryMetrics(void)
{
  return 0;
}

// ghidra_name RefreshMapSystemsAndPrepareOrderExecution_Impl
// ghidra_proto undefined RefreshMapSystemsAndPrepareOrderExecution_Impl()
// FUNCTION: IMPERIALISM 0x004e3560
undefined4 RefreshMapSystemsAndPrepareOrderExecution_Impl(void)
{
  return 0;
}

// ghidra_name SumDiplomacyGrantEntriesMaskedToValueBits
// ghidra_proto undefined SumDiplomacyGrantEntriesMaskedToValueBits()
// FUNCTION: IMPERIALISM 0x004e3620
undefined4 SumDiplomacyGrantEntriesMaskedToValueBits(void)
{
  return 0;
}

// ghidra_name WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004e37c0
// ghidra_proto undefined WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004e37c0()
// FUNCTION: IMPERIALISM 0x004e37c0
undefined4 WrapperFor_ReleaseSharedStringRefIfNotEmpty_At004e37c0(void)
{
  return 0;
}

