// AUTOGENERATED FILE. DO NOT EDIT.
// Regenerate with: uv run python -m tools.stubgen

#include "decomp_types.h"

// ghidra_name thunk_ReleaseHashIndexedRecordByHandle
// ghidra_proto void __fastcall thunk_ReleaseHashIndexedRecordByHandle(int ecxArg, int arg1)
// FUNCTION: IMPERIALISM 0x004020fe
undefined4 thunk_ReleaseHashIndexedRecordByHandle(void)
{
  return 0;
}

// ghidra_name thunk_DispatchTurnEvent1AWithNationActionPayload
// ghidra_proto void __cdecl thunk_DispatchTurnEvent1AWithNationActionPayload(void)
// FUNCTION: IMPERIALISM 0x004022c5
undefined4 thunk_DispatchTurnEvent1AWithNationActionPayload(void)
{
  return 0;
}

// ghidra_name TAdmiral::thunk_GenerateMappedFlavorTextByNationSlotField0C
// ghidra_proto void __thiscall thunk_GenerateMappedFlavorTextByNationSlotField0C(int arg1)
// FUNCTION: IMPERIALISM 0x0040231a
undefined4 thunk_GenerateMappedFlavorTextByNationSlotField0C(void)
{
  return 0;
}

// ghidra_name TMapEditCluster::thunk_DispatchPanelControlEvent
// ghidra_proto void __thiscall thunk_DispatchPanelControlEvent(int nEventClass, PanelEventPayload * pEventPayload, int nEventFlags)
// FUNCTION: IMPERIALISM 0x004023ab
undefined4 thunk_DispatchPanelControlEvent(void)
{
  return 0;
}

// ghidra_name thunk_InitializeCityProductionState
// ghidra_proto void __fastcall thunk_InitializeCityProductionState(int ecxArg, int arg1)
// FUNCTION: IMPERIALISM 0x004023d3
undefined4 thunk_InitializeCityProductionState(void)
{
  return 0;
}

// ghidra_name thunk_ShowCivilianLedgerDialogAndSelectUnit
// ghidra_proto void __cdecl thunk_ShowCivilianLedgerDialogAndSelectUnit(void)
// FUNCTION: IMPERIALISM 0x00402469
undefined4 thunk_ShowCivilianLedgerDialogAndSelectUnit(void)
{
  return 0;
}

// ghidra_name thunk_GetWrappedHexNeighborTileIndexByDirection
// ghidra_proto void __cdecl thunk_GetWrappedHexNeighborTileIndexByDirection(void)
// FUNCTION: IMPERIALISM 0x0040246e
undefined4 thunk_GetWrappedHexNeighborTileIndexByDirection(void)
{
  return 0;
}

// ghidra_name thunk_NoOpQuickDrawLifecycleHookB
// ghidra_proto void __cdecl thunk_NoOpQuickDrawLifecycleHookB(void)
// FUNCTION: IMPERIALISM 0x004024fa
undefined4 thunk_NoOpQuickDrawLifecycleHookB(void)
{
  return 0;
}

// ghidra_name thunk_GetCityBuildingProductionValueBySlot
// ghidra_proto int __thiscall thunk_GetCityBuildingProductionValueBySlot(short nBuildingSlotId)
// FUNCTION: IMPERIALISM 0x0040257c
undefined4 thunk_GetCityBuildingProductionValueBySlot(void)
{
  return 0;
}

// ghidra_name thunk_InitializeCityInteriorMinister
// ghidra_proto void __cdecl thunk_InitializeCityInteriorMinister(void)
// FUNCTION: IMPERIALISM 0x004028d8
undefined4 thunk_InitializeCityInteriorMinister(void)
{
  return 0;
}

// ghidra_name THQButton::thunk_DrawTextWithCachedQuickDrawStyleState
// ghidra_proto void __thiscall thunk_DrawTextWithCachedQuickDrawStyleState(void)
// FUNCTION: IMPERIALISM 0x004029aa
undefined4 thunk_DrawTextWithCachedQuickDrawStyleState(void)
{
  return 0;
}

// ghidra_name thunk_RelaxMapTileCostFieldByNeighborTerrain
// ghidra_proto void __cdecl thunk_RelaxMapTileCostFieldByNeighborTerrain(int arg1)
// FUNCTION: IMPERIALISM 0x004029d2
undefined4 thunk_RelaxMapTileCostFieldByNeighborTerrain(void)
{
  return 0;
}

// ghidra_name thunk_InitializeUiTextStyleDescriptor
// ghidra_proto void __cdecl thunk_InitializeUiTextStyleDescriptor(int arg1, int arg2, int arg3, int arg4, int arg5)
// FUNCTION: IMPERIALISM 0x00402a7c
undefined4 thunk_InitializeUiTextStyleDescriptor(void)
{
  return 0;
}

// ghidra_name thunk_SetUiResourceContextTagWord
// ghidra_proto void __cdecl thunk_SetUiResourceContextTagWord(void)
// FUNCTION: IMPERIALISM 0x00402aa4
undefined4 thunk_SetUiResourceContextTagWord(void)
{
  return 0;
}

// ghidra_name thunk_SetQuickDrawStylePair_1D08_1D0C_AndMarkDirty
// ghidra_proto void __cdecl thunk_SetQuickDrawStylePair_1D08_1D0C_AndMarkDirty(short styleParamA, short styleParamB)
// FUNCTION: IMPERIALISM 0x00402e73
undefined4 thunk_SetQuickDrawStylePair_1D08_1D0C_AndMarkDirty(void)
{
  return 0;
}

// ghidra_name thunk_ConstructFrogCityMarker
// ghidra_proto void __thiscall thunk_ConstructFrogCityMarker(void)
// FUNCTION: IMPERIALISM 0x00403044
undefined4 thunk_ConstructFrogCityMarker(void)
{
  return 0;
}

